const https=require('node:https'),http=require('node:http'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {createReadStream}=require('node:fs'),{randomBytes,randomUUID,createHash}=require('node:crypto');
const forge=require('node-forge'),QR=require('qrcode'),{atomicJson}=require('./library.cjs');
const hash=v=>createHash('sha256').update(v).digest('hex');
function privateAddress(ip){ip=String(ip).replace(/^::ffff:/,'');return ip==='127.0.0.1'||ip==='::1'||/^10\./.test(ip)||/^192\.168\./.test(ip)||/^172\.(1[6-9]|2\d|3[01])\./.test(ip);}
function addresses(){return ['127.0.0.1',...Object.values(os.networkInterfaces()).flat().filter(i=>i.family==='IPv4'&&!i.internal&&privateAddress(i.address)).map(i=>i.address)];}
async function preferredAddresses(){
 const ips=addresses();
 if(process.platform==='win32')try{
  const {stdout}=await require('node:util').promisify(require('node:child_process').execFile)('route.exe',['print','-4'],{windowsHide:true,timeout:5000});
  const routes=stdout.split(/\r?\n/).map(line=>line.trim().split(/\s+/)).filter(parts=>parts[0]==='0.0.0.0'&&parts[1]==='0.0.0.0').sort((a,b)=>Number(a[4])-Number(b[4]));
  const preferred=routes.find(parts=>ips.includes(parts[3]))?.[3];
  if(preferred)return ['127.0.0.1',preferred,...ips.filter(ip=>ip!==preferred&&ip!=='127.0.0.1')];
 }catch{}
 return ips;
}
async function body(req,limit=8*1024*1024){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>limit){const e=new Error('파일 또는 요청 크기가 너무 큽니다.');e.status=413;throw e;}chunks.push(chunk);}return Buffer.concat(chunks);}
async function keys(){const pair=await require('node:util').promisify(require('node:crypto').generateKeyPair)('rsa',{modulusLength:2048,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}});return {publicKey:forge.pki.publicKeyFromPem(pair.publicKey),privateKey:forge.pki.privateKeyFromPem(pair.privateKey)};}
function certificate(pair,issuer,issuerKey,names,ca=false){const cert=forge.pki.createCertificate();cert.publicKey=pair.publicKey;cert.serialNumber='01'+randomBytes(15).toString('hex');cert.validity.notBefore=new Date(Date.now()-300000);cert.validity.notAfter=new Date(Date.now()+(ca?365*3:180)*86400000);cert.setSubject([{name:'commonName',value:ca?'LOXT Personal Device CA':'LOXT Personal Server'}]);cert.setIssuer(issuer?.subject.attributes||cert.subject.attributes);cert.setExtensions([{name:'basicConstraints',cA:ca},{name:'keyUsage',digitalSignature:true,keyEncipherment:!ca,keyCertSign:ca},...(ca?[]:[{name:'extKeyUsage',serverAuth:true}]),...(!ca?[{name:'subjectAltName',altNames:names.map(ip=>({type:7,ip}))}]:[])]);cert.sign(issuerKey||pair.privateKey,forge.md.sha256.create());return cert;}
class DeviceServer{
 constructor({root,dist,rpc,asset,onState,previewCheck,previewLocal}){Object.assign(this,{root,dist,rpc,asset,onState,previewCheck,previewLocal});this.clients=new Set();this.pending=new Map();this.results=new (require('./request-cache.cjs').RequestCache)();this.eventRevision=0;this.attempts=new Map();this.configuration=null;this.running=false;this.lastError='';}
 async initialize(){await fs.mkdir(this.root,{recursive:true});try{this.configuration=JSON.parse(await fs.readFile(path.join(this.root,'devices.json'),'utf8'));}catch(e){if(e.code!=='ENOENT')throw e;this.configuration={version:1,hostId:randomUUID(),enabled:false,devices:[]};await this.persist();}if(this.configuration.enabled)await this.start().catch(e=>{this.lastError=e.message;});return this.snapshot();}
 persist(){this.write=(this.write||Promise.resolve()).catch(()=>{}).then(()=>atomicJson(path.join(this.root,'devices.json'),this.configuration));this.write=this.write.catch(e=>{this.lastError=e.message;throw e;});return this.write;}
 snapshot(){return {hostId:this.configuration?.hostId,enabled:Boolean(this.configuration?.enabled),running:this.running,error:this.lastError,addresses:(this.running?this.ips||[]:[]).filter(ip=>ip!=='127.0.0.1').map(ip=>`https://${ip}:${this.port}/web.html`),bootstrap:(this.running?this.ips||[]:[]).filter(ip=>ip!=='127.0.0.1').map(ip=>`http://${ip}:${this.bootstrapPort}/`),fingerprint:this.fingerprint,certificateExpires:this.certificateExpires,certificateRenewed:this.certificateRenewed||false,devices:(this.configuration?.devices||[]).map(({id,name,lastSeen,expires})=>({id,name,lastSeen,expires,expired:expires<=Date.now()})),pending:[...this.pending].filter(([,v])=>v.expires>Date.now()&&v.requested&&!v.approved&&!v.denied).map(([id,v])=>({id,name:v.name})),pairURL:this.running&&this.pending.get(this.pairToken)?.expires>Date.now()?this.pairURL:'',pairExpires:this.pending.get(this.pairToken)?.expires||null,qr:this.running&&this.pending.get(this.pairToken)?.expires>Date.now()?this.qr||'':''};}
 notify(){this.onState?.(this.snapshot());}
 async configure(enabled){await this.initializeIfNeeded();this.configuration.enabled=Boolean(enabled);await this.persist();if(enabled)await this.start();else await this.stop();this.notify();return this.snapshot();}
 async initializeIfNeeded(){if(!this.configuration)await this.initialize();}
 async start(){if(this.starting)return this.starting;this.starting=this.startNow().finally(()=>{this.starting=null;});return this.starting;}
 async startNow(){if(this.running)return;this.lastError='';this.ips=await preferredAddresses();let caPair,ca;
  try{const saved=JSON.parse(await fs.readFile(path.join(this.root,'tls.json'),'utf8'));caPair={privateKey:forge.pki.privateKeyFromPem(saved.key),publicKey:forge.pki.publicKeyFromPem(saved.public)};ca=forge.pki.certificateFromPem(saved.cert);if(ca.validity.notAfter<Date.now()+86400000){await fs.rename(path.join(this.root,'tls.json'),path.join(this.root,'tls.expired-'+Date.now()+'.json'));const expired=Error('expired');expired.code='ENOENT';this.certificateRenewed=true;throw expired;}}catch(e){if(e.code!=='ENOENT')throw e;caPair=await keys();ca=certificate(caPair,null,null,[],true);await atomicJson(path.join(this.root,'tls.json'),{key:forge.pki.privateKeyToPem(caPair.privateKey),public:forge.pki.publicKeyToPem(caPair.publicKey),cert:forge.pki.certificateToPem(ca)});}
  this.certificateExpires=ca.validity.notAfter.toISOString();this.caPem=forge.pki.certificateToPem(ca);this.fingerprint=hash(Buffer.from(forge.asn1.toDer(forge.pki.certificateToAsn1(ca)).getBytes(),'binary'));
  const serverPair=await keys(),cert=certificate(serverPair,ca,caPair.privateKey,this.ips);this.server=https.createServer({key:forge.pki.privateKeyToPem(serverPair.privateKey),cert:forge.pki.certificateToPem(cert)+this.caPem},(req,res)=>this.serve(req,res).catch(e=>this.error(res,e)));
  require('./device-socket.cjs').attachSockets(this,privateAddress);
  this.bootstrap=http.createServer((req,res)=>{if(!privateAddress(req.socket.remoteAddress)||!this.validHost(req,this.bootstrapPort)){res.writeHead(403);res.end();return;}if(req.url==='/loxt-ca.crt'){res.writeHead(200,{'Content-Type':'application/x-x509-ca-cert','Content-Disposition':'attachment; filename="LOXT-Personal-CA.crt"'});res.end(this.caPem);}else{res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'});res.end(`LOXT 개인 기기 연결\n\n노트북의 LOXT에서 표시한 인증서 지문과 비교하세요.\n${this.fingerprint}\n\n공개 인증서: /loxt-ca.crt\n아이폰·아이패드: 인증서 설치 후 설정 > 일반 > 정보 > 인증서 신뢰 설정에서 이 PC의 LOXT 인증서를 신뢰하세요.\n그다음 PC의 QR을 스캔하거나 연결 주소를 복사해 여세요.\n이 주소에는 보관함 데이터가 없습니다.`);}});
  try{await new Promise((resolve,reject)=>{this.server.once('error',reject);this.server.listen(this.configuration.port||0,'0.0.0.0',resolve);});this.port=this.server.address().port;await new Promise((resolve,reject)=>{this.bootstrap.once('error',reject);this.bootstrap.listen(this.configuration.bootstrapPort||0,'0.0.0.0',resolve);});this.bootstrapPort=this.bootstrap.address().port;this.configuration.port=this.port;this.configuration.bootstrapPort=this.bootstrapPort;await this.persist();this.running=true;await this.newQR();this.networkTimer=setInterval(()=>{if(addresses().sort().join(',')!==[...this.ips].sort().join(','))this.stop().then(()=>this.start()).catch(e=>{this.lastError=e.message;this.notify();});},10000);this.networkTimer.unref();this.notify();}catch(e){await this.stop();this.lastError=e.message;throw e;}
 }
 validHost(req,port){try{const u=new URL('http://'+req.headers.host);return this.ips?.includes(u.hostname)&&Number(u.port)===port;}catch{return false;}}
 async newQR(){if(!this.running)throw new Error('먼저 연결 서버를 켜 주세요.');for(const [k,v]of this.pending)if(v.expires<Date.now()||!v.requested)this.pending.delete(k);if(this.pending.size>=20)throw new Error('대기 중인 연결 요청을 먼저 승인하거나 거절해 주세요.');const token=randomBytes(24).toString('hex');this.pending.set(token,{expires:Date.now()+300000});const ip=this.ips.find(i=>i!=='127.0.0.1')||'127.0.0.1';this.pairToken=token;this.pairURL=`https://${ip}:${this.port}/web.html#pair=${token}`;this.qr=await QR.toDataURL(this.pairURL);this.notify();return this.snapshot();}
 async copyAddress(kind,index=0){if(!this.running)throw new Error('연결 서버가 중지되어 있습니다. 먼저 연결을 켜 주세요.');if(kind==='pair'){if(!this.pending.has(this.pairToken)||this.pending.get(this.pairToken).expires<=Date.now())await this.newQR();return this.pairURL;}if(!['reconnect','bootstrap'].includes(kind)||!Number.isInteger(index)||index<0)throw new Error('연결 주소 종류를 확인해 주세요.');const value=this.snapshot()[kind==='reconnect'?'addresses':'bootstrap'][index];if(!value)throw new Error('같은 Wi-Fi 연결 주소를 찾지 못했습니다.');return value;}
 session(req){const token=(req.headers.cookie||'').match(/(?:^|; )loxt=([a-f0-9]{64})/)?.[1];return token?this.configuration.devices.find(d=>d.token===hash(token)&&d.expires>Date.now()):null;}
 json(res,value,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));}
 error(res,e){if(!res.headersSent)this.json(res,{error:e.message,code:e.code},e.status|| (e.code==='CONFLICT'?409:400));else res.end();}
 async approve(id,allow){
  const p=this.pending.get(id);if(!p||p.expires<Date.now()||!p.requested)throw new Error('만료된 연결 요청입니다.');
  if(p.approving){if(!allow)throw new Error('연결을 승인하는 중입니다. 승인 후 연결된 기기에서 해제해 주세요.');return p.approving;}
  if(p.approved){if(allow)return;throw new Error('이미 승인된 기기입니다. 연결된 기기에서 해제해 주세요.');}
  if(p.denied)throw new Error('이미 거절된 연결 요청입니다. 새 QR을 생성해 주세요.');
  if(!allow){p.denied=true;p.expires=Math.min(p.expires,Date.now()+60000);this.notify();return;}
  if(this.configuration.devices.filter(d=>d.expires>Date.now()).length>=20)throw new Error('연결된 기기는 최대 20개입니다. 사용하지 않는 기기를 해제해 주세요.');
  const token=randomBytes(32).toString('hex'),device={id:randomUUID(),name:p.name,token:hash(token),csrf:randomBytes(24).toString('hex'),expires:Date.now()+30*86400000,lastSeen:new Date().toISOString()};
  const approval=(async()=>{this.configuration.devices.push(device);try{await this.persist();p.approved=true;p.token=token;this.notify();}catch(error){this.configuration.devices=this.configuration.devices.filter(d=>d.id!==device.id);throw error;}})();
  p.approving=approval;try{return await approval;}finally{p.approving=null;}
 }
 async revoke(id){for(const client of this.sockets||[])if(client.device.id===id)client.ws.close(1008);this.configuration.devices=this.configuration.devices.filter(d=>d.id!==id);await this.persist();for(const client of this.clients)if(client.device===id){client.res.end();this.clients.delete(client);}this.results.clear();this.notify();return this.snapshot();}
 event(type,value){this.sendSockets?.(type,value);const revision=++this.eventRevision;for(const client of this.clients){if(!this.configuration.devices.some(d=>d.id===client.device&&d.expires>Date.now())){client.res.end();this.clients.delete(client);continue;}const message=`id: ${revision}\nevent: ${type}\ndata: ${JSON.stringify(value)}\n\n`;if(client.blocked){if(type==='live-patch'&&value.append?.length){client.res.destroy();this.clients.delete(client);continue;}client.pending.set(type+(value.id||value.workspace||''),message);if(client.pending.size>64){client.res.destroy();this.clients.delete(client);}continue;}client.blocked=!client.res.write(message);}}

 async serve(req,res){if(!privateAddress(req.socket.remoteAddress)||!this.validHost(req,this.port)){res.writeHead(403);res.end();return;}const url=new URL(req.url,`https://${req.headers.host}`),origin=`https://${req.headers.host}`;if(req.headers.origin&&req.headers.origin!==origin){res.writeHead(403);res.end();return;}res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Cache-Control','no-store');
  if(url.pathname==='/api/pair'&&req.method==='POST'){const b=JSON.parse((await body(req,4096)).toString());const p=this.pending.get(b.token);const address=req.socket.remoteAddress;const count=this.attempts.get(address)||{count:0,time:Date.now()};if(Date.now()-count.time>60000){count.count=0;count.time=Date.now();}count.count++;this.attempts.set(address,count);if(this.attempts.size>1024)this.attempts.delete(this.attempts.keys().next().value);if(count.count>60||!p||p.expires<Date.now()){this.json(res,{error:'연결 요청이 만료되었습니다. PC에서 새 QR을 생성하거나 연결 주소를 다시 복사해 주세요.'},403);return;}if(p.requested&&p.nonce!==hash((req.headers.cookie||'').match(/(?:^|; )loxt_pair=([a-f0-9]{64})/)?.[1]||'')){this.json(res,{error:'다른 기기에서 사용 중인 QR입니다. PC에서 새 QR을 생성하거나 연결 주소를 다시 복사해 주세요.'},403);return;}if(p.denied){this.json(res,{error:'PC에서 연결 요청을 거절했습니다. PC에서 새 연결 주소를 받아 다시 요청하세요.',code:'PAIR_DENIED'},403);return;}if(p.approved){res.setHeader('Set-Cookie',`loxt=${p.token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000`);this.pending.delete(b.token);this.notify();this.json(res,{approved:true});return;}if(!p.requested){const nonce=randomBytes(32).toString('hex');p.nonce=hash(nonce);res.setHeader('Set-Cookie',`loxt_pair=${nonce}; HttpOnly; Secure; SameSite=Strict; Path=/api/pair; Max-Age=300`);p.requested=true;p.name=String(b.name||'모바일 기기').slice(0,80);}this.notify();this.json(res,{pending:true});return;}
  if(url.pathname.startsWith('/api/')){if(!['/api/session','/api/events','/api/rpc'].includes(url.pathname)){this.json(res,{error:'알 수 없는 API입니다.'},404);return;}const device=this.session(req);if(!device){this.json(res,{error:'이 기기의 승인이 만료되었거나 해제되었습니다. PC에서 새 연결 주소를 받아 다시 승인해 주세요.',code:'APPROVAL_REQUIRED'},401);return;}
   if(url.pathname==='/api/session'&&req.method==='GET'){device.lastSeen=new Date().toISOString();await this.persist();this.notify();this.json(res,{hostId:this.configuration.hostId,csrf:device.csrf,name:device.name,expires:device.expires});return;}
   if(url.pathname==='/api/events'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store'});res.write(': connected\n\n');if(this.clients.size>=40){res.end();return;}const client={device:device.id,res,blocked:false,pending:new Map()};res.on('drain',()=>{client.blocked=false;for(const [key,message] of client.pending){client.pending.delete(key);if(!res.write(message)){client.blocked=true;break;}}});res.write(`id: ${this.eventRevision}\nevent: resync\ndata: {}\n\n`);this.clients.add(client);const timer=setInterval(()=>res.write(': heartbeat\n\n'),15000);req.on('close',()=>{clearInterval(timer);this.clients.delete(client);});return;}
   if(req.method!=='POST'||req.headers['x-loxt-csrf']!==device.csrf){this.json(res,{error:'허용되지 않은 요청입니다.'},403);return;}
   const binary=req.headers['content-type']==='application/octet-stream';const b=binary?JSON.parse(decodeURIComponent(req.headers['x-loxt-meta']||'')):JSON.parse((await body(req,20*1024*1024)).toString());if(binary){b.payload.bytes=await body(req,128*1024*1024);}if(typeof b.method!=='string'||!/^[-a-zA-Z0-9.]+$/.test(b.method)||!/^[-a-f0-9]{36}$/.test(b.requestId||''))throw new Error('요청 형식을 확인해 주세요.');const key=device.id+':'+b.requestId;const started=performance.now(),{value,trace}=await require('./sync-trace.cjs').run(b.requestId,b.method,()=>this.results.run(key,b.method,()=>this.rpc(b.method,b.payload,{device:device.id,hostId:this.configuration.hostId})));this.timings.push({requestId:b.requestId,method:b.method,serverMs:Math.round((performance.now()-started)*10)/10,stages:trace.stages,at:new Date().toISOString()});this.timings=this.timings.slice(-100);this.json(res,{value});return;
  }
  if(url.pathname.startsWith('/file/')){if(!this.session(req)){res.writeHead(401);res.end();return;}const asset=await this.asset(url);const stat=await fs.lstat(asset.filename);if(!stat.isFile())throw new Error('파일을 찾지 못했습니다.');const range=req.headers.range?.match(/^bytes=(\d+)-(\d*)$/),start=range?Number(range[1]):0,end=range&&range[2]?Math.min(Number(range[2]),stat.size-1):stat.size-1;if(start>=stat.size||end<start){res.writeHead(416);res.end();return;}res.writeHead(range?206:200,{'Content-Type':asset.mime,...(asset.name?{'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(asset.name)}:{}),'Content-Length':end-start+1,'Accept-Ranges':'bytes',...(range?{'Content-Range':`bytes ${start}-${end}/${stat.size}`}:{})});if(req.method==='HEAD')res.end();else createReadStream(asset.filename,{start,end}).on('error',()=>res.destroy()).pipe(res);return;}
  if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return;}
  const relative=['/','/index.html'].includes(url.pathname)?'web.html':decodeURIComponent(url.pathname.slice(1)),filename=path.resolve(this.dist,relative);if(!filename.startsWith(path.resolve(this.dist)+path.sep)||relative.includes('..')||!(await fs.lstat(filename)).isFile())throw new Error('페이지를 찾지 못했습니다.');await require('./static-assets.cjs').serveStatic(req,res,filename,relative);
 }
 async stop(){this.closeSockets?.();clearInterval(this.networkTimer);for(const c of this.clients)c.res.end();this.clients.clear();for(const server of [this.server,this.bootstrap])if(server){server.closeAllConnections();await new Promise(resolve=>server.close(()=>resolve()));}this.running=false;this.pending.clear();this.pairToken=null;this.pairURL='';this.qr='';this.notify();}
}
module.exports={DeviceServer,privateAddress,body};
