import assert from 'node:assert/strict';
import {_electron as electron, chromium} from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import {PDFDocument} from 'pdf-lib';
const require=createRequire(import.meta.url),root=path.resolve('.');
const {Library}=require(path.join(root,'electron/library.cjs')),{Memos}=require(path.join(root,'electron/memos.cjs')),{PDFs}=require(path.join(root,'electron/pdfs.cjs')),{waveHeader}=require(path.join(root,'electron/pcm-wave.cjs'));
const out=path.join(root,'test-results/implementation-2.7.0');await fs.mkdir(out,{recursive:true});const profile=await fs.mkdtemp(path.join(out,'ui-profile-')),libraryRoot=path.join(profile,'LOXT');
await fs.mkdir(libraryRoot);await fs.writeFile(path.join(profile,'library-location.json'),JSON.stringify({version:1,root:libraryRoot}));
const source=path.join(profile,'sample.wav');await fs.writeFile(source,Buffer.concat([waveHeader(32000*32),Buffer.alloc(32000*32)]));
const pdf=await PDFDocument.create();pdf.addPage([595,842]);const pdfSource=path.join(profile,'example.pdf');await fs.writeFile(pdfSource,await pdf.save());
const samples={};const text=t=>[{type:'text',text:t,styles:{}}],block=(type,content,props={})=>({id:randomUUID(),type,content,props,children:[]});
for(const mode of ['work','live']){
 const lib=new Library(path.join(libraryRoot,mode+'-library'));await lib.ready;await lib.createFolder('혼합선택');await lib.createFolder({name:'하위 폴더',parent:'혼합선택'});await lib.createFolder('목적지');
 const memos=new Memos(lib);const memo=(await memos.create('혼합선택')).note;await lib.updateNote(memo.id,{title:'목차와 검색 테스트'});
 await memos.save({id:memo.id,revision:0,blocks:[block('heading',text('첫 제목'),{level:1}),block('heading',text('둘째 제목'),{level:2}),block('heading',text('셋째 제목'),{level:3}),block('paragraph',[{type:'text',text:'스타일',styles:{}},{type:'text',text:'검색',styles:{bold:true}}]),block('paragraph',text('일반검색 확인')),block('paragraph',text(''))]});
 const drawing=(await new PDFs(lib).create('혼합선택')).note;await lib.updateNote(drawing.id,{title:'그리기 테스트'});
 const paper=(await new PDFs(lib).import(await fs.readFile(pdfSource),'PDF 테스트','혼합선택')).note;
 const recording=(await lib.importAudio(source,'혼합선택')).note;await lib.updateNote(recording.id,{title:'녹음 테스트'});
 const script=(await lib.importAudio(source,'혼합선택')).note;await lib.updateNote(script.id,{title:mode+' 긴 스크립트'});await lib.completeTranscription(script.id,{seconds:32,segments:Array.from({length:24},(_,i)=>({start:i,end:i+1,text:`${mode} 예시 문장 ${i+1}`}))});
 if(mode==='work'){await lib.createFolder('대량 조회');for(let index=0;index<130;index++){const n=(await memos.create('대량 조회')).note;await lib.updateNote(n.id,{title:'범위 '+String(index).padStart(3,'0')});}}
 samples[mode]={memo:memo.id,drawing:drawing.id,pdf:paper.id,recording:recording.id,script:script.id};await lib.flushIndex();
}
const result={baseVersion:'2.7.0',profile,fixture:'Synthetic blocks, blank PDF and silent WAV; no microphone/GPU inference or user profile writes',checks:[],errors:[],screens:[]};let app,browser;
try{
 const env={...process.env,SORINOTE_TEST:'1',SORINOTE_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;delete env.SORINOTE_DEV;
 const exe=process.argv.slice(2).find(v=>v.endsWith('.exe'));app=await electron.launch({...(exe?{executablePath:path.resolve(exe)}:{}),args:exe?[]:['.'],env});let page=await app.firstWindow();for(let n=0;n<80&&!page.url().endsWith('index.html');n++){await new Promise(r=>setTimeout(r,100));page=app.windows().find(p=>p.url().endsWith('index.html'))||page;}
 page.setDefaultTimeout(15000);page.on('pageerror',e=>result.errors.push(e.stack));await page.getByRole('heading',{name:'홈',exact:true}).waitFor();result.actualVersion=(await page.evaluate(()=>window.desktop.getAppInfo())).version;assert.equal(result.actualVersion,require(path.join(root,'package.json')).version);
 const main=()=>page.locator('.workspace-panel:not([hidden])');const screenshot=async name=>{await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,name+'.png')});result.screens.push(name+'.png');};
 await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html'));w.setSize(1440,960);w.show();});
 result.sidebar=await main().locator('.sidebar-create').evaluate(e=>({text:e.innerText,border:getComputedStyle(e).border,bg:getComputedStyle(e).backgroundColor,classes:e.className}));await screenshot('home-dark');
 await main().locator('.sidebar button[data-folder-drop="혼합선택"]').click();await main().locator('.note-card').last().waitFor();await page.waitForTimeout(250);
 await main().locator('.note-collection').focus();await page.keyboard.press('Control+a');result.mixedSelectionCount=await main().locator('.is-selected[data-note-id]').count();
 const memoCard=main().locator(`[data-note-id="${samples.work.memo}"]`);const box=await memoCard.locator('.note-open').boundingBox();await page.mouse.move(box.x+15,box.y+15);await page.mouse.down();await page.waitForTimeout(380);await page.mouse.move(box.x+50,box.y+40,{steps:3});await page.locator('.selection-drag').waitFor();result.mixedDragBadge=await page.locator('.selection-drag').innerText();assert.match(result.mixedDragBadge,/6개 항목/);assert.ok(!result.mixedDragBadge.startsWith('6개 녹음'));await screenshot('mixed-drag-badge');await page.keyboard.press('Escape');await page.mouse.up();
 assert.equal(await main().locator('.note-collection').isVisible(),true,'Canceled pointer release must not open a card');assert.equal(await main().locator('.bn-editor').count(),0,'Canceled pointer release must not open a card');result.previewTypes=await main().locator('.note-preview').evaluateAll(es=>es.map(e=>({label:e.getAttribute('aria-label'),text:e.innerText})));await screenshot('mixed-library');
 await memoCard.getByRole('button',{name:'목차와 검색 테스트 열기',exact:true}).click();await main().locator('.bn-editor').waitFor();result.firstClickAfterDragEscOpened=await main().locator('.bn-editor').count()>0;assert.equal(result.firstClickAfterDragEscOpened,true);if(!result.firstClickAfterDragEscOpened){await screenshot('drag-esc-first-click-lost');await memoCard.getByRole('button',{name:'목차와 검색 테스트 열기',exact:true}).click();}await main().locator('.bn-editor').waitFor();result.memoOutlineButtonCount=await main().getByRole('button',{name:'메모 목차',exact:true}).count();assert.equal(result.memoOutlineButtonCount,1);await main().getByRole('button',{name:'메모 목차',exact:true}).click();await main().locator('.memo-outline').waitFor();await screenshot('memo-outline');await page.keyboard.press('Escape');
 result.headings=await main().locator('.bn-editor h1,.bn-editor h2,.bn-editor h3,.bn-editor h4').evaluateAll(es=>es.map(e=>({tag:e.tagName,text:e.innerText})));
 await main().getByRole('button',{name:'메모에서 찾기',exact:true}).click();await main().getByRole('textbox',{name:'메모 검색어'}).fill('스타일검색');await page.waitForTimeout(350);result.styledSearchCount=await main().locator('.memo-search span').innerText();assert.match(result.styledSearchCount,/1/);await screenshot('memo-search-styled');await main().getByRole('textbox',{name:'메모 검색어'}).fill('일반검색');await page.waitForTimeout(350);result.plainSearchCount=await main().locator('.memo-search span').innerText();
 await main().getByRole('button',{name:'메모에서 찾기',exact:true}).click();await main().locator('.bn-editor [data-content-type="paragraph"] .bn-inline-content').last().click();await page.keyboard.type('#### ');await page.keyboard.type('제목 네 단계');await page.waitForTimeout(450);const memoState=await page.evaluate(id=>window.desktop.memos.get(id),samples.work.memo);result.h4InputBlocks=memoState.blocks.map(b=>({type:b.type,level:b.props?.level,text:(b.content||[]).map(v=>v.text||'').join('')})).filter(b=>b.text.includes('네 단계'));assert.equal(result.h4InputBlocks[0].type,'heading');assert.equal(result.h4InputBlocks[0].level,4);await screenshot('memo-heading-four');
 result.layouts=[];for(const theme of ['dark','light']){await page.evaluate(t=>window.desktop.appearance.set(t),theme);for(const width of [1440,1000,760,480]){await app.evaluate(({BrowserWindow},width)=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).setSize(width,900),width);await page.waitForTimeout(150);result.layouts.push(await page.evaluate(()=>({width:innerWidth,theme:document.documentElement.dataset.theme,overflow:document.documentElement.scrollWidth>innerWidth,tools:[...document.querySelectorAll('.workspace-panel:not([hidden]) .memo-tools button')].map(e=>{const r=e.getBoundingClientRect();return {label:e.getAttribute('aria-label'),height:r.height,width:r.width,visible:r.right<=innerWidth&&r.left>=0};})})));await screenshot(`memo-${width}-${theme}`);}}
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).setSize(1440,960));await page.evaluate(()=>window.desktop.appearance.set('dark'));await main().getByRole('button',{name:'보관함으로 돌아가기',exact:true}).click();
 await main().locator('.note-collection').focus();await main().locator('.library-page').dispatchEvent('contextmenu',{clientX:400,clientY:280});const emptyMenu=page.getByRole('menu',{name:'새로 추가하기',exact:true});await emptyMenu.waitFor();assert.equal(await page.evaluate(()=>document.activeElement.textContent.trim()),'폴더');await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.textContent.trim()),'PDF 불러오기');await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>document.activeElement.textContent.trim()),'폴더');await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.textContent.trim()),'새 녹음');await page.keyboard.press('Escape');assert.equal(await main().locator('.note-collection').evaluate(e=>e===document.activeElement),true);result.emptyContextKeyboard=true;
 await main().locator('.sidebar button[data-folder-drop="대량 조회"]').click();await main().getByRole('button',{name:'더 보기 · 10개 항목',exact:true}).waitFor();assert.equal(await main().locator('.note-card').count(),120);await main().locator('.note-collection').focus();await page.keyboard.press('Control+a');await page.keyboard.press('Delete');await page.getByRole('dialog').waitFor();result.rangeSelectionDialog=await page.getByRole('dialog').innerText();assert.match(result.rangeSelectionDialog,/130/);await page.getByRole('dialog').getByRole('button',{name:'취소',exact:true}).click();await main().getByRole('button',{name:'더 보기 · 10개 항목',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.workspace-panel:not([hidden]) .note-card').length===130);result.pageRange={first:120,total:130,allSelected:true};await screenshot('library-page-range');
 await page.getByRole('button',{name:'워크스페이스 선택',exact:true}).click();await page.getByRole('menuitemradio',{name:/^Live/}).click();result.liveSidebar=await main().locator('.sidebar-create').evaluate(e=>({text:e.innerText,border:getComputedStyle(e).border,bg:getComputedStyle(e).backgroundColor,classes:e.className}));
 await page.keyboard.press('Control+t');const dock=page.locator('.side-dock');await dock.getByRole('button',{name:'LOXT 폴더',exact:true}).click();await dock.locator('.folder-card').filter({hasText:'혼합선택'}).click();const liveCard=dock.locator(`[data-note-id="${samples.live.script}"]`);await liveCard.scrollIntoViewIfNeeded();await page.waitForTimeout(250);result.livePanelPreviewBefore=await liveCard.locator('.note-preview').innerText();result.livePreviewCounts=await page.evaluate(async id=>{const note=(await window.desktop.live.getLibrary()).notes.find(n=>n.id===id),detail=await window.desktop.getNote(id,'live');return {listSegments:note.segments.length,listCount:note.segmentCount,detailSegments:detail.segments.length};},samples.live.script);assert.equal(result.livePreviewCounts.listCount,24);result.livePanelMorePresent=await liveCard.locator('.preview-more').count();assert.equal(result.livePanelMorePresent,1);if(result.livePanelMorePresent){await liveCard.locator('.note-preview').evaluate(el=>el.scrollTop=el.scrollHeight);await page.waitForFunction(id=>document.querySelector('.side-dock [data-note-id="'+id+'"] .note-preview')?.textContent.includes('live 예시 문장 20'),samples.live.script);result.livePanelPreviewAfter=await liveCard.locator('.note-preview').innerText();assert.match(result.livePanelPreviewAfter,/live 예시 문장 20/);}await screenshot('live-panel-more');await dock.getByRole('button',{name:'패널 접기',exact:true}).click();
 await page.getByRole('button',{name:'워크스페이스 선택',exact:true}).click();await page.getByRole('menuitemradio',{name:/^Work/}).click();
 const server=await page.evaluate(()=>window.desktop.devices.configure(true));const pair=new URL(server.pairURL);pair.hostname='127.0.0.1';browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true});const web=await context.newPage();web.on('pageerror',e=>result.errors.push('web: '+e.stack));await web.goto(pair.toString());await web.getByText('PC에서 이 기기의 연결을 승인해 주세요.',{exact:true}).waitFor();await page.waitForFunction(async()=>(await window.desktop.devices.get()).pending.length>0);await page.evaluate(async()=>{const s=await window.desktop.devices.get();await window.desktop.devices.approve(s.pending[0].id,true);});await web.getByRole('heading',{name:'홈',exact:true}).waitFor();await web.getByRole('navigation',{name:'모바일 탐색'}).getByRole('button',{name:'보관함',exact:true}).click();await web.locator('.folder-card').filter({hasText:'혼합선택'}).click();await web.locator(`[data-note-id="${samples.work.memo}"]`).scrollIntoViewIfNeeded();await web.getByRole('button',{name:'목차와 검색 테스트 열기',exact:true}).click();await web.locator('.bn-editor').waitFor();result.mobileMemoButtons=await web.locator('.memo-tools button').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {label:e.getAttribute('aria-label'),height:r.height,width:r.width};}));assert.ok(result.mobileMemoButtons.every(b=>b.height>=44));await web.getByRole('button',{name:'메모 목차',exact:true}).click();await web.locator('.memo-outline').waitFor();assert.equal(await web.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await web.screenshot({path:path.join(out,'mobile-memo-390.png')});result.screens.push('mobile-memo-390.png');result.mobileBrowser=browser.version();result.physicalSafari=false;
 assert.deepEqual(result.errors,[]);result.completed=true;
}catch(error){result.failure=error.stack;process.exitCode=1;if(app){const p=app.windows().find(p=>p.url().endsWith('index.html'));if(p){await p.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});await fs.writeFile(path.join(out,'failure-dom.txt'),await p.locator('body').innerText().catch(()=>''));}}}
finally{await browser?.close().catch(()=>{});await app?.close().catch(()=>{});await fs.writeFile(path.join(out,'ui-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}
