const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),https=require('node:https'),{randomUUID}=require('node:crypto');
const {Library}=require('../electron/library.cjs'),{Memos}=require('../electron/memos.cjs'),{PDFs}=require('../electron/pdfs.cjs'),{DeviceServer}=require('../electron/device-server.cjs'),{recoverInstaller}=require('../electron/model-installation.cjs'),{webServices}=require('../electron/web-services.cjs');
async function fixture(run){await fs.mkdir('test-results/implementation-2.8.0/connection-unit',{recursive:true});const root=await fs.mkdtemp(path.resolve('test-results/implementation-2.8.0/connection-unit/profile-'));try{await run(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
async function stores(root){const work=new Library(path.join(root,'work')),live=new Library(path.join(root,'live'));await Promise.all([work.ready,live.ready]);return {work,live,service:webServices({libraries:{get:mode=>({work,live})[mode]},root:path.join(root,'exports')})};}
const blocks=text=>[{id:'p',type:'paragraph',props:{},content:[{type:'text',text,styles:{}}],children:[]}];
test('memo draft recovery creates an independent copy and copies attachments; permanent deletion of the original is safe',()=>fixture(async root=>{
 const {work,service}=await stores(root),memos=new Memos(work),{note}=await memos.create(),url=await memos.attach({id:note.id,name:'test.png',bytes:Buffer.from('exact attachment bytes')});await memos.save({id:note.id,revision:0,blocks:blocks('original')});const original=await memos.read(note.id),hostId=randomUUID(),draft=[...blocks('unsaved'),{id:'i',type:'image',props:{url},children:[]}],result=await service.rpc('draft.restore',{hostId,id:note.id,kind:'memo',data:{revision:9,blocks:draft}},{hostId});assert.notEqual(result.id,note.id);const restored=await memos.read(result.id),newURL=restored.blocks[1].props.url;assert.notEqual(newURL,url);assert.match(newURL,new RegExp(result.id));assert.deepEqual(await memos.read(note.id),original);assert.equal(restored.blocks[0].content[0].text,'unsaved');await work.updateNote(note.id,{deleted:true});await work.deleteTrash([note.id]);assert.equal(await fs.readFile((await memos.asset(newURL)).filename,'utf8'),'exact attachment bytes');await work.flushIndex();
}));
test('foreign host or unreadable attachment rejects draft recovery before creating any copy',()=>fixture(async root=>{
 const {work,service}=await stores(root),hostId=randomUUID(),{note}=await new Memos(work).create(),count=work.data.notes.length;
 await assert.rejects(service.rpc('draft.restore',{hostId:randomUUID(),id:note.id,kind:'memo',data:{revision:0,blocks:blocks('x')}},{hostId}),/원래 PC/);
 const url=`loxt-asset://memo/${note.id}/${randomUUID()}.png`;await assert.rejects(service.rpc('draft.restore',{hostId,id:note.id,kind:'memo',data:{revision:0,blocks:[{id:'i',type:'image',props:{url},children:[]}]}},{hostId}));assert.equal(work.data.notes.length,count);await work.flushIndex();
}));
test('Live draft restores into Live and leaves Work unchanged',()=>fixture(async root=>{
 const {work,live,service}=await stores(root),memos=new Memos(live),{note}=await memos.create(),hostId=randomUUID(),result=await service.rpc('draft.restore',{hostId,id:note.id,kind:'memo',data:{revision:1,blocks:blocks('live offline')}},{hostId});assert.equal(result.workspace,'live');assert.equal(work.data.notes.length,0);assert.equal((await memos.read(result.id)).blocks[0].content[0].text,'live offline');await live.flushIndex();
}));
test('drawing draft restores reordered multi-page IDs and ink without changing original; duplicate IDs fail first',()=>fixture(async root=>{
 const {work,service}=await stores(root),pdf=new PDFs(work),{note}=await pdf.create(),hostId=randomUUID(),ids=[randomUUID(),randomUUID()],object={id:randomUUID(),type:'pen',page:2,pageId:ids[1],color:'#387a97',width:2,points:[[20,20],[40,40]]},original=await pdf.read(note.id),before=Buffer.from(await fs.readFile(pdf.file(note.id)));
 const result=await service.rpc('draft.restore',{hostId,id:note.id,kind:'pdf',data:{revision:4,pageIds:ids,objects:[object]}},{hostId}),restored=await pdf.read(result.id);assert.deepEqual(restored.pageIds,ids);assert.equal(restored.objects[0].pageId,ids[1]);assert.equal((await work.detail(result.id)).pages,2);assert.deepEqual(await pdf.read(note.id),original);assert.deepEqual(await fs.readFile(pdf.file(note.id)),before);
 const count=work.data.notes.length;await assert.rejects(service.rpc('draft.restore',{hostId,id:note.id,kind:'pdf',data:{revision:4,pageIds:[ids[0],ids[0]],objects:[]}},{hostId}),/고유/);assert.equal(work.data.notes.length,count);await assert.rejects(service.rpc('draft.restore',{hostId,id:note.id,kind:'pdf',data:{revision:4,pageIds:ids,objects:[{...object,pageId:randomUUID()}]}},{hostId}),/삭제되거나 변경/);assert.equal(work.data.notes.length,count);await assert.rejects(service.rpc('draft.restore',{hostId,id:note.id,kind:'pdf',data:{revision:4,pageIds:ids,objects:[{...object,page:3}]}},{hostId}),/페이지/);assert.equal(work.data.notes.length,count);await work.flushIndex();
}));
const journal=(extra={})=>({version:1,id:'small',stage:'.installer-stage-small',backup:'.installer-backup-small',hadTarget:true,state:'staged',...extra});
async function writeJournal(root,value){await fs.mkdir(path.join(root,'models'),{recursive:true});await fs.writeFile(path.join(root,'models','installer-model-journal.json'),JSON.stringify(value));}
async function model(root,name,text){await fs.mkdir(path.join(root,'models',name),{recursive:true});await fs.writeFile(path.join(root,'models',name,'model.bin'),text);}
test('installer rollback preserves both previous target and unfinished replacement and is restart-idempotent',()=>fixture(async root=>{
 await model(root,'small','new');await model(root,'.installer-backup-small','old');await writeJournal(root,journal());await recoverInstaller(root);assert.equal(await fs.readFile(path.join(root,'models/small/model.bin'),'utf8'),'old');assert.equal(await fs.readFile(path.join(root,'models/.installer-stage-small/model.bin'),'utf8'),'new');await recoverInstaller(root);
}));
test('installer committed journal requires target before removing backup; duplicate rollback paths preserve every file',()=>fixture(async root=>{
 await model(root,'.installer-backup-small','old');await writeJournal(root,journal({state:'committed'}));await assert.rejects(recoverInstaller(root),/백업은 보존/);assert.equal(await fs.readFile(path.join(root,'models/.installer-backup-small/model.bin'),'utf8'),'old');await model(root,'small','new');await model(root,'.installer-stage-small','stage');await writeJournal(root,journal());await assert.rejects(recoverInstaller(root),/중복/);for(const name of ['small','.installer-backup-small','.installer-stage-small'])assert.ok(await fs.stat(path.join(root,'models',name,'model.bin')));
}));
test('installer traversal and junction paths are refused without touching an outside sentinel',()=>fixture(async root=>{
 const outside=path.join(root,'outside');await fs.mkdir(outside);await fs.writeFile(path.join(outside,'sentinel'),'keep');for(const value of [journal({id:'../outside'}),journal({backup:'../outside'}),journal({stage:'../outside'})]){await writeJournal(root,value);await assert.rejects(recoverInstaller(root),/위치/);assert.equal(await fs.readFile(path.join(outside,'sentinel'),'utf8'),'keep');}
 await writeJournal(root,journal());await fs.symlink(outside,path.join(root,'models/small'),process.platform==='win32'?'junction':'dir');await assert.rejects(recoverInstaller(root),/연결된/);assert.equal(await fs.readFile(path.join(outside,'sentinel'),'utf8'),'keep');
}));
test('installer missing previous target and backup preserves the recovery journal rather than erasing evidence',()=>fixture(async root=>{
 await writeJournal(root,journal());await assert.rejects(recoverInstaller(root),/이전 모델/);assert.deepEqual(JSON.parse(await fs.readFile(path.join(root,'models/installer-model-journal.json'),'utf8')),journal());
}));
test('installer first-install rollback stages uncommitted target and committed recovery preserves the completed model',()=>fixture(async root=>{
 await model(root,'small','uncommitted');await writeJournal(root,journal({hadTarget:false}));await recoverInstaller(root);await assert.rejects(fs.stat(path.join(root,'models/small')),{code:'ENOENT'});assert.equal(await fs.readFile(path.join(root,'models/.installer-stage-small/model.bin'),'utf8'),'uncommitted');await model(root,'small','completed');await model(root,'.installer-backup-small','previous');await writeJournal(root,journal({state:'committed'}));await recoverInstaller(root);assert.equal(await fs.readFile(path.join(root,'models/small/model.bin'),'utf8'),'completed');await assert.rejects(fs.stat(path.join(root,'models/.installer-backup-small')),{code:'ENOENT'});
}));
test('twenty expired pairing slots are pruned; duplicate approval is idempotent and denied QR cannot be approved',()=>fixture(async root=>{
 const server=new DeviceServer({root,dist:'dist'});await server.initialize();server.running=true;server.ips=['127.0.0.1'];server.port=8844;for(let i=0;i<20;i++)server.pending.set('expired-'+i,{expires:Date.now()-1,requested:true});await server.newQR();assert.equal(server.pending.size,1);const token=server.pairToken,p=server.pending.get(token);Object.assign(p,{requested:true,name:'isolated'});await Promise.all([server.approve(token,true),server.approve(token,true)]);assert.equal(server.configuration.devices.length,1);await server.approve(token,true);assert.equal(server.configuration.devices.length,1);await server.newQR();const denied=server.pairToken;Object.assign(server.pending.get(denied),{requested:true,name:'denied'});await server.approve(denied,false);await assert.rejects(server.approve(denied,true),/거절/);assert.equal(server.configuration.devices.length,1);
}));
test('real HTTPS and WebSocket: denial differs from expiration; revoke rejects auth and fresh approval uses new CSRF',()=>fixture(async root=>{
 const dist=path.join(root,'dist');await fs.mkdir(dist);await fs.writeFile(path.join(dist,'web.html'),'isolated');const server=new DeviceServer({root:path.join(root,'server'),dist,rpc:async()=>({ok:true}),asset:async()=>{throw Error('unused');}});await server.initialize();await server.configure(true);
 const request=(route,{cookie,method='GET',body,headers={}}={})=>new Promise((resolve,reject)=>{const req=https.request({hostname:'127.0.0.1',port:server.port,path:route,ca:server.caPem,method,headers:{...headers,...(cookie?{Cookie:cookie}:{})}},res=>{let data='';res.on('data',v=>data+=v);res.on('end',()=>resolve({status:res.statusCode,value:JSON.parse(data||'{}'),cookie:res.headers['set-cookie']?.[0].split(';')[0]}));});req.on('error',reject);if(body)req.write(JSON.stringify(body));req.end();});
 const begin=async()=>{await server.newQR();const token=server.pairToken,pending=await request('/api/pair',{method:'POST',body:{token,name:'browser'}});return {token,cookie:pending.cookie};};
 const finish=async pair=>{await server.approve(pair.token,true);return request('/api/pair',{method:'POST',cookie:pair.cookie,body:{token:pair.token}});};
 let socket;try{const denied=await begin();await server.approve(denied.token,false);const deniedResponse=await request('/api/pair',{method:'POST',cookie:denied.cookie,body:{token:denied.token}});assert.equal(deniedResponse.value.code,'PAIR_DENIED');const expired=await begin();server.pending.get(expired.token).expires=Date.now()-1;const expiredResponse=await request('/api/pair',{method:'POST',cookie:expired.cookie,body:{token:expired.token}});assert.match(expiredResponse.value.error,/만료/);assert.notEqual(expiredResponse.value.code,'PAIR_DENIED');
  const pair=await begin(),approved=await finish(pair),session=(await request('/api/session',{cookie:approved.cookie})).value,WS=require('ws');socket=new WS(`wss://127.0.0.1:${server.port}/api/socket`,{ca:server.caPem,headers:{Cookie:approved.cookie,Origin:`https://127.0.0.1:${server.port}`}});await new Promise((resolve,reject)=>{socket.on('error',reject);socket.on('open',()=>socket.send(JSON.stringify({type:'hello',csrf:session.csrf})));socket.on('message',bytes=>{if(JSON.parse(bytes).type==='ready')resolve();});});
  const closed=new Promise(resolve=>socket.once('close',code=>resolve(code)));await server.revoke(server.configuration.devices[0].id);assert.equal(await closed,1008);assert.equal((await request('/api/session',{cookie:approved.cookie})).status,401);
  const again=await finish(await begin()),next=(await request('/api/session',{cookie:again.cookie})).value;assert.equal(next.hostId,session.hostId);assert.notEqual(next.csrf,session.csrf);const payload={method:'check',requestId:randomUUID(),payload:{}};assert.equal((await request('/api/rpc',{cookie:again.cookie,method:'POST',headers:{'X-LOXT-CSRF':session.csrf},body:payload})).status,403);assert.equal((await request('/api/rpc',{cookie:again.cookie,method:'POST',headers:{'X-LOXT-CSRF':next.csrf},body:payload})).status,200);
 }finally{socket?.terminate();await server.configure(false);}
}));
