const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {Library}=require('../electron/library.cjs'),{PDFs}=require('../electron/pdfs.cjs'),{Memos}=require('../electron/memos.cjs'),{PDFDocument}=require('pdf-lib');
async function profile(fn){const root=await fs.mkdtemp(path.resolve('test-results/documents-2.5-'));try{await fn(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
async function recording(root){const library=new Library(path.join(root,'work-library'));await library.ready;const source=path.join(root,'sample.wav');await fs.writeFile(source,'exact audio bytes');const {note}=await library.importAudio(source,'');await library.completeTranscription(note.id,{seconds:1,segments:[{start:0,end:1,text:'preserved script'}],language:'ko',model:'small'});const memo=new Memos(library);await memo.save({id:note.id,revision:0,blocks:[{id:note.id,type:'paragraph',content:[{type:'text',text:'preserved memo',styles:{}}],children:[]}]});await library.flushIndex();return {library,id:note.id};}
test('audio-only trash retains script, memo and identity through damaged-index recovery, ZIP and restore',()=>profile(async root=>{
 let {library,id}=await recording(root);await library.detachAudio(id);let original=await library.detail(id),audio=library.data.notes.find(n=>n.kind==='audio');assert.equal(original.audioMissing,true);assert.equal(original.deleted,false);assert.deepEqual(original.segments,[{start:0,end:1,text:'preserved script'}]);assert.equal(audio.done,false);assert.deepEqual(audio.segments,[]);assert.equal(audio.deleted,true);assert.equal(audio.hasMemo,false); // The attachment remains on the original, not in the audio directory.
 await assert.rejects(library.getAudio(id));assert.equal(await fs.readFile((await library.getAudio(audio.id)).filename,'utf8'),'exact audio bytes');
 await fs.writeFile(library.index,'damaged');await fs.writeFile(library.index+'.backup','damaged');library=new Library(library.root);await library.ready;assert.equal((await library.detail(id)).audioMissing,true);assert.equal((await new Memos(library).read(id)).blocks[0].content[0].text,'preserved memo');
 const zip=path.join(root,'script-only.zip');await require('../electron/folder-export.cjs').exportFolder({folder:''},{library,dialog:{showSaveDialog:async()=>({filePath:zip})}});const files=(await require('unzipper').Open.file(zip)).files;assert.ok(files.some(f=>f.path.endsWith('스크립트.txt')));assert.ok(!files.some(f=>f.path.endsWith('원본.wav')));
 await library.restoreTrash([audio.id]);assert.equal((await library.detail(id)).audioMissing,false);assert.ok(!library.data.notes.some(n=>n.id===audio.id));assert.equal(await fs.readFile((await library.getAudio(id)).filename,'utf8'),'exact audio bytes');
}));
test('permanent audio deletion and parent deletion never delete the other record; orphan audio restores independently',()=>profile(async root=>{
 const {library,id}=await recording(root);await library.detachAudio(id);let audio=library.data.notes.find(n=>n.kind==='audio');await library.deleteTrash([audio.id]);assert.equal((await library.detail(id)).segments[0].text,'preserved script');assert.equal((await new Memos(library).read(id)).blocks[0].content[0].text,'preserved memo');
 const second=await recording(path.join(root,'other'));await second.library.detachAudio(second.id);audio=second.library.data.notes.find(n=>n.kind==='audio');await second.library.updateNote(second.id,{deleted:true});await second.library.deleteTrash([second.id]);await second.library.restoreTrash([audio.id]);assert.equal((await second.library.detail(audio.id)).deleted,false);assert.equal(await fs.readFile((await second.library.getAudio(audio.id)).filename,'utf8'),'exact audio bytes');
}));
test('restoring selected script and detached audio together reconnects regardless of selection order',()=>profile(async root=>{
 for(const reverse of [false,true]){const {library,id}=await recording(path.join(root,String(reverse)));await library.detachAudio(id);const audio=library.data.notes.find(n=>n.kind==='audio');await library.updateNote(id,{deleted:true});await library.restoreTrash(reverse?[audio.id,id]:[id,audio.id]);assert.equal((await library.detail(id)).audioMissing,false);assert.equal((await library.detail(id)).deleted,false);assert.equal(await fs.readFile((await library.getAudio(id)).filename,'utf8'),'exact audio bytes');}
}));
test('interrupted audio transfer journal finishes after restart and duplicate detach is rejected',()=>profile(async root=>{
 const {library,id}=await recording(root),save=library.saveIndex.bind(library);library.saveIndex=async()=>{throw Error('simulated index write interruption');};await assert.rejects(library.detachAudio(id),/interruption/);library.saveIndex=save;const restarted=new Library(library.root);await restarted.ready;assert.equal((await restarted.detail(id)).audioMissing,true);const audio=restarted.data.notes.find(n=>n.kind==='audio');assert.equal(await fs.readFile((await restarted.getAudio(audio.id)).filename,'utf8'),'exact audio bytes');await assert.rejects(restarted.detachAudio(id));
}));
test('drawing page identity, duplicate, delete, undo, CAS, restart and exports preserve ink',()=>profile(async root=>{
 for(const mode of ['work','live']){let library=new Library(path.join(root,mode));await library.ready;let pdf=new PDFs(library);const {note}=await pdf.create(),ink={id:randomUUID(),type:'pen',page:1,color:'#387a97',width:2,points:[[30,30],[60,60]]};await pdf.save({id:note.id,revision:0,objects:[ink]});const {changeDrawingPage}=await import('../src/drawingPages.js');let doc=await pdf.read(note.id),before=structuredClone(doc),next=changeDrawingPage(doc,'duplicate',1);assert.notEqual(next.objects[0].id,next.objects[1].id);assert.notEqual(next.pageIds[0],next.pageIds[1]);await pdf.save({id:note.id,revision:doc.revision,objects:next.objects,pageIds:next.pageIds});doc=await pdf.read(note.id);assert.equal(doc.pageIds.length,2);const deleted=changeDrawingPage(doc,'delete',1);assert.equal(deleted.objects[0].id,next.objects[1].id);assert.equal(deleted.objects[0].page,1);await pdf.save({id:note.id,revision:doc.revision,...deleted});await assert.rejects(pdf.save({id:note.id,revision:doc.revision,objects:next.objects,pageIds:next.pageIds}),/다른 기기/);doc=await pdf.read(note.id);await pdf.save({id:note.id,revision:doc.revision,objects:next.objects,pageIds:next.pageIds});await library.flushIndex();library=new Library(library.root);await library.ready;pdf=new PDFs(library);assert.equal((await pdf.read(note.id)).pageIds.length,2);assert.equal((await pdf.export(note.id,false)).length>500,true);assert.equal((await PDFDocument.load(await pdf.export(note.id,true))).getPageCount(),2);assert.equal((await PDFDocument.load(await pdf.export(note.id,false))).getPageCount(),2);assert.throws(()=>changeDrawingPage(before,'delete',1));}
}));

test('drawing metadata recovers from a durable snapshot after deferred metadata interruption',()=>profile(async root=>{
 const library=new Library(root);await library.ready;const pdf=new PDFs(library),{note}=await pdf.create();const file=path.join(library.recordings,note.id,'annotations.json');await fs.writeFile(file,JSON.stringify({version:1,revision:1,pageIds:[note.id,randomUUID()],objects:[]}));const restarted=new Library(root);await restarted.ready;assert.equal((await restarted.detail(note.id)).pages,2);assert.equal((await new PDFs(restarted).read(note.id)).pageIds.length,2);
}));
