import {_electron as electron,chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{Library}=require('../electron/library.cjs'),{PDFs}=require('../electron/pdfs.cjs'),{Memos}=require('../electron/memos.cjs'),{PDFDocument}=require('pdf-lib'),{createCanvas}=require('@napi-rs/canvas');
const out=path.resolve('test-results/drawing-2.4.0');await fs.mkdir(out,{recursive:true});
const fixture=path.join(out,'large-image.pdf');
try{await fs.access(fixture);}catch{
 const canvas=createCanvas(1500,2000),ctx=canvas.getContext('2d'),image=ctx.createImageData(1500,2000);let seed=12345;
 for(let i=0;i<image.data.length;i+=4){for(let c=0;c<3;c++){seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;image.data[i+c]=seed>>>24;}image.data[i+3]=255;}ctx.putImageData(image,0,0);const jpg=await canvas.encode('jpeg',82),count=Math.ceil(90*1024*1024/jpg.length),doc=await PDFDocument.create();
 for(let n=0;n<count;n++){const picture=await doc.embedJpg(jpg),page=doc.addPage([595,842]);page.drawImage(picture,{x:0,y:0,width:595,height:842});page.drawText('Large PDF sample page '+(n+1),{x:30,y:790,size:16});}
 await fs.writeFile(fixture,await doc.save());canvas.width=canvas.height=1;
}
const profile=await fs.mkdtemp(path.join(out,'drawing-profile-')),root=path.join(profile,'LOXT');await fs.mkdir(root);await fs.writeFile(path.join(profile,'library-location.json'),JSON.stringify({version:1,root}));const library=new Library(path.join(root,'work-library'));await library.ready;
const large=(await new PDFs(library).import(new Uint8Array(await fs.readFile(fixture)),'대용량 테스트.pdf')).note,memo=(await new Memos(library).create()).note;await library.updateNote(memo.id,{title:'집중 메모'});
const results={version:'2.4.0',profile,synthetic:true,physicalIPad:false,fileBytes:(await fs.stat(fixture)).size,pages:large.pages,errors:[]};let app,browser;
try{
 const exe=process.argv.slice(2).find(v=>v.endsWith('.exe'));app=await electron.launch({...(exe?{executablePath:path.resolve(exe)}:{}),args:exe?[]:['.'],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,SORINOTE_TEST:'1',SORINOTE_TEST_DATA:profile}});let pc=await app.firstWindow();for(let i=0;i<80&&!pc.url().endsWith('index.html');i++){await new Promise(r=>setTimeout(r,100));pc=app.windows().find(w=>w.url().endsWith('index.html'))||pc;}await pc.getByRole('heading',{name:'홈',exact:true}).waitFor();const scope=pc.locator('[data-workspace=work]');
 pc.on('pageerror',e=>results.errors.push(e.message));await scope.getByRole('button',{name:'내 보관함',exact:true}).click();await scope.getByRole('button',{name:'새로 추가하기',exact:true}).click();await pc.getByRole('menuitem',{name:'그리기',exact:true}).click();await pc.waitForFunction(()=>document.querySelector('.pdf-sheet canvas')?.dataset.rendered==='true');
 const drawing=await pc.evaluate(async()=>(await window.desktop.getLibrary()).notes.find(n=>n.documentType==='drawing'));assert.ok(drawing);await scope.getByLabel('PDF 제목',{exact:true}).fill('새 필기 문서');await scope.getByLabel('PDF 제목',{exact:true}).press('Tab');await pc.waitForFunction(async id=>(await window.desktop.getNote(id)).title==='새 필기 문서',drawing.id);
 await scope.getByRole('button',{name:'전체화면',exact:true}).click();await pc.waitForFunction(()=>Math.abs((document.querySelector('.document-fullscreen')?.getBoundingClientRect().width||0)-innerWidth)<1);await scope.getByRole('button',{name:'필기 옵션',exact:true}).click();assert.ok(await pc.getByRole('dialog',{name:'필기 옵션'}).isVisible());await pc.keyboard.press('Escape');await scope.getByRole('button',{name:'PDF 내보내기',exact:true}).click();assert.ok(await pc.getByRole('menuitem',{name:'필기 포함 PDF'}).isVisible());await pc.keyboard.press('Escape');const box=await scope.locator('.pdf-sheet').boundingBox();await pc.mouse.move(box.x+40,box.y+80);await pc.mouse.down();await pc.mouse.move(box.x+160,box.y+120,{steps:10});await pc.mouse.up();await pc.waitForFunction(async id=>(await window.desktop.pdf.get({workspace:'work',id})).objects.length===1,drawing.id);const drawingShot=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));await fs.writeFile(path.join(out,'drawing-fullscreen.png'),Buffer.from(drawingShot,'base64'));await scope.getByRole('button',{name:'전체화면 종료',exact:true}).click();await scope.getByRole('button',{name:'보관함으로 돌아가기'}).click();results.drawing=true;results.fullscreenMenus=true;
 await scope.getByRole('button',{name:'집중 메모 열기',exact:true}).click();await scope.locator('.bn-editor').waitFor();await scope.getByRole('button',{name:'전체화면',exact:true}).click();await scope.locator('.bn-editor').click();await pc.keyboard.insertText('새로운 메모 내용');assert.equal(await scope.locator('.bn-side-menu').count(),0);await scope.getByRole('button',{name:'메모 내보내기',exact:true}).click();assert.ok(await pc.getByRole('menuitem',{name:'Markdown (.md)',exact:true}).isVisible());await pc.keyboard.press('Escape');await scope.getByRole('button',{name:'전체화면 종료',exact:true}).click();await scope.getByRole('button',{name:'보관함으로 돌아가기'}).click();results.memoFullscreen=true;
 const state=await pc.evaluate(()=>window.desktop.devices.configure(true));browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:820,height:1180},deviceScaleFactor:2,isMobile:true,hasTouch:true});const web=await ctx.newPage();web.setDefaultTimeout(60000);web.on('pageerror',e=>results.errors.push(e.message));let originalBytes=0,pngBytes=0;
 web.on('response',async response=>{if(response.url().includes('/file/pdf/'))originalBytes+=Number(response.headers()['content-length']||0);if(['image/png','image/jpeg'].includes(response.headers()['content-type']))pngBytes+=Number(response.headers()['content-length']||0);});
 await web.addInitScript(()=>{window.audit={resizes:0,longTasks:[]};const prop=Object.getOwnPropertyDescriptor(HTMLCanvasElement.prototype,'width');Object.defineProperty(HTMLCanvasElement.prototype,'width',{...prop,set(value){if(this.parentElement?.classList.contains('pdf-sheet'))window.audit.resizes++;prop.set.call(this,value);}});new PerformanceObserver(list=>window.audit.longTasks.push(...list.getEntries().map(e=>e.duration))).observe({type:'longtask',buffered:true});});
 await web.goto(`https://127.0.0.1:${new URL(state.pairURL).port}/web.html#pair=`+state.pairURL.split('#pair=')[1]);await web.getByText('PC에서 이 기기의 연결을 승인해 주세요.',{exact:true}).waitFor();await pc.evaluate(async()=>{const s=await window.desktop.devices.get();await window.desktop.devices.approve(s.pending[0].id,true);});await web.getByRole('heading',{name:'홈',exact:true}).waitFor();assert.equal(await web.locator('.mobile-navigation button').count(),3);
 const main=web.locator('[data-workspace=work]');await main.getByRole('button',{name:'보관함',exact:true}).click();const began=Date.now();await main.getByRole('button',{name:'대용량 테스트 열기',exact:true}).click();await web.waitForFunction(()=>document.querySelector('.pdf-sheet canvas')?.dataset.rendered==='true');results.largeOpenMs=Date.now()-began;await web.waitForTimeout(1000);
 assert.equal(originalBytes,0);assert.ok(await main.locator('.textLayer span').count());const cdp=await ctx.newCDPSession(web),scroll=await main.locator('.pdf-scroll').boundingBox(),x=scroll.x+scroll.width/2,y=scroll.y+150;if(await main.getByRole('button',{name:'페이지 미리보기',exact:true}).getAttribute('aria-expanded')==='true')await main.getByRole('button',{name:'페이지 미리보기',exact:true}).click();await web.waitForTimeout(300);await web.evaluate(()=>{window.audit.resizes=0;window.audit.longTasks=[];});const width=(await main.locator('.pdf-sheet').boundingBox()).width;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-35,y,id:1},{x:x+35,y,id:2}]});for(let n=0;n<20;n++){const d=40+n*4;await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-d,y,id:1},{x:x+d,y,id:2}]});await web.waitForTimeout(30);}results.resizesDuringPinch=await web.evaluate(()=>window.audit.resizes);assert.equal(results.resizesDuringPinch,0);const settle=Date.now();await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await web.waitForFunction(()=>!document.querySelector('.pdf-zoom-preview')&&!document.querySelector('.pdf-render-state'));results.zoomSettleMs=Date.now()-settle;
 const geometry=await web.evaluate(()=>{const c=document.querySelector('.pdf-sheet canvas');return {pixels:c.width*c.height,scale:visualViewport.scale,width:document.querySelector('.pdf-sheet').getBoundingClientRect().width,resizes:window.audit.resizes,longTasks:window.audit.longTasks};});assert.ok(geometry.pixels<=5_242_880);assert.equal(geometry.scale,1);assert.ok(geometry.width>width*2);assert.equal(geometry.resizes,1);results.largeZoom=geometry;results.originalBytes=originalBytes;results.previewBytes=pngBytes;assert.ok(pngBytes<results.fileBytes/4);
 await web.screenshot({path:path.join(out,'large-pdf-mobile.png')});await main.getByRole('button',{name:'전체화면',exact:true}).click();const focus=await main.locator('.document-fullscreen').boundingBox();assert.equal(focus.width,820);assert.equal(focus.height,1180);await main.getByRole('button',{name:'전체화면 종료',exact:true}).click();await main.getByRole('button',{name:'다음 PDF 페이지'}).click();await web.waitForTimeout(1500);assert.ok(await main.locator('.document-identity').innerText().then(s=>s.includes('2 /')));results.mobileFullscreen=true;assert.deepEqual(results.errors,[]);results.complete=true;
}catch(error){results.failure=error.stack;process.exitCode=1;console.error(error.stack);if(app)for(const page of app.windows())await page.screenshot({path:path.join(out,'drawing-failure.png')}).catch(()=>{});}finally{await browser?.close();if(app)await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await fs.writeFile(path.join(out,'drawing-ui-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));}
