const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {Library}=require('../electron/library.cjs'),{PDFs}=require('../electron/pdfs.cjs'),{PDFDocument}=require('pdf-lib'),{stopPDFJobs}=require('../electron/pdf-jobs.cjs');
test('Work and Live drawings retain identity, annotations, original PDF, rename and export across restart',async()=>{
 const root=await fs.mkdtemp(path.resolve('test-results/drawing-'));
 try{const stores=['work','live'].map(mode=>new Library(path.join(root,mode)));await Promise.all(stores.map(l=>l.ready));
  for(const library of stores){const pdf=new PDFs(library),{note}=await pdf.create();assert.equal(note.documentType,'drawing');assert.equal(note.pages,1);assert.equal((await pdf.info(note.id)).bytes,note.pdfBytes);const ink={id:randomUUID(),type:'pen',page:1,color:'#387a97',width:2,points:[[40,40],[80,90]]};await pdf.save({id:note.id,revision:0,objects:[ink]});await library.updateNote(note.id,{title:'필기 이름'});await library.flushIndex();const next=new Library(library.root);await next.ready;assert.equal((await next.detail(note.id)).documentType,'drawing');assert.equal((await next.detail(note.id)).title,'필기 이름');assert.deepEqual((await new PDFs(next).read(note.id)).objects,[ink]);const original=await pdf.export(note.id,false),annotated=await pdf.export(note.id,true);assert.equal((await PDFDocument.load(annotated)).getPageCount(),1);assert.ok(annotated.length>original.length);}
  assert.notEqual(stores[0].data.notes[0].id,stores[1].data.notes[0].id);
 }finally{stopPDFJobs();await fs.rm(root,{recursive:true,force:true});}
});
test('PC PDF worker caps pixels and produces durable searchable text off the main thread',async()=>{
 const root=await fs.mkdtemp(path.resolve('test-results/pdf-worker-'));try{const library=new Library(root);await library.ready;const pdf=new PDFs(library),doc=await PDFDocument.create();doc.addPage([595,842]).drawText('bounded page text');const {note}=await pdf.import(await doc.save(),'text.pdf');const preview=await pdf.preview(note.id,1,8);assert.ok(preview.width*preview.height<=5_242_880);assert.equal(Buffer.from(preview.bytes).subarray(1,4).toString(),'PNG');const [a,b]=await Promise.all([pdf.prepareIndex(note.id),pdf.prepareIndex(note.id)]);assert.deepEqual(a,b);assert.match(a.text,/bounded page text/);assert.deepEqual((await pdf.searchIndex(note.id)).pages,a.pages);const page=await pdf.page(note.id,1);assert.equal(page.content.items[0].str,'bounded page text');await library.flushIndex();}finally{stopPDFJobs();await fs.rm(root,{recursive:true,force:true});}
});
test('PC-rendered viewport preserves PDF coordinates at every supported rotation and zoom',async()=>{
 const {pageViewport}=await import('../src/pdfViewport.js');for(const rotation of [0,90,180,270])for(const scale of [.5,1,4]){const view=pageViewport({viewBox:[20,30,615,872],scale,rotation});const point=[127,642];const restored=view.convertToPdfPoint(...view.convertToViewportPoint(...point));assert.ok(restored.every((n,i)=>Math.abs(n-point[i])<.00001));const text=view.clone({dontFlip:true});assert.equal(text.width,view.width);assert.equal(text.rawDims.pageX,20);}
});
test('remote page preview files are bounded and old generated caches do not accumulate',async()=>{
 const root=await fs.mkdtemp(path.resolve('test-results/pdf-preview-'));try{const library=new Library(path.join(root,'library'));await library.ready;const {note}=await new PDFs(library).create();const cache=path.join(root,'exports','pdf-previews');await fs.mkdir(cache,{recursive:true});await fs.writeFile(path.join(cache,randomUUID()+'.jpg'),'stale generated cache');await fs.writeFile(path.join(cache,'keep.png'),'unrelated file');const {webServices}=require('../electron/web-services.cjs'),web=webServices({libraries:{get:()=>library},root:path.join(root,'exports')});for(let n=0;n<11;n++){const value=await web.rpc('pdf.preview',{workspace:'work',id:note.id,page:1,scale:.1});const asset=await web.asset(new URL('https://localhost'+value.download));assert.equal(asset.mime,'image/png');assert.equal(asset.name,null);}const names=await fs.readdir(cache);assert.ok(names.filter(n=>/^[a-f0-9-]{36}\.(jpg|png)$/.test(n)).length<=8);assert.equal(await fs.readFile(path.join(cache,'keep.png'),'utf8'),'unrelated file');assert.ok((await new PDFs(library).info(note.id)).bytes>500);await library.flushIndex();}finally{stopPDFJobs();await fs.rm(root,{recursive:true,force:true});}
});
