const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {Library}=require('../electron/library.cjs'),{Memos}=require('../electron/memos.cjs'),{LibraryActions}=require('../electron/library-actions.cjs'),{page}=require('../shared/library-range.cjs');
async function fixture(work){const root=await fs.mkdtemp(path.resolve('test-results/flow-2.8-'));try{await work(root);}finally{await fs.rm(root,{recursive:true,force:true});}}
test('discard is reversible with exact original, memo and attachment through restart and permanent deletion',()=>fixture(async root=>{
 let library=new Library(root);await library.ready;const {id}=await library.beginRecording({title:'Draft',folder:'',mime:'audio/wav'});await library.appendRecording({id,sequence:0,bytes:Buffer.alloc(32000,4)});
 const memos=new Memos(library);await memos.save({id,revision:0,blocks:[{id:'body',type:'paragraph',props:{},content:[{type:'text',text:'Keep this memo',styles:{}}],children:[]}]});await memos.attach({id,name:'keep.txt',bytes:Buffer.from('attachment')});await library.finishRecording({id,seconds:1});
 const before=await fs.readFile((await library.getAudio(id)).filename);await library.discardRecording(id);assert.equal((await library.detail(id)).deleted,true);await library.flushIndex();library=new Library(root);await library.ready;
 assert.equal((await new Memos(library).read(id)).blocks[0].content[0].text,'Keep this memo');assert.deepEqual(await fs.readFile((await library.getAudio(id)).filename),before);
 await library.restoreTrash([id]);assert.equal((await library.detail(id)).deleted,false);assert.deepEqual(await fs.readFile((await library.getAudio(id)).filename),before);
 await library.discardRecording(id);await library.deleteTrash([id]);await assert.rejects(fs.stat(path.join(root,'recordings',id)),{code:'ENOENT'});
}));
test('active partial WAV discard fixes header and remains playable after restart',()=>fixture(async root=>{
 let library=new Library(root);await library.ready;const {id}=await library.beginRecording({title:'Partial',folder:'',mime:'audio/wav'});await library.appendRecording({id,sequence:0,bytes:Buffer.alloc(64000)});await library.discardRecording(id);assert.equal(library.sessions.size,0);await library.flushIndex();library=new Library(root);await library.ready;
 const note=await library.detail(id),audio=await fs.readFile((await library.getAudio(id)).filename);assert.equal(note.deleted,true);assert.equal(note.seconds,2);assert.equal(audio.readUInt32LE(40),64000);await library.restoreTrash([id]);assert.equal((await library.detail(id)).deleted,false);
}));
test('interrupted discard journal preserves memo and completes safe trash after restart',()=>fixture(async root=>{
 let library=new Library(root);await library.ready;const {id}=await library.beginRecording({title:'Interrupted',folder:'',mime:'audio/webm'});await library.appendRecording({id,sequence:0,bytes:Buffer.from([1,2,3])});const memos=new Memos(library);await memos.save({id,revision:0,blocks:[{id:'body',type:'paragraph',props:{},content:[{type:'text',text:'Keep',styles:{}}],children:[]}]});await library.finishRecording({id,seconds:1});
 library.commitFolderRename=async()=>{throw Error('simulated crash');};await assert.rejects(library.discardRecording(id),/simulated crash/);library=new Library(root);await library.ready;assert.equal((await library.detail(id)).deleted,true);assert.equal((await new Memos(library).read(id)).blocks[0].content[0].text,'Keep');assert.deepEqual(await fs.readFile((await library.getAudio(id)).filename),Buffer.from([1,2,3]));
}));
test('user library folder and system all-records scope are distinct with legacy inference',()=>fixture(async root=>{
 const library=new Library(root);await library.ready;await library.createFolder('library');await library.createFolder('other');const memos=new Memos(library),a=(await memos.create('library')).note,b=(await memos.create('other')).note;
 assert.deepEqual((await page(library,{folder:'library',scope:'folder'})).notes.map(n=>n.id),[a.id]);assert.deepEqual((await page(library,{folder:'library'})).notes.map(n=>n.id),[a.id]);assert.deepEqual(new Set((await page(library,{folder:'library',scope:'system'})).notes.map(n=>n.id)),new Set([a.id,b.id]));await assert.rejects(page(library,{folder:'library',scope:'unknown'}));
}));
test('folder target payload moves and trashes full hierarchy in Work and Live stores',()=>fixture(async root=>{
 for(const mode of ['work','live']){const library=new Library(path.join(root,mode));await library.ready;await library.createFolder('source');await library.createFolder({name:'child',parent:'source'});await library.createFolder('destination');const note=(await new Memos(library).create('source/child')).note,actions=new LibraryActions(library);await actions.run({action:'move',ids:[],folders:['source'],folder:'destination'});assert.equal(library.data.folderParents['destination/source'],'destination');assert.equal((await library.detail(note.id)).folder,'destination/source/child');await actions.run({action:'trash',ids:[],folders:['destination/source']});assert.equal((await library.detail(note.id)).deleted,true);const group=library.data.notes.find(n=>n.kind==='folder');await library.restoreTrash([group.id]);assert.equal((await library.detail(note.id)).deleted,false);assert.equal(library.data.folderParents['destination/source'],'destination');}
}));
