const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const {Library}=require('../electron/library.cjs'),{LibraryActions}=require('../electron/library-actions.cjs'),{Memos}=require('../electron/memos.cjs'),{summary,lightResult}=require('../shared/library-summary.cjs');
async function profile(t){await fs.mkdir('test-results',{recursive:true});const root=await fs.mkdtemp(path.resolve('test-results/library-2.7-'));t.after(async()=>{await fs.rm(root,{recursive:true,force:true});});const store=new Library(path.join(root,'library'));await store.ready;return {root,store,actions:new LibraryActions(store)};}
async function memo(store,folder=''){return (await new Memos(store).create(folder)).note;}
test('summary repeated at all response boundaries retains original segment count and bounded preview',()=>{
 const full={id:'record',segments:Array.from({length:24},(_,i)=>({start:i,end:i+1,text:'가'.repeat(700)}))};let note=summary(full);
 for(let i=0;i<10;i++)note=lightResult({folders:[],notes:[note]}).notes[0];assert.equal(note.segmentCount,24);assert.equal(note.segments.length,8);assert.equal(note.segments[0].text.length,500);assert.equal(full.segments[0].text.length,700);
 for(const segmentCount of [NaN,-1,2,'24'])assert.equal(summary({...note,segmentCount}).segmentCount,8);
});
test('file taxonomy distinguishes drawing, PDF, memo, script, original audio and mixed selection without double counting',async()=>{
 const {fileType,selectionDescription}=await import('../shared/file-type.js');const items=[{id:'folder:하위',title:'하위'},{id:'memo',kind:'memo'},{id:'draw',kind:'pdf',documentType:'drawing'},{id:'pdf',kind:'pdf'},{id:'script',audioMissing:true},{id:'audio',kind:'audio'},{id:'combined',done:true,segments:[{text:'script'}]}];
 assert.deepEqual(items.map(item=>fileType(item).label),['폴더','메모','그리기','PDF','스크립트','녹음 원본','녹음']);assert.equal(selectionDescription(items).label,'7개 항목');assert.match(selectionDescription(items).detail,/그리기 1/);assert.equal(selectionDescription([items[3],items[3]]).label,'PDF 2개');assert.equal(selectionDescription([items[0]]).label,'하위 · 폴더');
});
test('empty and nested folders restore durably from metadata after damaged indexes with original member IDs',async t=>{
 const {root,store}=await profile(t);await store.createFolder('자료');await store.createFolder({name:'빈 폴더',parent:'자료'});await store.createFolder({name:'본문',parent:'자료'});const note=await memo(store,'자료/본문');await store.deleteFolder('자료');const group=store.data.notes.find(n=>n.kind==='folder');assert.equal(group.folderPaths.length,3);
 await fs.writeFile(store.index,'damaged');await fs.writeFile(store.index+'.backup','damaged');const recovered=new Library(store.root);await recovered.ready;assert.equal(recovered.data.notes.find(n=>n.id===group.id).kind,'folder');const result=await recovered.restoreTrash([group.id]);assert.ok(result.folders.includes('자료/빈 폴더'));assert.equal(result.notes.find(n=>n.id===note.id).folder,'자료/본문');assert.ok(!result.notes.some(n=>n.id===group.id));await assert.rejects(fs.access(path.join(recovered.recordings,group.id)));
 const restarted=new Library(recovered.root);await restarted.ready;assert.equal((await restarted.detail(note.id)).deleted,false);assert.equal(restarted.data.notes.filter(n=>n.kind==='folder').length,0);
});
test('collision restoration selects a new root; partial then full restore after restart reuses its identity',async t=>{
 const {store}=await profile(t);await store.createFolder('회의');for(const name of ['A','B','빈'])await store.createFolder({name,parent:'회의'});const a=await memo(store,'회의/A'),b=await memo(store,'회의/B');await store.deleteFolder('회의');const group=store.data.notes.find(n=>n.kind==='folder');await store.createFolder('회의');const keep=await memo(store,'회의');await store.restoreTrash([a.id]);assert.equal((await store.detail(a.id)).folder,'회의 (복구)/A');assert.equal(store.data.folders.includes('회의 (복구)/빈'),false);
 const restarted=new Library(store.root);await restarted.ready;await restarted.restoreTrash([group.id]);assert.equal((await restarted.detail(b.id)).folder,'회의 (복구)/B');assert.ok(restarted.data.folders.includes('회의 (복구)/빈'));assert.equal((await restarted.detail(keep.id)).folder,'회의');assert.equal((await restarted.detail(keep.id)).deleted,false);assert.equal(restarted.data.folders.some(f=>f.startsWith('회의 (복구 2)')),false);
});
test('a deleted and recreated partial restore root is a different folder; other group members are not deleted',async t=>{
 const {store}=await profile(t);await store.createFolder('자료');await store.createFolder({name:'하위',parent:'자료'});const a=await memo(store,'자료'),b=await memo(store,'자료/하위');await store.deleteFolder('자료');const old=store.data.notes.find(n=>n.kind==='folder');await store.restoreTrash([a.id]);const oldIdentity=store.data.folderIds['자료'];await store.deleteFolder('자료');const other=store.data.notes.find(n=>n.kind==='folder'&&n.id!==old.id);await store.createFolder('자료');assert.notEqual(store.data.folderIds['자료'],oldIdentity);const keep=await memo(store,'자료');await store.restoreTrash([old.id]);assert.equal((await store.detail(b.id)).folder,'자료 (복구)/하위');assert.equal((await store.detail(keep.id)).deleted,false);assert.equal((await store.detail(a.id)).deleted,true);await store.deleteTrash([other.id]);await assert.rejects(store.detail(a.id));assert.equal((await store.detail(b.id)).deleted,false);assert.equal((await store.detail(keep.id)).deleted,false);
});
test('permanent folder deletion preserves partially restored members and unrelated trash',async t=>{
 const {store}=await profile(t);await store.createFolder('묶음');const a=await memo(store,'묶음'),b=await memo(store,'묶음'),keep=await memo(store);await store.updateNote(keep.id,{deleted:true});await store.deleteFolder('묶음');const group=store.data.notes.find(n=>n.kind==='folder');await store.restoreTrash([a.id]);await store.deleteTrash([group.id]);assert.equal((await store.detail(a.id)).deleted,false);await assert.rejects(store.detail(b.id));assert.equal((await store.detail(keep.id)).deleted,true);const restarted=new Library(store.root);await restarted.ready;assert.ok(!restarted.data.notes.some(n=>n.id===group.id||n.id===b.id));
});
test('folder restore combined with detached original audio is one durable transaction and preserves the script',async t=>{
 const {root,store}=await profile(t);await store.createFolder('녹음');const source=path.join(root,'source.wav');await fs.writeFile(source,'original audio');const note=(await store.importAudio(source,'녹음')).note;await store.completeTranscription(note.id,{seconds:2,segments:[{start:0,end:1,text:'preserved script'}]});await store.detachAudio(note.id);const audio=store.data.notes.find(n=>n.kind==='audio');await store.deleteFolder('녹음');const group=store.data.notes.find(n=>n.kind==='folder');await store.restoreTrash([group.id,audio.id]);const restored=await store.detail(note.id);assert.equal(restored.folder,'녹음');assert.equal(restored.audioMissing,false);assert.equal(restored.segments[0].text,'preserved script');assert.equal(await fs.readFile((await store.getAudio(note.id)).filename,'utf8'),'original audio');const restarted=new Library(store.root);await restarted.ready;assert.equal((await restarted.detail(note.id)).deleted,false);assert.ok(!restarted.data.notes.some(n=>n.id===group.id||n.id===audio.id));
});
test('folder trash undo and redo do not resurrect tombstones; interrupted commit replays all metadata',async t=>{
 const {store,actions}=await profile(t);await store.createFolder('그룹');const note=await memo(store,'그룹');await actions.run({action:'trash',ids:[],folders:['그룹']});const group=store.data.notes.find(n=>n.kind==='folder');await actions.run({action:'undo'});assert.equal(store.data.notes.some(n=>n.kind==='folder'),false);await assert.rejects(fs.access(path.join(store.recordings,group.id)));await actions.run({action:'redo'});assert.equal(store.data.notes.find(n=>n.kind==='folder').id,group.id);await actions.run({action:'undo'});
 const commit=store.commitFolderRename.bind(store);store.commitFolderRename=async()=>{throw Error('simulated commit interruption');};await assert.rejects(actions.run({action:'trash',ids:[],folders:['그룹']}),/interruption/);store.commitFolderRename=commit;const restarted=new Library(store.root);await restarted.ready;assert.equal((await restarted.detail(note.id)).deleted,true);const recoveredGroup=restarted.data.notes.find(n=>n.kind==='folder');await restarted.restoreTrash([recoveredGroup.id]);assert.equal((await restarted.detail(note.id)).folder,'그룹');
});
test('partially restored folder rename retains pending group destination and alias-safe path metadata',async t=>{
 const {store}=await profile(t);await store.createFolder('__proto__');await store.createFolder({name:'하위',parent:'__proto__'});const a=await memo(store,'__proto__'),b=await memo(store,'__proto__/하위');await store.deleteFolder('__proto__');const group=store.data.notes.find(n=>n.kind==='folder');await store.restoreTrash([a.id]);await store.renameFolder({folder:'__proto__',name:'변경'});await store.restoreTrash([group.id]);assert.equal((await store.detail(a.id)).folder,'변경');assert.equal((await store.detail(b.id)).folder,'변경/하위');assert.ok(!store.data.folders.includes('__proto__'));assert.equal(Object.getPrototypeOf(store.data.folderIds),Object.prototype);
});
test('moving a partial restore root moves its identity and pending group destination, including undo and redo',async t=>{
 const {store,actions}=await profile(t);await store.createFolder('자료');await store.createFolder({name:'하위',parent:'자료'});await store.createFolder('목적지');const a=await memo(store,'자료'),b=await memo(store,'자료/하위');await store.deleteFolder('자료');const group=store.data.notes.find(n=>n.kind==='folder');await store.restoreTrash([a.id]);const identity=store.data.folderIds['자료'];await actions.run({action:'move',ids:[],folders:['자료'],folder:'목적지'});assert.equal(store.data.folderIds['목적지/자료'],identity);assert.equal((await store.detail(group.id)).restoredRoot,'목적지/자료');await actions.run({action:'undo'});assert.equal((await store.detail(group.id)).restoredRoot,'자료');await actions.run({action:'redo'});const restarted=new Library(store.root);await restarted.ready;await restarted.restoreTrash([group.id]);assert.equal((await restarted.detail(a.id)).folder,'목적지/자료');assert.equal((await restarted.detail(b.id)).folder,'목적지/자료/하위');assert.ok(!restarted.data.folders.includes('자료'));
});
