const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { Library } = require('../electron/library.cjs');
async function fixture() {
  await fs.mkdir('test-results', { recursive: true });
  const root = await fs.mkdtemp(path.resolve('test-results/folders-'));
  const library = new Library(root); await library.ready;
  return { root, library };
}
test('existing root folders and notes migrate without moving audio; children survive restart', async () => {
  const { root, library } = await fixture();
  await library.createFolder('회의'); await library.createFolder('강의');
  const file = path.join(root, 'source.wav'); await fs.writeFile(file, 'original audio');
  const { note } = await library.importAudio(file, '회의');
  const old = JSON.parse(await fs.readFile(library.index)); delete old.folderParents;
  await fs.writeFile(library.index, JSON.stringify(old));
  const migrated = new Library(root); await migrated.ready;
  assert.equal((await migrated.list()).notes[0].folder, '회의');
  await migrated.createFolder({ name: '2026', parent: '회의' });
  await migrated.createFolder({ name: '2026', parent: '강의' });
  await migrated.createFolder({ name: '10월', parent: '회의/2026' });
  await migrated.updateNote(note.id, { folder: '회의/2026/10월' });
  await assert.rejects(migrated.createFolder({ name: '2026', parent: '회의' }), /이미/);
  await migrated.setTranscription(note.id, { status: 'queued' });
  const restarted = new Library(root); await restarted.ready;
  const saved = await restarted.list();
  assert.equal(saved.folderParents['회의/2026/10월'], '회의/2026');
  assert.equal(saved.notes[0].folder, '회의/2026/10월');
  assert.equal(saved.notes[0].status, 'failed', 'A terminated queue must be visibly retriable');
  assert.equal(await fs.readFile((await restarted.getAudio(note.id)).filename, 'utf8'), 'original audio');
});
test('invalid parents, ambiguous path names and hierarchy cycles cannot corrupt the library', async () => {
  const { root, library } = await fixture();
  await library.createFolder('__proto__');
  await library.createFolder({ name: '하위', parent: '__proto__' });
  assert.equal((await library.list()).folderParents['__proto__/하위'], '__proto__');
  await assert.rejects(library.createFolder({ name: '하위', parent: '없는 폴더' }), /다시 선택/);
  for (const name of ['../outside', '하위/폴더', '하위\\폴더', '..']) await assert.rejects(library.createFolder(name), /폴더 이름/);
  await library.createFolder('A'); await library.createFolder('B');
  const data = await library.list(); data.folderParents = { A: 'B', B: 'A' };
  await fs.writeFile(library.index, JSON.stringify(data));
  const restored = new Library(root); const recovered = await restored.list();
  assert.equal(recovered.recovery.backup, true);
  assert.notDeepEqual(recovered.folderParents, { A: 'B', B: 'A' });
  assert.equal(JSON.parse(await fs.readFile(recovered.recovery.archive, 'utf8')).folderParents.A, 'B');
});
test('renaming a folder updates descendants, recordings, trash and active sessions without moving audio', async () => {
  const { root, library } = await fixture();
  await library.createFolder('강의'); await library.createFolder('다른 강의');
  await library.createFolder({ name: '10월', parent: '강의' });
  await library.createFolder({ name: '요약', parent: '강의/10월' });
  const file = path.join(root, 'sample.wav'); await fs.writeFile(file, 'original');
  const { note } = await library.importAudio(file, '강의/10월/요약');
  await library.updateNote(note.id, { deleted: true });
  const audio = (await library.getAudio(note.id)).filename;
  const active = await library.beginRecording({ title: '녹음 중', folder: '강의/10월', mime: 'audio/webm' });
  await library.appendRecording({ id: active.id, sequence: 0, bytes: new Uint8Array([1, 2, 3]) });
  await assert.rejects(library.renameFolder({ folder: '강의', name: '다른 강의' }), /이미/);
  await assert.rejects(library.renameFolder({ folder: '강의', name: '../escape' }), /폴더 이름/);
  const result = await library.renameFolder({ folder: '강의', name: '알고리즘' });
  assert.equal(result.renamed['강의/10월/요약'], '알고리즘/10월/요약');
  assert.equal(result.library.notes[0].folder, '알고리즘/10월/요약');
  assert.equal(result.library.notes[0].deleted, true);
  assert.equal((await library.finishRecording({ id: active.id, seconds: 1 })).note.folder, '알고리즘/10월');
  const restarted = new Library(root); await restarted.ready;
  assert.equal((await restarted.list()).folderParents['알고리즘/10월/요약'], '알고리즘/10월');
  assert.equal((await restarted.getAudio(note.id)).filename, audio);
  assert.equal(await fs.readFile(audio, 'utf8'), 'original');
});
test('interrupted folder rename recovers atomically before later changes can overwrite it', async () => {
  const { root, library } = await fixture();
  await library.createFolder('이전');
  const source = path.join(root, 'sample.wav'); await fs.writeFile(source, 'original');
  const { note } = await library.importAudio(source, '이전');
  const collision = path.join(library.recordings, note.id, 'note.json.tmp'); await fs.mkdir(collision);
  await assert.rejects(library.renameFolder({ folder: '이전', name: '변경' }));
  await assert.rejects(library.updateNote(note.id, { title: '다른 변경' }), /다시 실행/);
  await fs.rmdir(collision);
  const recovered = new Library(root); await recovered.ready;
  const data = await recovered.list();
  assert.deepEqual(data.folders, ['변경']); assert.equal(data.notes[0].folder, '변경');
  await assert.rejects(fs.access(path.join(root, 'folder-rename.json')), /ENOENT/);
  assert.equal(await fs.readFile((await recovered.getAudio(note.id)).filename, 'utf8'), 'original');
});
