// Investigation only: runtime instrumentation and writes are confined to a private profile.
import {_electron as electron,chromium} from 'playwright';
import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url),{Library}=require('../electron/library.cjs'),{Memos}=require('../electron/memos.cjs'),{PDFs}=require('../electron/pdfs.cjs');
const out=path.resolve('test-results/implementation-2.4.0'),profile=await fs.mkdtemp(path.join(out,'sample-')),root=path.join(profile,'LOXT');await fs.mkdir(root);await fs.writeFile(path.join(profile,'library-location.json'),JSON.stringify({version:1,root}));
const work=new Library(path.join(root,'work-library'));await work.ready;await work.createFolder('측정');const memo=(await new Memos(work).create('측정')).note;await work.updateNote(memo.id,{title:'측정 메모'});const pdf=(await new PDFs(work).create('측정')).note;await work.updateNote(pdf.id,{title:'측정 그림'});await work.flushIndex();
let app,browser;const results={profile,network:'same-PC 127.0.0.1 HTTPS',physicalDevices:false,actualWiFi:false,cases:[],errors:[]};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
try{
 const exe=path.resolve(process.argv[2]||'release/stage5/win-unpacked/LOXT.exe');app=await electron.launch({executablePath:exe,args:[],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,SORINOTE_TEST:'1',SORINOTE_TEST_DATA:profile}});let pc=await app.firstWindow();for(let i=0;i<80&&!pc.url().endsWith('index.html');i++){await pause(100);pc=app.windows().find(p=>p.url().endsWith('index.html'))||pc;}await pc.getByRole('heading',{name:'홈',exact:true}).waitFor();results.version=(await pc.evaluate(()=>window.desktop.getAppInfo())).version;
 await app.evaluate(({app,ipcMain,BrowserWindow})=>{
  const req=process.getBuiltinModule('module').createRequire(app.getAppPath()+'/package.json'),{Library}=req('./electron/library.cjs'),{DeviceServer}=req('./electron/device-server.cjs');globalThis.audit={rpc:[],ipc:[],events:[],documents:[]};globalThis.auditStores=new Map();
  const enq=Library.prototype.enqueue;Library.prototype.enqueue=function(fn){auditStores.set(this.root,this);return enq.call(this,fn);};
  const doc=Library.prototype.document;Library.prototype.document=function(id,fn){const submitted=Date.now();return doc.call(this,id,async()=>{const start=Date.now();try{return await fn();}finally{audit.documents.push({id,submitted,start,end:Date.now()});}});};
  const event=DeviceServer.prototype.event;DeviceServer.prototype.event=function(type,value){audit.events.push({type,value,time:Date.now()});return event.call(this,type,value);};
  const serve=DeviceServer.prototype.serve;DeviceServer.prototype.serve=function(...args){if(!this.auditWrapped){this.auditWrapped=true;const rpc=this.rpc;this.rpc=async(method,payload,context)=>{const start=Date.now();try{const value=await rpc(method,payload,context);audit.rpc.push({method,id:payload?.id,start,end:Date.now(),resultBytes:Buffer.byteLength(JSON.stringify(value)||'null')});return value;}catch(e){audit.rpc.push({method,start,end:Date.now(),error:e.message});throw e;}};}return serve.apply(this,args);};
  for(const name of ['library:list','workspace:library','memos:get','memos:save','pdf:get','pdf:save']){const handle=ipcMain._invokeHandlers.get(name);if(handle){ipcMain.removeHandler(name);ipcMain.handle(name,async(...args)=>{const start=Date.now();try{return await handle(...args);}finally{audit.ipc.push({name,start,end:Date.now()});}});}}
  const win=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html'));win.setSize(1300,900);win.show();win.focus();
 });
 const scope=p=>p.locator('[data-workspace=work]');async function open(p,title){const s=scope(p);if(p!==pc){const back=s.getByRole('button',{name:'보관함으로 돌아가기'});if(await back.isVisible())await back.click();else if(await s.locator('.back-link').first().isVisible())await s.locator('.back-link').first().click();}await s.getByRole('button',{name:p===pc?'내 보관함':'보관함',exact:true}).click();await s.locator('.folder-card').filter({hasText:'측정'}).click();await s.getByRole('button',{name:title+' 열기',exact:true}).click();if(title.includes('메모'))await s.locator('.bn-editor').waitFor();else await p.waitForFunction(()=>document.querySelector('.pdf-sheet canvas')?.dataset.rendered==='true');}
 const state=await pc.evaluate(()=>window.desktop.devices.configure(true));browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:820,height:1180},hasTouch:true,isMobile:true});const web=await ctx.newPage();
 await web.addInitScript(()=>{window.auditFetch=[];const fetch=window.fetch;window.fetch=async(...args)=>{let b;try{b=JSON.parse(args[1]?.body||'{}');}catch{}const start=Date.now();const response=await fetch(...args);if(b?.method)window.auditFetch.push({method:b.method,start,end:Date.now(),status:response.status});return response;};});
 await web.goto(`https://127.0.0.1:${new URL(state.pairURL).port}/web.html#pair=`+state.pairURL.split('#pair=')[1]);await web.getByText('PC에서 이 기기의 연결을 승인해 주세요.',{exact:true}).waitFor();await pc.evaluate(async()=>{const s=await window.desktop.devices.get();await window.desktop.devices.approve(s.pending[0].id,true);});await web.getByRole('heading',{name:'홈',exact:true}).waitFor();for(const p of [pc,web]){p.on('pageerror',e=>results.errors.push(e.stack));await p.evaluate(()=>{window.auditDOM={};window.auditExpected=[];window.desktop.onLibraryChange(e=>{window.auditLibrary||=[];window.auditLibrary.push({event:e,time:Date.now()});});new MutationObserver(()=>{const el=document.querySelector('[data-workspace=work]');for(const key of window.auditExpected){const text=el?.innerText||'';if(text.includes(key)&&!window.auditDOM[key])window.auditDOM[key]=Date.now();}}).observe(document.body,{subtree:true,childList:true,characterData:true});});}
 await open(pc,'측정 메모');await open(web,'측정 메모');await pause(1200);
 async function reset(){await app.evaluate(()=>{audit.rpc=[];audit.ipc=[];audit.events=[];audit.documents=[];});await web.evaluate(()=>{auditFetch=[];auditLibrary=[];});await pc.evaluate(()=>{auditLibrary=[];});}
 async function trace(){return {...await app.evaluate(()=>audit),fetch:await web.evaluate(()=>auditFetch),pcEvents:await pc.evaluate(()=>auditLibrary),webEvents:await web.evaluate(()=>auditLibrary)};}
 async function typing(source,target,type,n){const marker=type+'-'+n+'-'+randomUUID().slice(0,6);await reset();for(const p of [source,target])await p.evaluate(marker=>{auditExpected=[marker];},marker);await scope(source).locator('.bn-editor').click();const start=Date.now();await source.keyboard.insertText(marker);await target.waitForFunction(marker=>Boolean(window.auditDOM[marker]),marker);const local=await source.evaluate(marker=>auditDOM[marker],marker),remote=await target.evaluate(marker=>auditDOM[marker],marker);await pause(550);results.cases.push({type,n,start,localVisibleMs:local-start,remoteVisibleMs:remote-start,trace:await trace()});console.log(type,n,local-start,remote-start);}
 for(let i=0;i<5;i++)await typing(web,pc,'webMemoToPC',i);for(let i=0;i<5;i++)await typing(pc,web,'pcMemoToWeb',i);
 // Direct RPC gives the no-debounce baseline for the same body.
 for(let i=0;i<5;i++){await reset();const marker='direct-'+i+'-'+randomUUID().slice(0,6);await pc.evaluate(marker=>{auditExpected=[marker];},marker);const start=Date.now();await web.evaluate(async({id,marker})=>{const d=await window.desktop.memos.get(id);const blocks=structuredClone(d.blocks);blocks.push({id:crypto.randomUUID(),type:'paragraph',props:{},content:[{type:'text',text:marker,styles:{}}],children:[]});await window.desktop.memos.save({id,blocks,revision:d.revision});},{id:memo.id,marker});await pc.waitForFunction(marker=>Boolean(window.auditDOM[marker]),marker);results.cases.push({type:'directMemoRPC',start,remoteVisibleMs:await pc.evaluate(marker=>auditDOM[marker]-Number(window.auditStart||0),marker),trace:await trace()});results.cases.at(-1).remoteVisibleMs=(await pc.evaluate(marker=>auditDOM[marker],marker))-start;await pause(550);}
 // Folder operations do not use the typing debounce.
 for(let i=0;i<5;i++){await reset();const marker='외부 폴더 '+i;await pc.evaluate(marker=>{auditExpected=[marker];},marker);const start=Date.now();await web.evaluate(name=>window.desktop.createFolder(name),marker);await pc.waitForFunction(marker=>Boolean(window.auditDOM[marker]),marker);results.cases.push({type:'webFolderToPC',start,remoteVisibleMs:(await pc.evaluate(marker=>auditDOM[marker],marker))-start,trace:await trace()});await pause(550);}
 await open(pc,'측정 그림');await open(web,'측정 그림');for(const p of [pc,web])await scope(p).getByRole('button',{name:'펜',exact:true}).click();await pause(1200);
 for(let i=0;i<5;i++){await reset();const count=await scope(pc).locator('.pdf-ink [data-object]').count(),s=await scope(web).locator('.pdf-sheet').boundingBox();await web.mouse.move(s.x+40,s.y+80+i*15);await web.mouse.down();await web.mouse.move(s.x+100,s.y+83+i*15,{steps:5});const start=Date.now();await web.mouse.up();await pc.waitForFunction(count=>document.querySelectorAll('[data-workspace=work] .pdf-ink [data-object]').length>count,count);results.cases.push({type:'webStrokeEndToPC',start,remoteVisibleMs:Date.now()-start,trace:await trace()});await pause(550);}
 await reset();const count=await scope(pc).locator('.pdf-ink [data-object]').count(),s=await scope(web).locator('.pdf-sheet').boundingBox(),longStart=Date.now();await web.mouse.move(s.x+40,s.y+190);await web.mouse.down();for(let i=0;i<20;i++){await web.mouse.move(s.x+40+i*3,s.y+190+i);await pause(100);}const during=await scope(pc).locator('.pdf-ink [data-object]').count(),previewCount=await scope(pc).locator('.pdf-remote-preview').count(),ended=Date.now();if(!previewCount)throw Error('Missing in-progress ink preview');await web.mouse.up();await pc.waitForFunction(count=>document.querySelectorAll('[data-workspace=work] .pdf-ink [data-object]').length>count,count);results.longStroke={durationBeforeUpMs:ended-longStart,before:count,during,previewCount,after:await scope(pc).locator('.pdf-ink [data-object]').count(),afterUpMs:Date.now()-ended,trace:await trace()};
 // Explicitly saturate HTTP/1 connections with five extra authenticated SSE streams.
 await web.evaluate(()=>{window.extraStreams=Array.from({length:6},()=>new EventSource('/api/events'));});await pause(700);let queuedFinished=false,queuedFinishedAt;const queueStart=Date.now(),queued=web.evaluate(()=>window.desktop.getLibrary()).then(()=>{queuedFinished=true;queuedFinishedAt=Date.now();});await pause(1000);results.connectionSaturation={blockedAfterMs:Date.now()-queueStart,finishedBeforeRelease:queuedFinished};await web.evaluate(()=>extraStreams.forEach(e=>e.close()));await queued;results.connectionSaturation.totalMs=Date.now()-queueStart;results.connectionSaturation.requestMs=queuedFinishedAt-queueStart;if(!results.connectionSaturation.finishedBeforeRelease)throw Error('WebSocket request blocked by HTTP SSE slots');
 // Return to an idle document before the controlled transport experiment.
 await open(pc,'측정 메모');await open(web,'측정 메모');await pause(700);
 // Delay only transport of a read RPC to model a slow network, clearly separated from real observations.
 await web.evaluate(()=>{window.originalSocketSend=WebSocket.prototype.send;WebSocket.prototype.send=function(value){let message;try{message=JSON.parse(value);}catch{}if(message?.type==='rpc'&&message.method==='library.createFolder')setTimeout(()=>originalSocketSend.call(this,value),2500);else originalSocketSend.call(this,value);};});await reset();const delayName='지연 재현 폴더';await pc.evaluate(marker=>{auditExpected=[marker];},delayName);const delayStart=Date.now();await web.evaluate(name=>window.desktop.createFolder(name),delayName);await pc.waitForFunction(marker=>Boolean(auditDOM[marker]),delayName);results.injectedTransport={injectedBeforeRequestMs:2500,visibleMs:(await pc.evaluate(marker=>auditDOM[marker],delayName))-delayStart,trace:await trace()};await web.evaluate(()=>{WebSocket.prototype.send=originalSocketSend;});
 const extraTabs=[];for(let i=0;i<6;i++){const tab=await ctx.newPage();await tab.goto(`https://127.0.0.1:${new URL(state.pairURL).port}/web.html`);await tab.getByRole('heading',{name:'홈',exact:true}).waitFor();extraTabs.push(tab);}const manyStart=Date.now();await web.evaluate(()=>window.desktop.createFolder('다중 탭 검증'));results.multipleTabs={tabs:7,writeAckMs:Date.now()-manyStart,diagnostics:await pc.evaluate(()=>window.desktop.devices.diagnostics())};for(const tab of extraTabs)await tab.close();
 results.webDiagnostics=await web.evaluate(()=>window.desktop.syncDiagnostics());
 results.complete=true;
}catch(error){results.failure=error.stack;process.exitCode=1;console.error(error.stack);}finally{await browser?.close();if(app)await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await fs.writeFile(path.join(out,'results-'+(results.version||'failed')+'.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({version:results.version,complete:results.complete,failure:results.failure,cases:results.cases.map(c=>({type:c.type,local:c.localVisibleMs,remote:c.remoteVisibleMs})),longStroke:results.longStroke,connectionSaturation:results.connectionSaturation,injectedTransport:results.injectedTransport,errors:results.errors},null,2));}
