const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{randomUUID}=require('node:crypto');
const {Library}=require('../electron/library.cjs'),{Memos}=require('../electron/memos.cjs'),{PDFs}=require('../electron/pdfs.cjs'),{PDFDocument}=require('pdf-lib'),{RequestCache}=require('../electron/request-cache.cjs');
const blocks=text=>[{id:randomUUID(),type:'paragraph',content:[{type:'text',text,styles:{}}],children:[]}];
async function setup(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'loxt-sync-'));const library=new Library(root);await library.ready;t.after(async()=>{await library.flushIndex();await fs.rm(root,{recursive:true,force:true});});return library;}
test('summary index is compact; full scripts and metadata survive restart; reads do not wait for writes',async t=>{
 const l=await setup(t),{id}=await l.beginRecording({title:'예시',mime:'audio/webm'});await l.appendRecording({id,sequence:0,bytes:new Uint8Array([1,2,3])});await l.finishRecording({id,seconds:200});const segments=Array.from({length:1000},(_,i)=>({start:i/10,end:(i+1)/10,text:'긴 스크립트 '.repeat(20)}));await l.completeTranscription(id,{seconds:200,segments});
 assert.equal((await l.detail(id)).segments.length,1000);const summary=await l.listSummary();assert.equal(summary.notes[0].segments.length,8);assert.equal(summary.notes[0].segmentCount,1000);assert.ok(JSON.stringify(summary).length<10000);
 let release;const wait=new Promise(r=>release=r);const writing=l.enqueue(()=>wait);const data=await Promise.race([l.listSummary(),new Promise((_,r)=>setTimeout(()=>r(Error('read blocked')),200))]);assert.equal(data.notes[0].id,id);release();await writing;
 const disk=JSON.parse(await fs.readFile(l.index));assert.equal(disk.notes[0].segments.length,8);const next=new Library(l.root);await next.ready;assert.equal((await next.detail(id)).segments.length,1000);assert.equal(next.revision,l.revision);
});
test('durable memo body publishes a targeted event even if metadata fails; title CAS rejects overwrite',async t=>{
 const l=await setup(t),m=new Memos(l),{note}=await m.create(),events=[];l.onChange=(revision,event)=>events.push({revision,...event});const original=l.saveNote;l.saveNote=async()=>{throw Error('index unavailable');};const saved=await m.save({id:note.id,revision:0,blocks:blocks('본문')});await l.queue;assert.match(l.indexError,/본문은 저장/);assert.equal((await m.read(note.id)).revision,1);await new Promise(r=>setImmediate(r));assert.ok(events.some(e=>e.id===note.id&&e.kind==='memo'));l.saveNote=original;
 await l.updateNote(note.id,{title:'외부 변경'});await assert.rejects(l.updateNote(note.id,{title:'오래된 이름'},{title:note.title}),e=>e.code==='CONFLICT');assert.equal((await l.detail(note.id)).title,'외부 변경');
});
test('PDF delta saves preserve unrelated objects, dots export, and stale revisions reject',async t=>{
 const l=await setup(t),p=new PDFs(l),doc=await PDFDocument.create();doc.addPage([400,600]);const {note}=await p.import(await doc.save(),'예시.pdf');const dot={id:randomUUID(),type:'pen',page:1,color:'#387a97',width:2,points:[[20,30]]};await p.save({id:note.id,revision:0,patch:{upsert:[dot],remove:[]}});const line={...dot,id:randomUUID(),points:[[30,40],[50,60]]};await p.save({id:note.id,revision:1,patch:{upsert:[line],remove:[]}});assert.equal((await p.read(note.id)).objects.length,2);await assert.rejects(p.save({id:note.id,revision:0,objects:[]}),e=>e.code==='CONFLICT');await p.save({id:note.id,revision:2,patch:{upsert:[],remove:[line.id]}});assert.deepEqual((await p.read(note.id)).objects,[dot]);assert.ok((await p.export(note.id,true)).length>500);const next=new Library(l.root);await next.ready;assert.equal((await new PDFs(next).read(note.id)).revision,3);
});
test('retry cache shares active writes; excludes reads and evicts settled large results',async()=>{
 const c=new RequestCache();let runs=0,release;const wait=new Promise(r=>release=r);const first=c.run('same','memo.save',async()=>{runs++;await wait;return {ok:true};}),retry=c.run('same','memo.save',()=>{runs++;});release();assert.deepEqual(await first,await retry);assert.equal(runs,1);await c.run('read','library.list',()=>({value:1}));assert.equal(c.entries.has('read'),false);await c.run('big','memo.save',()=>({value:'x'.repeat(9*1024*1024)}));assert.ok(c.bytes<=8*1024*1024);for(const e of c.entries.values())e.expires=0;c.prune();assert.equal(c.entries.size,0);
});
test('PDF hit testing and text occurrences support drag erase and within-page search',async()=>{
 const {touchesObject,matchingItems,appendPoint}=await import('../src/pdfGeometry.js');const o={type:'pen',width:2,points:[[0,0],[100,100]]};assert.equal(touchesObject(o,[50,50],2),true);assert.equal(touchesObject(o,[50,70],2),false);const s={points:[[0,0]]};appendPoint(s,[.1,.1]);assert.equal(s.points.length,1);appendPoint(s,[2,2]);assert.equal(s.points.length,2);assert.equal(matchingItems([{str:'hello hello'},{str:'hello'}],'hello').length,3);
});
