import {_electron as electron,chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{Library}=require('../electron/library.cjs'),{PDFs}=require('../electron/pdfs.cjs'),{Memos}=require('../electron/memos.cjs'),{PDFDocument,StandardFonts}=require('pdf-lib');
const out=path.resolve('test-results/implementation-2.3.0');await fs.mkdir(out,{recursive:true});const profile=await fs.mkdtemp(path.join(out,'ui-profile-')),root=path.join(profile,'LOXT');await fs.mkdir(root);await fs.writeFile(path.join(profile,'library-location.json'),JSON.stringify({version:1,root}));
const work=new Library(path.join(root,'work-library')),live=new Library(path.join(root,'live-library'));await Promise.all([work.ready,live.ready]);await work.createFolder('테스트');const memo=(await new Memos(work).create('테스트')).note;await work.updateNote(memo.id,{title:'예시 메모'});
const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica);for(let i=0;i<4;i++){const p=doc.addPage([595,842]);p.drawText('LOXT search sample: sample text',{x:50,y:740,font,size:18});}const pdf=(await new PDFs(work).import(await doc.save(),'PDF 예시.pdf','테스트')).note;
const results={version:'2.3.0',profile,physicalDevices:false,gpuInference:false,errors:[],screens:[],sync:[]};let app,browser;
try{
 const exe=process.argv.slice(2).find(v=>v.endsWith('.exe'));app=await electron.launch({...(exe?{executablePath:path.resolve(exe)}:{}),args:exe?[]:['.'],env:{...process.env,ELECTRON_RUN_AS_NODE:undefined,SORINOTE_TEST:'1',SORINOTE_TEST_DATA:profile}});let pc=await app.firstWindow();for(let i=0;i<60&&!pc.url().endsWith('index.html');i++){await new Promise(r=>setTimeout(r,100));pc=app.windows().find(w=>w.url().endsWith('index.html'))||pc;}pc.on('console',message=>{if(message.type()==='error')results.errors.push(message.text());});pc.setDefaultTimeout(20000);pc.on('pageerror',e=>results.errors.push(e.stack));await pc.getByRole('heading',{name:'홈',exact:true}).waitFor();await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(1440,960);w.show();w.focus();});
 const scope=pc.locator('[data-workspace=work]');async function waitObjects(count){for(let i=0;i<150;i++){const value=await pc.evaluate(id=>window.desktop.pdf.get({workspace:'work',id}),pdf.id);if(value.objects.length===count)return value;await pc.waitForTimeout(50);}throw Error('PDF 저장 개수 '+count+' 도달 실패');}async function open(p,title){const main=p.locator('[data-workspace=work]');if(p!==pc&&await main.locator('[aria-label="보관함으로 돌아가기"]').isVisible())await main.locator('[aria-label="보관함으로 돌아가기"]').click();await main.getByRole('button',{name:p===pc?'내 보관함':'보관함',exact:true}).click();await main.locator('.folder-card').filter({hasText:'테스트'}).click();await main.getByRole('button',{name:title+' 열기',exact:true}).click();}
 await open(pc,'PDF 예시');await pc.waitForFunction(()=>document.querySelector('.pdf-sheet canvas')?.dataset.rendered==='true');
 const before=await scope.locator('.pdf-sheet').boundingBox();await scope.getByRole('button',{name:'PDF 확대',exact:true}).click();await pc.waitForFunction(w=>document.querySelector('.pdf-sheet').getBoundingClientRect().width>w,before.width);results.pdfOnlyZoom=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getZoomFactor());assert.equal(results.pdfOnlyZoom,1);
 await scope.getByRole('button',{name:'PDF 맞춤',exact:true}).click();await pc.getByRole('menuitemradio',{name:'너비 맞춤',exact:false}).click();await pc.waitForTimeout(400);
 await scope.getByRole('button',{name:'펜',exact:true}).click();let sheet=await scope.locator('.pdf-sheet').boundingBox();await pc.mouse.click(sheet.x+80,sheet.y+160);await waitObjects(1);assert.equal((await pc.evaluate(id=>window.desktop.pdf.get({workspace:'work',id}),pdf.id)).objects[0].points.length,1);results.dot=true;
 await pc.mouse.move(sheet.x+100,sheet.y+200);await pc.mouse.down();await pc.mouse.move(sheet.x+220,sheet.y+200,{steps:10});await pc.mouse.up();await waitObjects(2);
 await scope.getByRole('button',{name:'지우개',exact:true}).click();await pc.mouse.move(sheet.x+160,sheet.y+170);await pc.mouse.down();await pc.mouse.move(sheet.x+160,sheet.y+240,{steps:15});await pc.mouse.up();await waitObjects(1);results.dragErase=true;
 await scope.getByRole('button',{name:'실행 취소',exact:true}).click();await waitObjects(2);results.eraseUndo=true;
 await scope.locator('.pdf-workspace').focus();await pc.keyboard.press('t');assert.equal(await scope.getByRole('button',{name:'텍스트',exact:true}).getAttribute('aria-pressed'),'true');await pc.mouse.click(sheet.x+90,sheet.y+260);await scope.getByRole('textbox',{name:'PDF 텍스트 입력'}).fill('한글 필기');await scope.getByRole('textbox',{name:'PDF 텍스트 입력'}).press('Tab');await waitObjects(3);results.text=true;await scope.locator('.pdf-workspace').focus();await pc.keyboard.press('t');await pc.mouse.click(sheet.x+95,sheet.y+290);await scope.getByRole('textbox',{name:'PDF 텍스트 입력'}).fill('취소할 텍스트');await scope.getByRole('textbox',{name:'PDF 텍스트 입력'}).press('Escape');assert.equal(await scope.getByRole('textbox',{name:'PDF 텍스트 입력'}).count(),0);await pc.waitForTimeout(300);assert.equal((await pc.evaluate(id=>window.desktop.pdf.get({workspace:'work',id}),pdf.id)).objects.length,3);results.textCancel=true;
 await scope.getByRole('button',{name:'PDF 검색 열기',exact:true}).click();await scope.getByRole('textbox',{name:'PDF 검색',exact:true}).fill('sample');await scope.locator('.pdf-search-bar').getByRole('button',{name:'찾기',exact:true}).click();await pc.waitForFunction(()=>document.querySelector('.pdf-search-bar')?.textContent.includes('1 / 8'));assert.equal(await scope.locator('.pdf-search-marks mark').count(),1);results.searchOccurrences=8;await scope.getByRole('button',{name:'다음 PDF 검색 결과'}).click();assert.ok(await scope.locator('.pdf-search-bar').innerText().then(t=>t.includes('2 / 8')));await scope.getByRole('button',{name:'PDF 검색 닫기'}).click();
 const state=await pc.evaluate(()=>window.desktop.devices.configure(true));browser=await chromium.launch({channel:'msedge',headless:true});const ctx=await browser.newContext({ignoreHTTPSErrors:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true});const web=await ctx.newPage();web.on('pageerror',e=>results.errors.push(e.stack));await web.goto(`https://127.0.0.1:${new URL(state.pairURL).port}/web.html#pair=`+state.pairURL.split('#pair=')[1]);await web.getByText('PC에서 이 기기의 연결을 승인해 주세요.',{exact:true}).waitFor();await pc.evaluate(async()=>{const s=await window.desktop.devices.get();await window.desktop.devices.approve(s.pending[0].id,true);});await web.getByRole('heading',{name:'홈',exact:true}).waitFor();await open(web,'PDF 예시');await web.waitForFunction(()=>document.querySelector('.pdf-sheet canvas')?.dataset.rendered==='true');
 await web.evaluate(id=>window.desktop.updateNote(id,{title:'외부 변경 PDF'}),pdf.id);await pc.waitForFunction(()=>document.querySelector('[aria-label="PDF 제목"]')?.value==='외부 변경 PDF');await scope.getByLabel('PDF 제목',{exact:true}).focus();await scope.getByRole('button',{name:'페이지 미리보기',exact:true}).click();assert.equal((await pc.evaluate(id=>window.desktop.getNote(id),pdf.id)).title,'외부 변경 PDF');results.titleFollowAndBlur=true;
 await web.getByRole('button',{name:'펜',exact:true}).click();sheet=await web.locator('.pdf-sheet').boundingBox();const start=Date.now(),counts=[];for(let i=0;i<12;i++){await web.mouse.move(sheet.x+30,sheet.y+80+i*9);await web.mouse.down();await web.mouse.move(sheet.x+80,sheet.y+83+i*9,{steps:3});await web.mouse.up();await web.waitForTimeout(100);counts.push(await scope.locator('.pdf-ink [data-object]').count());}await pc.waitForFunction(()=>document.querySelectorAll('[data-workspace=work] .pdf-ink [data-object]').length>=15);results.continuousInk={durationMs:Date.now()-start,counts};assert.ok(counts.slice(0,-1).some(n=>n>3));
 const scrollBox=await web.locator('.pdf-scroll').boundingBox(),factorBefore=await web.evaluate(()=>visualViewport.scale),widthBefore=(await web.locator('.pdf-sheet').boundingBox()).width;const cdp=await ctx.newCDPSession(web),x=scrollBox.x+scrollBox.width/2,y=scrollBox.y+120;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-35,y,id:1},{x:x+35,y,id:2}]});for(let d=40;d<=60;d+=5){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-d,y,id:1},{x:x+d,y,id:2}]});await web.waitForTimeout(30);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await web.waitForTimeout(400);results.pinch={before:widthBefore,after:(await web.locator('.pdf-sheet').boundingBox()).width,browserScaleBefore:factorBefore,browserScaleAfter:await web.evaluate(()=>visualViewport.scale)};assert.ok(results.pinch.after>widthBefore*1.4);assert.equal(results.pinch.browserScaleAfter,factorBefore);
 for(const width of [320,390,768]){await web.setViewportSize({width,height:width===768?1024:844});for(const theme of ['dark','light']){await web.evaluate(theme=>window.desktop.appearance.set(theme),theme);await web.waitForTimeout(250);await web.getByRole('button',{name:'PDF 맞춤',exact:true}).click();await web.getByRole('menuitemradio',{name:'너비 맞춤',exact:false}).click();await web.waitForTimeout(300);const geometry=await web.evaluate(()=>{const r=document.querySelector('.pdf-scroll'),s=document.querySelector('.pdf-sheet'),h=document.querySelector('.pdf-toolbar'),f=document.querySelector('.pdf-footer');return {scroll:r.clientWidth,sheet:s.getBoundingClientRect().width,toolbar:h.getBoundingClientRect().height,footer:f.getBoundingClientRect().height,pageOverflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(geometry.sheet<=geometry.scroll);assert.equal(geometry.pageOverflow,false);assert.ok(geometry.toolbar<65);assert.ok(geometry.footer<65);const file=`pdf-${width}-${theme}.png`;await web.screenshot({path:path.join(out,file)});results.screens.push({width,theme,...geometry,file});}}
 await web.setViewportSize({width:390,height:844});await web.getByRole('button',{name:'너비 맞춤'}).count().catch(()=>{});await web.getByLabel('PDF 제목',{exact:true}).fill('아주 긴 PDF 제목 반응형 검증 '.repeat(5));await web.getByLabel('PDF 제목',{exact:true}).press('Tab');await web.waitForTimeout(250);assert.ok((await web.locator('.document-toolbar').boundingBox()).height<120);results.longTitle=true;
 await open(pc,'예시 메모');await scope.locator('.bn-editor').waitFor();await open(web,'예시 메모');await web.locator('.bn-editor').waitFor();for(let i=0;i<3;i++){const marker='remote-change-'+i;await web.locator('.bn-editor').click();const start=Date.now();await web.keyboard.insertText(marker);await pc.waitForFunction(marker=>document.querySelector('[data-workspace=work] .bn-editor')?.innerText.includes(marker),marker);results.sync.push(Date.now()-start);}await web.evaluate(id=>window.desktop.updateNote(id,{title:'외부 변경 메모'}),memo.id);await pc.waitForFunction(()=>document.querySelector('[aria-label="메모 제목 변경"]')?.value==='외부 변경 메모');results.memoTitle=true;let resyncRequests=0;web.on('request',r=>{if(r.url().endsWith('/api/rpc')){try{if(JSON.parse(r.postData()||'{}').method==='liveState')resyncRequests++;}catch{}}});await web.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));for(let i=0;i<30&&!resyncRequests;i++)await web.waitForTimeout(50);assert.ok(resyncRequests>0);results.foregroundResync=true;
 const recording=await web.evaluate(()=>window.desktop.beginRecording({title:'조각 저장 검증',mime:'audio/webm',folder:''}));results.chunks=[];for(let sequence=0;sequence<4;sequence++){const start=Date.now();await web.evaluate(({id,sequence})=>window.desktop.appendRecording({id,sequence,bytes:new Uint8Array(1024*1024).fill(sequence+1)}),{id:recording.id,sequence});await web.evaluate(id=>window.desktop.checkpointRecording({id,seconds:3}),recording.id);results.chunks.push(Date.now()-start);}await web.reload();await web.waitForFunction(()=>Boolean(window.desktop?.recordingDrafts));const recovered=await web.evaluate(async id=>{const doc=(await window.desktop.recordingDrafts.list()).find(d=>d.id===id);return {count:doc.chunks.length,bytes:doc.bytes,starts:doc.chunks.map(c=>new Uint8Array(c)[0])};},recording.id);assert.deepEqual(recovered,{count:4,bytes:4194304,starts:[1,2,3,4]});await web.evaluate(id=>window.desktop.discardRecording(id),recording.id);results.chunkOrder=true;
 await browser.close();browser=null;
 const current=await pc.evaluate(id=>window.desktop.getNote(id),pdf.id);await open(pc,current.title);await pc.waitForFunction(()=>document.querySelector('.pdf-sheet canvas')?.dataset.rendered==='true');await scope.getByRole('button',{name:'펜',exact:true}).click();const endSheet=await scope.locator('.pdf-sheet').boundingBox();const previous=(await pc.evaluate(id=>window.desktop.pdf.get({workspace:'work',id}),pdf.id)).objects.length;await pc.mouse.click(endSheet.x+55,endSheet.y+110);const child=app.process(),closed=new Promise(resolve=>child.once('exit',resolve)),closeStart=Date.now();await app.evaluate(({BrowserWindow})=>{setTimeout(()=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('index.html')).close(),10);});await Promise.race([closed,new Promise((_,reject)=>setTimeout(()=>reject(Error('Normal close timed out')),8000))]);results.normalCloseMs=Date.now()-closeStart;app=null;const stored=new PDFs(new Library(path.join(root,'work-library')));const finalPDF=await stored.read(pdf.id);assert.equal(finalPDF.objects.length,previous+1);results.closeFlushedPDF=true;
 assert.deepEqual(results.errors,[]);results.complete=true;
}catch(error){results.failure=error.stack;if(app){results.windows=app.windows().map(w=>w.url());for(const w of app.windows())await w.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});}process.exitCode=1;console.error(error.stack);}finally{await fs.writeFile(path.join(out,'ui-results.json'),JSON.stringify(results,null,2));await browser?.close();if(app)await app.evaluate(({app})=>app.exit(0)).catch(()=>{});console.log(JSON.stringify(results,null,2));}

