import {_electron as electron,chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url),{Library}=require('../electron/library.cjs'),{Memos}=require('../electron/memos.cjs'),{PDFs}=require('../electron/pdfs.cjs');
const out=path.resolve('test-results/ux-2.9.0');await fs.mkdir(out,{recursive:true});const profile=await fs.mkdtemp(path.join(out,'profile-')),library=new Library(path.join(profile,'library'));await library.ready;
const text=v=>[{type:'text',text:v,styles:{}}],p=(id,v)=>({id,type:'paragraph',props:{},content:text(v),children:[]});
const {note}=await new Memos(library).create();await library.updateNote(note.id,{title:'UX 검증 메모'});const headings=[1,2,3,4].map(level=>({id:randomUUID(),type:'heading',props:{level},content:text('제목 '+level),children:[]}));await new Memos(library).save({id:note.id,revision:0,blocks:[...headings,p('body','예시 본문')]});const drawing=(await new PDFs(library).create()).note;
await library.flushIndex();
const env={...process.env,SORINOTE_TEST:'1',SORINOTE_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;delete env.SORINOTE_DEV;
let app,browser,page;const result={profile,example:true,microphone:false,inference:false,realSafari:false},errors=[];
try{
 app=await electron.launch({...(process.argv.includes('--source')?{args:['.']}:{executablePath:path.resolve('release/stage5/win-unpacked/LOXT.exe'),args:[]}),env});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));const work=page.locator('[data-workspace=work]');
 const resize=async(w,h=900)=>{await app.evaluate(({BrowserWindow},{w,h})=>{const b=BrowserWindow.getAllWindows()[0];b.setMinimumSize(320,500);b.setSize(w,h);b.show();},{w,h});await page.waitForTimeout(200);};await resize(1400);assert.equal((await page.evaluate(()=>window.desktop.getAppInfo())).version,'2.9.0');
 await work.getByRole('button',{name:'내 기기 연결',exact:true}).click();await page.locator('.device-settings').waitFor();assert.equal((await page.evaluate(()=>window.desktop.devices.get())).enabled,false);await work.getByRole('button',{name:'← 돌아가기',exact:true}).click();
 await work.getByRole('button',{name:'내 보관함',exact:true}).click();await work.getByRole('button',{name:'UX 검증 메모 열기',exact:true}).click();await page.locator('.bn-editor').waitFor();
 await page.evaluate(()=>{let el=document.querySelector('.bn-editor'),f=el[Object.keys(el).find(k=>k.startsWith('__reactFiber'))];while(f){if(f.memoizedProps?.editor?.document){window.e=f.memoizedProps.editor;return;}f=f.return;}throw Error('editor inaccessible');});
 assert.equal(await page.getByRole('button',{name:'편집 도구',exact:true}).count(),0);const order=await page.locator('.memo-tools').evaluate(el=>[...el.querySelectorAll('button')].map(x=>x.getAttribute('aria-label')));assert.equal(order.indexOf('메모 목차'),order.indexOf('전체화면')+1);result.toolbarOrder=order;
 await page.getByRole('button',{name:'전체화면',exact:true}).click();await page.getByRole('button',{name:'메모 목차',exact:true}).click();result.layouts=[];
 for(const theme of ['dark','light'])for(const width of [1400,1024,768,390]){await page.evaluate(v=>window.desktop.appearance.set(v),theme);await resize(width);const measured=await page.evaluate(()=>({width:innerWidth,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth,fonts:[...document.querySelectorAll('.memo-outline-title')].map(el=>getComputedStyle(el).fontSize),fullscreen:document.querySelector('.memo-editor').getBoundingClientRect().toJSON()}));assert.deepEqual(measured.fonts,['16px','14px','13px','12px']);assert.equal(measured.overflow,false);assert.equal(measured.fullscreen.x,0);result.layouts.push({theme,...measured});await page.screenshot({path:path.join(out,`memo-${theme}-${width}.png`)});}
 await resize(1400);await page.getByRole('button',{name:'목차 닫기',exact:true}).click();const reset=async blocks=>{await page.evaluate(blocks=>{const e=window.e;e.replaceBlocks(e.document,blocks);e.setTextCursorPosition(blocks[0].id,'start');e.focus();},blocks);};await reset([p('input','')]);await page.keyboard.type('```python');await page.keyboard.press('Enter');await page.keyboard.type('print("hello, world")');await page.keyboard.press('Enter');await page.keyboard.type('```');await page.keyboard.press('Enter');await page.waitForFunction(()=>window.e.document.length>=2&&window.e.getTextCursorPosition().block.type==='paragraph');assert.equal(await page.evaluate(()=>window.e.document[0].content.map(x=>x.text||'').join('').trim()),'print("hello, world")');await page.keyboard.press('Control+z');await page.waitForFunction(()=>window.e.document[0].content.map(x=>x.text||'').join('').endsWith('```'));await page.keyboard.press('Control+Shift+z');await page.waitForFunction(()=>window.e.getTextCursorPosition().block.type==='paragraph');result.fenceAndHistory=true;
 await reset([{id:'literal',type:'codeBlock',props:{language:'python'},content:text('value = "```"'),children:[]}]);await page.evaluate(()=>{e.setTextCursorPosition('literal','end');e.focus();});await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>e.document[0].content.map(x=>x.text||'').join('')),'value = "```"\n');result.literalFence=true;
 await reset([p('paste','')]);await page.evaluate(value=>{const transfer=new DataTransfer();transfer.setData('text/plain',value);e.prosemirrorView.dom.dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));},'```python\nprint("hello, world")\n```');await page.waitForFunction(()=>e.document[0].type==='codeBlock');result.pastedFence=true;
 await page.getByRole('button',{name:'코드 언어 선택',exact:true}).click();await page.getByRole('textbox',{name:'코드 언어 검색'}).fill('ROS2');assert.equal(await page.locator('.memo-code-language-results button').count(),8);await page.getByRole('button',{name:'ROS2 · Python',exact:true}).click();await page.locator('[data-content-type=codeBlock] .shiki').first().waitFor();await page.getByRole('button',{name:'코드 복사',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.memo-code-copy')?.textContent==='복사됨');assert.equal(await app.evaluate(({clipboard})=>clipboard.readText()),'print("hello, world")');await page.waitForFunction(async id=>(await window.desktop.memos.get(id)).blocks[0].props.language==='ros2-python',note.id);result.ros2SaveAndCopy=true;
 for(const lang of ['ros2-msg','ros2-cpp']){await reset([{id:lang,type:'codeBlock',props:{language:lang},content:text(lang==='ros2-msg'?'# Comment\nint32 count\n---\nstring result':'#include <rclcpp/rclcpp.hpp>\nint main() { return 0; }'),children:[]}]);await page.locator('[data-content-type=codeBlock] .shiki').first().waitFor();}result.ros2InterfaceHighlight=true;
 await page.getByRole('button',{name:'전체화면 종료',exact:true}).click();await page.getByRole('button',{name:'보관함으로 돌아가기',exact:true}).click();await work.getByRole('button',{name:' 새 그리기 열기'.trim(),exact:true}).click();await page.locator('.pdf-sheet canvas[data-rendered=true]').waitFor();await page.getByRole('button',{name:'전체화면',exact:true}).click();result.drawingLayouts=[];
 for(const theme of ['dark','light'])for(const width of [1400,1024,768,390]){await page.evaluate(v=>window.desktop.appearance.set(v),theme);await resize(width);await page.locator('.pdf-sheet canvas[data-rendered=true]').waitFor();const measured=await page.evaluate(()=>{const root=document.querySelector('.pdf-workspace'),frame=document.querySelector('.pdf-frame');return {width:innerWidth,height:innerHeight,x:root.getBoundingClientRect().x,frameRadius:getComputedStyle(frame).borderRadius,frameBorder:getComputedStyle(frame).borderWidth,padding:getComputedStyle(root).padding,overflow:document.documentElement.scrollWidth>innerWidth};});assert.equal(measured.x,0);assert.equal(measured.frameRadius,'0px');assert.equal(measured.frameBorder,'0px');assert.equal(measured.padding,'0px');assert.equal(measured.overflow,false);result.drawingLayouts.push({theme,...measured});await page.screenshot({path:path.join(out,`drawing-${theme}-${width}.png`)});}
 await resize(1400);await page.getByRole('button',{name:'펜',exact:true}).click();const box=await page.locator('.pdf-sheet').boundingBox();await page.mouse.move(box.x+100,box.y+120);await page.mouse.down();await page.mouse.move(box.x+180,box.y+140,{steps:8});await page.mouse.up();await page.waitForFunction(async id=>(await window.desktop.pdf.get({id,workspace:"work"})).objects.length>0,drawing.id);result.fullscreenInkSaved=true;
 await page.getByRole('button',{name:'전체화면 종료',exact:true}).click();await page.getByRole('button',{name:'보관함으로 돌아가기',exact:true}).click();await work.getByRole('button',{name:'설정',exact:true}).click();await page.getByRole('button',{name:'내 기기 연결',exact:true}).click();await page.evaluate(()=>window.desktop.devices.configure(true));const devices=await page.evaluate(()=>window.desktop.devices.get());result.connectionSteps=await page.locator('.device-step h3').allTextContents();assert.equal(result.connectionSteps.length,4);
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({ignoreHTTPSErrors:true,hasTouch:true,viewport:{width:390,height:844}}),web=await context.newPage();web.on('pageerror',e=>errors.push(e.message));await web.goto(devices.pairURL);await page.waitForFunction(async()=>(await window.desktop.devices.get()).pending.length===1);await page.locator('.device-pending').waitFor();await page.locator('.device-pending').getByRole('button',{name:'승인',exact:true}).click();await web.getByRole('heading',{name:'홈',exact:true}).waitFor();await page.getByRole('button',{name:/^승인한 브라우저/}).click();await page.getByText('현재 접속 중 · 승인 유효',{exact:true}).waitFor();const count=(await page.evaluate(()=>window.desktop.devices.get())).devices.length;
 await web.getByRole('button',{name:'PC 연결 관리',exact:true}).click();await web.getByRole('dialog',{name:'PC 연결 관리',exact:true}).waitFor();assert.equal(await web.getByLabel('새 연결 주소').isVisible(),false);await web.locator('details').filter({hasText:'다른 연결 주소 사용'}).getByText('다른 연결 주소 사용',{exact:true}).click();const newQR=await page.evaluate(()=>window.desktop.devices.qr());await web.getByLabel('새 연결 주소').fill(newQR.pairURL);await web.getByRole('button',{name:'이 주소로 연결 요청',exact:true}).click();await web.getByText('PC 승인이 완료되었습니다. 열린 문서와 초안을 유지합니다.',{exact:false}).waitFor();assert.equal((await page.evaluate(()=>window.desktop.devices.get())).devices.length,count);await web.getByRole('button',{name:'닫기',exact:true}).click();await web.evaluate(url=>{location.hash=new URL(url).hash;},newQR.pairURL);await web.waitForTimeout(200);assert.equal(await web.getByRole('dialog').count(),0);result.sameBrowserReapprovalAndHash=true;
 await page.getByRole('button',{name:'이름 수정',exact:true}).click();await page.getByLabel('브라우저 별명').fill('내 iPad 검증');await page.locator('.device-alias').getByRole('button',{name:'저장',exact:true}).click();await page.getByText('내 iPad 검증',{exact:true}).waitFor();await page.getByRole('button',{name:'승인 해제',exact:true}).click();await page.getByRole('dialog',{name:'브라우저 승인 해제'}).waitFor();assert.equal((await page.evaluate(()=>window.desktop.devices.get())).devices.length,count);await page.getByRole('dialog').getByRole('button',{name:'취소',exact:true}).click();result.renameAndRevokeConfirmation=true;
 for(const theme of ['dark','light'])for(const width of [1400,1024,768,390]){await page.evaluate(v=>window.desktop.appearance.set(v),theme);await resize(width);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,`devices-${theme}-${width}.png`)});}
 await web.getByRole('navigation',{name:'모바일 탐색'}).getByRole('button',{name:'보관함',exact:true}).click();await web.getByRole('button',{name:'UX 검증 메모 열기',exact:true}).click();await web.locator('.bn-editor').waitFor();assert.equal(await web.getByRole('button',{name:'실행 취소',exact:true}).isVisible(),true);assert.equal(await web.getByRole('button',{name:'다시 실행',exact:true}).isVisible(),true);await web.getByRole('button',{name:'코드 복사',exact:true}).waitFor();result.touchHistoryAndCodeCopy=true;await web.screenshot({path:path.join(out,'web-touch-memo.png')});
 await page.getByRole('button',{name:'← 돌아가기',exact:true}).click();await page.getByRole('button',{name:'워크스페이스 선택',exact:true}).click();await page.getByRole('menuitemradio',{name:/^Live/}).click();await page.locator('[data-workspace=live]').getByRole('heading',{name:'홈',exact:true}).waitFor();await page.locator('[data-workspace=live]').getByRole('button',{name:'내 기기 연결',exact:true}).click();await page.locator('.device-settings:visible').waitFor();result.workLiveSharedDeviceSettings=true;
 await page.evaluate(()=>window.desktop.devices.configure(false));result.passed=true;assert.deepEqual(errors,[]);
}catch(e){result.error=e.stack;process.exitCode=1;if(page){result.editor=await page.evaluate(()=>window.e?.document).catch(()=>null);await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});}}
finally{if(page)await page.evaluate(()=>window.desktop.devices.configure(false)).catch(()=>{});await browser?.close();if(app)await app.close().catch(()=>app.process().kill());result.pageErrors=errors;await fs.writeFile(path.join(out,'results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}
