const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),https=require('node:https');
const {PDFDocument}=require('pdf-lib'),{Library}=require('../electron/library.cjs'),{PDFs}=require('../electron/pdfs.cjs'),{DeviceServer}=require('../electron/device-server.cjs'),{Memos}=require('../electron/memos.cjs');
async function profile(){await fs.mkdir('test-results/v2-services',{recursive:true});return fs.mkdtemp(path.resolve('test-results/v2-services/profile-'));}
test('PDF original, annotation revision, export, restart and trash preservation',async()=>{const root=await profile(),store=new Library(path.join(root,'library'));await store.ready;await store.createFolder('자료');const service=new PDFs(store),pdf=await PDFDocument.create();pdf.addPage([400,600]);const bytes=await pdf.save(),result=await service.import(bytes,'강의.pdf','자료');assert.equal(result.note.kind,'pdf');assert.equal(result.note.pages,1);assert.deepEqual(await fs.readFile(service.file(result.note.id)),Buffer.from(bytes));const object={id:require('node:crypto').randomUUID(),type:'pen',page:1,color:'#387a97',width:2,points:[[20,40],[40,80]]};const saved=await service.save({id:result.note.id,revision:0,objects:[object]});assert.equal(saved.revision,1);await assert.rejects(service.save({id:result.note.id,revision:0,objects:[]}),/다른 기기/);await assert.rejects(service.save({id:result.note.id,revision:1,objects:[{...object,points:[[NaN,0]]}]}),/형식/);assert.equal((await PDFDocument.load(await service.export(result.note.id,true))).getPageCount(),1);const reload=new Library(store.root);await reload.ready;assert.equal((await reload.list()).notes.find(n=>n.id===result.note.id).pages,1);await store.updateNote(result.note.id,{deleted:true});await assert.rejects(service.save({id:result.note.id,revision:1,objects:[]}),/삭제/);await store.restoreTrash([result.note.id]);assert.equal((await service.read(result.note.id)).objects.length,1);await assert.rejects(service.import(Buffer.from('invalid'),'invalid.pdf'),/PDF/);});
test('shared memo CAS rejects stale PC or web writes',async()=>{const store=new Library(path.join(await profile(),'library'));await store.ready;const a=new Memos(store),b=new Memos(store),note=(await a.create()).note,doc=await a.read(note.id);await a.save({id:note.id,revision:0,blocks:doc.blocks});await assert.rejects(b.save({id:note.id,revision:0,blocks:doc.blocks}),/다른 화면/);});
test('personal HTTPS server: trusted CA, one-time approval, auth, CSRF, Host and revoke',async()=>{const root=await profile(),dist=path.join(root,'dist');await fs.mkdir(dist);await fs.writeFile(path.join(dist,'web.html'),'<html>LOXT</html>');let calls=0;const server=new DeviceServer({root:path.join(root,'server'),dist,rpc:async()=>{calls++;return {ok:true};},asset:async()=>{throw Error('denied');}});await server.initialize();assert.equal(server.running,false);await server.configure(true);const port=server.port;async function request(route,options={}){return new Promise((resolve,reject)=>{const req=https.request({hostname:'127.0.0.1',port,path:route,ca:server.caPem,checkServerIdentity:(_host,cert)=>require('node:tls').checkServerIdentity('127.0.0.1',cert),method:options.method||'GET',headers:options.headers||{}},res=>{let data='';res.on('data',v=>data+=v);res.on('end',()=>resolve({status:res.statusCode,data,headers:res.headers}));});req.on('error',reject);if(options.body)req.write(JSON.stringify(options.body));req.end();});}try{assert.equal((await request('/api/session')).status,401);assert.equal((await request('/web.html')).status,200);const token=[...server.pending.keys()][0];const pending=await request('/api/pair',{method:'POST',body:{token,name:'test ipad'}});assert.equal(pending.status,200);const pairCookie=pending.headers['set-cookie'][0].split(';')[0];await server.approve(token,true);assert.equal((await request('/api/pair',{method:'POST',body:{token}})).status,403);const paired=await request('/api/pair',{method:'POST',headers:{Cookie:pairCookie},body:{token}}),cookie=paired.headers['set-cookie'][0].split(';')[0];assert.equal((await request('/api/pair',{method:'POST',body:{token}})).status,403);const session=JSON.parse((await request('/api/session',{headers:{Cookie:cookie}})).data);const payload={method:'test',payload:{},requestId:require('node:crypto').randomUUID()};assert.equal((await request('/api/rpc',{method:'POST',headers:{Cookie:cookie},body:payload})).status,403);const headers={Cookie:cookie,'X-LOXT-CSRF':session.csrf};assert.equal((await request('/api/rpc',{method:'POST',headers,body:payload})).status,200);await request('/api/rpc',{method:'POST',headers,body:payload});assert.equal(calls,1);assert.equal((await request('/api/session',{headers:{Cookie:cookie,Host:'attacker.example:'+port}})).status,403);const beforeRestartPort=server.port,identity=server.configuration.hostId;await server.configure(false);await server.configure(true);assert.equal(server.port,beforeRestartPort);assert.equal(server.configuration.hostId,identity);assert.equal((await request('/api/session',{headers:{Cookie:cookie}})).status,200);await server.revoke(server.configuration.devices[0].id);assert.equal((await request('/api/session',{headers:{Cookie:cookie}})).status,401);}finally{await server.configure(false);}});

 test('web undo belongs to each approved device; stale metadata cannot overwrite',async()=>{
  const root=await profile(),work=new Library(path.join(root,'work')),live=new Library(path.join(root,'live'));await Promise.all([work.ready,live.ready]);await work.createFolder('자료');
  const note=(await new Memos(work).create('자료')).note,services=require('../electron/web-services.cjs').webServices({libraries:{get:mode=>({work,live})[mode]},actions:{},root:path.join(root,'exports'),dist:'dist',conversions:{},preferences:{}});
  const expected={title:note.title,folder:note.folder,deleted:false};await services.rpc('library.update',{workspace:'work',id:note.id,changes:{title:'PC 제목'},expected});
  await assert.rejects(services.rpc('library.update',{workspace:'work',id:note.id,changes:{title:'오래된 제목'},expected}),/다른 기기/);
  await services.rpc('manage',{workspace:'work',action:'move',ids:[note.id],folders:[],folder:''},{device:'one'});
  await assert.rejects(services.rpc('manage',{workspace:'work',action:'undo'},{device:'two'}),/되돌릴 작업/);
  await services.rpc('manage',{workspace:'work',action:'undo'},{device:'one'});assert.equal(work.data.notes.find(n=>n.id===note.id).folder,'자료');
 });

 test('PDF text reader works without ReadableStream async iteration (iOS Safari regression)',async()=>{
  const {readPdfText}=await import('../src/pdfText.js');
  const prior=Object.getOwnPropertyDescriptor(ReadableStream.prototype,Symbol.asyncIterator);
  try{Object.defineProperty(ReadableStream.prototype,Symbol.asyncIterator,{value:undefined,configurable:true});
   const page={streamTextContent:()=>new ReadableStream({start(c){c.enqueue({items:[{str:'첫 페이지'}],styles:{font:{fontFamily:'sans-serif'}},lang:'ko'});c.enqueue({items:[{str:'한국어 필기'}],styles:{},lang:'ko'});c.close();}})};
   const result=await readPdfText(page);assert.deepEqual(result.items.map(i=>i.str),['첫 페이지','한국어 필기']);assert.equal(result.lang,'ko');assert.equal(result.styles.font.fontFamily,'sans-serif');
  }finally{if(prior)Object.defineProperty(ReadableStream.prototype,Symbol.asyncIterator,prior);else delete ReadableStream.prototype[Symbol.asyncIterator];}
 });
 test('PDF Korean export preserves CropBox/rotation, search index and ZIP originals',async()=>{
  const root=await profile(),store=new Library(path.join(root,'library'));await store.ready;await store.createFolder('자료');
  const original=await PDFDocument.create(),page=original.addPage([600,800]);page.setRotation(require('pdf-lib').degrees(90));page.setCropBox(40,70,460,640);
  const service=new PDFs(store),{note}=await service.import(await original.save(),'회전 문서.pdf','자료');
  const objects=[{id:require('node:crypto').randomUUID(),type:'text',page:1,color:'#387a97',width:3,points:[[90,240]],text:'한국어 필기'}, {id:require('node:crypto').randomUUID(),type:'highlight',page:1,color:'#ffa500',width:5,points:[[80,210],[220,210]]},{id:require('node:crypto').randomUUID(),type:'rect',page:1,color:'#dd3322',width:2,points:[[90,300],[190,400]]}];
  await service.save({id:note.id,revision:0,objects});await service.index({id:note.id,text:'검색할 원본 문장'});assert.match(await service.text(note.id),/검색할 원본 문장.*한국어 필기/);
  const file=path.join(root,'annotated.pdf'),bytes=await service.export(note.id,true,path.resolve('public/pdf-font.ttf'));await fs.writeFile(file,bytes);const exported=await PDFDocument.load(bytes),p=exported.getPage(0);assert.equal(p.getRotation().angle,90);assert.deepEqual(p.getCropBox(),page.getCropBox());
  const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs'),loaded=await pdfjs.getDocument({data:new Uint8Array(bytes),useSystemFonts:true,isEvalSupported:false}).promise;
  try{const text=await (await loaded.getPage(1)).getTextContent();assert.ok(text.items.some(item=>item.str==='한국어 필기'));}finally{await loaded.loadingTask.destroy();}
  const zip=path.join(root,'folder.zip');await require('../electron/folder-export.cjs').exportFolder({folder:'자료'},{library:store,dialog:{showSaveDialog:async()=>({filePath:zip})}});const entries=(await require('unzipper').Open.file(zip)).files;assert.ok(entries.some(e=>e.path.endsWith('원본.pdf')));assert.ok(entries.some(e=>e.path.endsWith('필기.json')));
 });
