import {Plugin} from '@tiptap/pm/state';
import {Decoration,DecorationSet} from '@tiptap/pm/view';
import {createExtension} from '@blocknote/core';
import {memoLanguage} from './memoCode.js';
export function withoutMemoBlocks(blocks,removed){const ids=new Set(removed);return blocks.flatMap(block=>{const children=withoutMemoBlocks(block.children||[],ids);return ids.has(block.id)?children:[{...block,children}];});}
export function deleteMemoBlocksPreservingChildren(editor,blocks){const ids=new Set(blocks.map(block=>block.id));const parents=new Set();function visit(list,selectedParent=false){for(const block of list){if(ids.has(block.id)&&!selectedParent)parents.add(block.id);visit(block.children||[],selectedParent||ids.has(block.id));}}visit(editor.document);return editor.transact(()=>{for(const block of blocks.filter(block=>parents.has(block.id)).reverse()){const surviving=withoutMemoBlocks(block.children||[],ids);editor.replaceBlocks([block.id],surviving);}});}
function preserveDelete({editor,event}){if(event.isComposing||editor.prosemirrorView.composing)return false;const selection=editor.prosemirrorState.selection;const selected=editor.getSelection()?.blocks;if(selection.nodes||selection.node){const blocks=selected?.length?selected:[editor.getTextCursorPosition().block];if(blocks.some(block=>block.children?.length)){deleteMemoBlocksPreservingChildren(editor,blocks);return true;}return false;}const block=editor.getTextCursorPosition().block;if(!selection.empty){if(block.children?.length&&selection.$from.sameParent(selection.$to)&&selection.$from.parentOffset===0&&selection.$to.parentOffset===selection.$to.parent.content.size){deleteMemoBlocksPreservingChildren(editor,[block]);return true;}return false;}if(block.children?.length&&selection.$from.parent.textContent===''){deleteMemoBlocksPreservingChildren(editor,[block]);return true;}return false;}
function rangeIndent({editor,event},outdent){if(event.isComposing||editor.prosemirrorView.composing)return false;const blocks=editor.getSelection()?.blocks;if(!blocks||blocks.length<2)return false;if(outdent){if(editor.canUnnestBlock())editor.unnestBlock();}else if(editor.canNestBlock())editor.nestBlock();return true;}

const guideColors=new Set(['gray','brown','red','orange','yellow','green','blue','purple','pink']);
function guideDecorations(doc){const decorations=[];doc.descendants((node,pos)=>{if(node.type.name!=='blockContainer'||node.childCount<2)return;const content=node.firstChild;let color=content.attrs.textColor;if(!color||color==='default'){let found=false;content.descendants(child=>{if(found)return false;if(child.isText&&child.text.trim()){found=true;color=child.marks.find(mark=>mark.type.name==='textColor')?.attrs.stringValue;}return !found;});}if(guideColors.has(color))decorations.push(Decoration.node(pos,pos+node.nodeSize,{'data-memo-guide-color':color}));});return DecorationSet.create(doc,decorations);}
const memoGuidePlugin=new Plugin({state:{init:(_,state)=>guideDecorations(state.doc),apply:(tr,old)=>tr.docChanged?guideDecorations(tr.doc):old},props:{decorations(state){return this.getState(state);}}});
export const memoEditingExtension=createExtension({key:'loxt-memo-editing',prosemirrorPlugins:[memoGuidePlugin],runsBefore:['quote-block-shortcuts','code-block-keyboard-shortcuts'],inputRules:[{find:/^>\s$/,replace:()=>({type:'toggleListItem'})},{find:/^```(.*?)\s$/,replace:({match})=>({type:'codeBlock',props:{language:memoLanguage(match[1])},content:[]})}],keyboardShortcuts:{Backspace:preserveDelete,Delete:preserveDelete,Tab:ctx=>rangeIndent(ctx,false),'Shift-Tab':ctx=>rangeIndent(ctx,true)}});
