import {useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import Icon from './Icon.jsx';
import {clampOverlay,visibleViewport,watchPlacement} from './viewportPlacement.js';
// Form controls are a dialog, not menuitems; arrows keep their native meaning.
export default function PdfProperties({children,label='필기 옵션',trigger,className=''}){
 const [open,setOpen]=useState(false),button=useRef(null),panel=useRef(null);
 useLayoutEffect(()=>{if(!open)return;const p=panel.current,b=button.current;const stop=watchPlacement(b,p,()=>{if(!b.getClientRects().length){if(p.contains(document.activeElement))b.closest('.document-identity')?.querySelector('input')?.focus({preventScroll:true});setOpen(false);return;}const bounds=visibleViewport(),r=b.getBoundingClientRect();p.style.maxWidth=Math.max(1,bounds.width-16)+'px';p.style.maxHeight=Math.max(1,bounds.height-16)+'px';const height=p.offsetHeight,below=r.bottom+6,above=r.top-height-6;const placed=clampOverlay({left:r.left,top:below+height>bounds.top+bounds.height-8&&above>=bounds.top+8?above:below},{width:p.offsetWidth,height},bounds);p.style.left=placed.left+'px';p.style.top=placed.top+'px';});const outside=e=>{if(!p.contains(e.target)&&!b.contains(e.target))setOpen(false);};const keys=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setOpen(false);b.focus();}if(e.key==='Tab'){const items=[...p.querySelectorAll('button,input,select')].filter(n=>!n.disabled);if(!items.length)return;const at=items.indexOf(document.activeElement);if(e.shiftKey&&at<=0||!e.shiftKey&&at===items.length-1){e.preventDefault();items[e.shiftKey?items.length-1:0].focus();}}};document.addEventListener('pointerdown',outside);p.addEventListener('keydown',keys);p.querySelector('input,button,select')?.focus();return()=>{stop();document.removeEventListener('pointerdown',outside);p.removeEventListener('keydown',keys);};},[open]);
 return <><button ref={button} aria-haspopup="dialog" aria-expanded={open} aria-label={label} onClick={()=>setOpen(v=>!v)}>{trigger||<Icon name="settings"/>}</button>{open?createPortal(<div ref={panel} role="dialog" aria-label={label} className={`pdf-properties unified-menu ${className}`}>{children}<button onClick={()=>{setOpen(false);button.current?.focus();}}>닫기</button></div>,button.current?.closest('.document-fullscreen')||document.body):null}</>;
}
