import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
// The matched legacy pair supplies browser API polyfills for iOS Safari.
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import worker from 'pdfjs-dist/legacy/build/pdf.worker.mjs?url';
import Menu from './Menu.jsx';
import Icon from './Icon.jsx';
import PdfThumbnail from './PdfThumbnail.jsx';
import { readPdfText } from './pdfText.js';
import './pdf.css';
pdfjs.GlobalWorkerOptions.workerSrc = worker;
const entries=new Map();
function entry(id,mode){const key=`${window.desktop.hostId || 'desktop'}:${mode}:${id}`;if(!entries.has(key))entries.set(key,{id,mode,key,state:{loading:true,objects:[],revision:0,error:'',dirty:false,saving:false},listeners:new Set(),history:[],redo:[],timer:null,request:null});return entries.get(key);}
function publish(e,changes){e.state={...e.state,...changes};e.listeners.forEach(fn=>fn());}
function backup(e){try{localStorage.setItem('loxt.pdf.draft:'+e.key,JSON.stringify({revision:e.state.revision,objects:e.state.objects}));}catch{publish(e,{error:'임시 저장 공간이 부족합니다. 연결 상태를 확인해 주세요.'});}}
async function persist(e){if(e.request)return e.request;if(!e.state.dirty||e.state.loading)return;clearTimeout(e.timer);const objects=e.state.objects;publish(e,{saving:true});e.request=window.desktop.pdf.save({workspace:e.mode,id:e.id,revision:e.state.revision,objects,preview:e.state.preview}).then(doc=>{publish(e,{revision:doc.revision,saving:false,dirty:e.state.objects!==objects,error:''});if(!e.state.dirty)localStorage.removeItem('loxt.pdf.draft:'+e.key);}).catch(error=>{backup(e);publish(e,{saving:false,error:error.message});}).finally(()=>{e.request=null;if(e.state.dirty&&!e.state.error)e.timer=setTimeout(()=>persist(e),200);});return e.request;}
function modify(e,objects){e.history.push(e.state.objects);e.history=e.history.slice(-100);e.redo=[];publish(e,{objects,dirty:true,error:''});backup(e);clearTimeout(e.timer);e.timer=setTimeout(()=>persist(e),250);}
export default function PdfPage({note,mode='work',onBack,onUpdate}){
 const e=entry(note.id,mode),state=useSyncExternalStore(fn=>{e.listeners.add(fn);return()=>e.listeners.delete(fn);},()=>e.state);
 const [pdf,setPdf]=useState(null),[page,setPage]=useState(1),[zoom,setZoom]=useState(1),[tool,setTool]=useState('select'),[color,setColor]=useState('#387a97'),[width,setWidth]=useState(2),[pagesOpen,setPagesOpen]=useState(()=>innerWidth>700),[viewport,setViewport]=useState(null),[draft,setDraft]=useState(null),[selected,setSelected]=useState(null),[text,setText]=useState(null),[query,setQuery]=useState(''),[matches,setMatches]=useState([]),[matchIndex,setMatchIndex]=useState(0),[searching,setSearching]=useState(false),[title,setTitle]=useState(note.title),[loadError,setLoadError]=useState(''),[loadStack,setLoadStack]=useState('');
 function report(error,stage){setLoadError(error.message);setLoadStack(error.stack||String(error));window.desktop.reportClientError?.({scope:'pdf.'+stage,stack:error.stack||String(error),version:pdfjs.version}).catch(()=>{});}
 const root=useRef(null),canvas=useRef(null),textLayer=useRef(null),area=useRef(null),stroke=useRef(null),pdfRef=useRef(null),menuButton=useRef(null);
 useEffect(()=>{let active=true,task;const load=async()=>{try{const [bytes,doc]=await Promise.all([window.desktop.pdf.bytes({workspace:mode,id:note.id}),window.desktop.pdf.get({workspace:mode,id:note.id})]);if(e.state.loading||!e.state.dirty&&!e.state.saving){let pending;try{pending=JSON.parse(localStorage.getItem('loxt.pdf.draft:'+e.key));}catch{}publish(e,{...doc,loading:false,dirty:Boolean(pending),objects:pending?.objects || doc.objects,revision:pending?.revision ?? doc.revision,error:pending?'저장 대기 중인 필기를 복구했습니다. 저장을 다시 시도해 주세요.':''});}task=pdfjs.getDocument({data:new Uint8Array(bytes),isEvalSupported:false,cMapUrl:new URL("./pdf-assets/cmaps/",location.href).href,cMapPacked:true,standardFontDataUrl:new URL("./pdf-assets/standard_fonts/",location.href).href,wasmUrl:new URL("./pdf-assets/wasm/",location.href).href});const loaded=await task.promise;if(active){setPdf(loaded);pdfRef.current=loaded;void(async()=>{let content='';for(let n=1;active&&n<=loaded.numPages&&content.length<2_000_000;n++){const p=await loaded.getPage(n),items=await readPdfText(p);content+=items.items.map(i=>i.str||'').join(' ')+'\n';if(n%4===0)await new Promise(resolve=>setTimeout(resolve,0));}if(active&&!note.deleted)await window.desktop.pdf.index({workspace:mode,id:note.id,text:content.slice(0,2_000_000)});})().catch(()=>{});}else await task.destroy();}catch(error){if(active)report(error,'load');}};load();return()=>{active=false;persist(e);task?.destroy();};},[note.id,mode]);
 useEffect(()=>{if(!pdf||!canvas.current)return;canvas.current.dataset.rendered='false';let active=true,render,layer;const run=async()=>{try{const p=await pdf.getPage(page);if(!active)return;const v=p.getViewport({scale:zoom});setViewport(v);const ratio=Math.min(devicePixelRatio || 1,2),c=canvas.current;c.width=Math.ceil(v.width*ratio);c.height=Math.ceil(v.height*ratio);c.style.width=v.width+'px';c.style.height=v.height+'px';render=p.render({canvasContext:c.getContext('2d'),viewport:v,transform:[ratio,0,0,ratio,0,0]});await render.promise;if(!active)return;textLayer.current.replaceChildren();layer=new pdfjs.TextLayer({textContentSource:await readPdfText(p),container:textLayer.current,viewport:v});await layer.render();if(active)canvas.current.dataset.rendered='true';}catch(error){if(active&&error.name!=='RenderingCancelledException')report(error,'render');}};run();return()=>{active=false;render?.cancel();layer?.cancel();};},[pdf,page,zoom]);
 useEffect(()=>{const unload=event=>{if(e.state.dirty){backup(e);event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload);},[e]);
 useEffect(()=>window.desktop.onLibraryChange(async event=>{if(event.workspace!==mode||e.state.dirty||e.state.saving)return;try{const doc=await window.desktop.pdf.get({workspace:mode,id:note.id});if(!e.state.dirty&&!e.state.saving&&doc.revision>e.state.revision)publish(e,doc);}catch{}}),[e,mode,note.id]);
 const change=objects=>{if(!note.deleted)modify(e,objects);};
 function undo(redo=false){const from=redo?e.redo:e.history,to=redo?e.history:e.redo;if(!from.length)return;to.push(e.state.objects);publish(e,{objects:from.pop(),dirty:true,error:''});backup(e);persist(e);}
 function keys(event){if(event.target.closest('input,textarea,[contenteditable=true],[role=menu]'))return;const k=event.key.toLowerCase(),ctrl=event.ctrlKey||event.metaKey;if(ctrl&&k==='f'){event.preventDefault();event.stopPropagation();setSearching(true);return;}if(ctrl&&k==='d'){event.preventDefault();menuButton.current?.querySelector('button')?.click();}else if(ctrl&&event.shiftKey&&['p','e','h'].includes(k)){event.preventDefault();setTool({p:'pen',e:'erase',h:'highlight'}[k]);}else if(ctrl&&k==='z'){event.preventDefault();event.stopPropagation();undo(event.shiftKey);}else if(!ctrl&&!event.altKey&&k==='t'){setTool('text');event.preventDefault();}else if(event.key==='Escape'){setTool('select');setSelected(null);setText(null);}else if(event.key==='Delete'&&selected){event.preventDefault();change(state.objects.filter(o=>o.id!==selected));setSelected(null);}}
 function point(event){const box=area.current.getBoundingClientRect();return viewport.convertToPdfPoint(event.clientX-box.left,event.clientY-box.top);}
 function down(event){if(!viewport||note.deleted||(event.pointerType==='mouse'&&event.button!==0)||event.target.closest('textarea'))return;if(tool==='select'){const id=event.target.closest('[data-object]')?.dataset.object;setSelected(id || null);if(id){event.preventDefault();stroke.current={move:id,start:point(event),original:state.objects.find(o=>o.id===id),resize:event.target.dataset.resize==='true'};event.currentTarget.setPointerCapture(event.pointerId);}return;}event.preventDefault();const p=point(event);if(tool==='erase'){const id=event.target.closest('[data-object]')?.dataset.object;if(id)change(state.objects.filter(o=>o.id!==id));return;}if(tool==='text'){setText({point:p,value:''});return;}stroke.current={id:crypto.randomUUID(),type:tool,page,color,width,points:[p]};setDraft(stroke.current);event.currentTarget.setPointerCapture(event.pointerId);}
 function move(event){const s=stroke.current;if(!s)return;event.preventDefault();const p=point(event);if(s.move){const [dx,dy]=[p[0]-s.start[0],p[1]-s.start[1]],o=s.original;let points;if(s.resize){const a=o.points[0],b=o.points.at(-1),sx=Math.abs(b[0]-a[0])>.01?(b[0]-a[0]+dx)/(b[0]-a[0]):1,sy=Math.abs(b[1]-a[1])>.01?(b[1]-a[1]+dy)/(b[1]-a[1]):1;points=o.points.map(v=>[a[0]+(v[0]-a[0])*sx,a[1]+(v[1]-a[1])*sy]);}else points=o.points.map(v=>[v[0]+dx,v[1]+dy]);setDraft({...o,points,width:s.resize&&o.type==='text'?Math.max(.5,Math.min(20,o.width+dx/20)):o.width});}else {s.points=['pen','highlight'].includes(s.type)?[...s.points,p]:[s.points[0],p];setDraft({...s});}}
 function up(){const s=stroke.current;if(!s)return;if(s.move){if(draft)change(state.objects.map(o=>o.id===s.move?draft:o));}else if(s.points.length>1)change([...state.objects,{...s}]);stroke.current=null;setDraft(null);}
 function finishText(){if(text){const objects=state.objects.filter(o=>o.id!==text.id);if(text.value.trim())objects.push({id:text.id||crypto.randomUUID(),type:'text',page,color:text.color||color,width:text.width||width,points:[text.point],text:text.value});change(objects);}setText(null);}
 function object(o){const p=o.points.map(v=>viewport.convertToViewportPoint(...v)),a=p[0],b=p.at(-1);if(!a)return null;const props={'data-object':o.id,stroke:o.color,strokeWidth:o.width*zoom,fill:'none',style:{pointerEvents:'all'},onClick:()=>setSelected(o.id),onDoubleClick:o.type==='text'?()=>{if(!note.deleted)setText({id:o.id,point:o.points[0],value:o.text,color:o.color,width:o.width});}:undefined};let shape;if(o.type==='text')shape=<text {...props} fill={o.color} stroke="none" x={a[0]} y={a[1]} fontSize={Math.max(8,o.width*6)*zoom}>{(o.text||'').split('\n').map((line,i)=><tspan x={a[0]} dy={i?Math.max(8,o.width*6)*zoom:0} key={i}>{line}</tspan>)}</text>;else if(o.type==='rect')shape=<rect {...props} x={Math.min(a[0],b[0])} y={Math.min(a[1],b[1])} width={Math.abs(b[0]-a[0])} height={Math.abs(b[1]-a[1])}/>;else if(o.type==='ellipse')shape=<ellipse {...props} cx={(a[0]+b[0])/2} cy={(a[1]+b[1])/2} rx={Math.abs(b[0]-a[0])/2} ry={Math.abs(b[1]-a[1])/2}/>;else shape=<polyline {...props} points={p.map(v=>v.join(',')).join(' ')} strokeWidth={o.width*zoom*(o.type==='highlight'?5:1)} opacity={o.type==='highlight'?.3:1} markerEnd={o.type==='arrow'?'url(#pdf-arrow)':undefined}/>;return <g key={o.id}>{shape}{selected===o.id&&tool==='select'?<rect data-object={o.id} data-resize="true" x={b[0]-4} y={b[1]-4} width="8" height="8" fill="var(--blue)"/>:null}</g>;}
 async function search(){if(!pdf)return;setSearching(true);const found=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),content=await readPdfText(p);if(query.trim()&&content.items.map(i=>i.str||'').join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()))found.push(n);}setMatches(found);setMatchIndex(0);if(found.length)setPage(found[0]);}
 const tools=[['select','선택','Esc'],['pen','펜','Ctrl+Shift+P'],['highlight','형광펜','Ctrl+Shift+H'],['erase','지우개','Ctrl+Shift+E'],['text','텍스트','T']];
 return <section ref={root} className="content workspace pdf-workspace" tabIndex="0" onKeyDown={keys}>
 <div className="heading workspace-heading"><button className="back" onClick={async()=>{await persist(e);onBack();}}>← 보관함</button><div className="workspace-title"><div className="detail-title"><input aria-label="PDF 제목" value={title} readOnly={note.deleted} maxLength={120} onChange={ev=>setTitle(ev.target.value)} onBlur={()=>onUpdate?.({title:title.trim()||note.title})}/></div><div className="detail-meta">{note.folder||'내 보관함'} / {note.pages}쪽</div></div><Menu label="PDF 내보내기" trigger={<><Icon name="download"/>내보내기<Icon name="chevronDown"/></>}>{close=><>{[['annotated','필기 포함 PDF'],['original','원본 PDF']].map(([format,label])=><button role="menuitem" key={format} onClick={async()=>{close();await persist(e);if(e.state.dirty){publish(e,{error:'저장하지 못한 필기가 있습니다. 저장 후 내보내 주세요.'});return;}try{await window.desktop.pdf.export({workspace:mode,id:note.id,annotated:format==='annotated'});}catch(error){publish(e,{error:error.message});}}}>{label}</button>)}</>}</Menu></div>
 {loadStack?<details className="pdf-error-detail"><summary>PDF 오류 상세</summary><pre>{loadStack}</pre></details>:null}
 {state.recovered?<p className="recovery-message">필기 백업을 복구했습니다. 마지막 수정 일부는 포함되지 않을 수 있습니다. 원본을 보존하고 수정 내용을 저장합니다.</p>:null}
 {(loadError||state.error)?<p className="error-message" role="alert">{loadError||state.error} {state.dirty?<><button className="secondary" onClick={()=>persist(e)}>저장 재시도</button><button className="secondary" onClick={async()=>{backup(e);const doc=await window.desktop.pdf.get({workspace:mode,id:note.id});publish(e,{...doc,dirty:false,error:''});}}>최신 내용 보기</button><button className="secondary" onClick={async()=>{try{const bytes=await window.desktop.pdf.bytes({workspace:mode,id:note.id}),copy=await window.desktop.pdf.import({workspace:mode,folder:note.folder,name:title+' 필기 사본.pdf',bytes});await window.desktop.pdf.save({workspace:mode,id:copy.note.id,revision:0,objects:state.objects});publish(e,{error:'내 필기를 보관함에 사본으로 저장했습니다.'});}catch(error){publish(e,{error:error.message});}}}>내 필기 사본 저장</button></>:null}</p>:null}
 <div className="pdf-frame"><div className="pdf-toolbar"><button aria-label="페이지 미리보기" aria-expanded={pagesOpen} onClick={()=>setPagesOpen(v=>!v)}>페이지</button>{tools.map(([id,label,key])=><button key={id} disabled={note.deleted} aria-pressed={tool===id} title={`${label} · ${key}`} onClick={()=>setTool(id)}>{label}</button>)}<span ref={menuButton}><Menu label="도형" trigger={<>도형<Icon name="chevronDown"/></>}>{close=><>{[['line','직선'],['arrow','화살표'],['rect','사각형'],['ellipse','원']].map(([id,label])=><button role="menuitem" key={id} onClick={()=>{setTool(id);close();}}>{label}</button>)}</>}</Menu></span><Menu label="필기 옵션" trigger={<>필기 옵션<Icon name="chevronDown"/></>}>{()=><div className="pdf-tool-options"><label>색상<input aria-label="필기 색상" type="color" value={color} onChange={ev=>setColor(ev.target.value)}/></label><label>굵기<input aria-label="필기 굵기" type="range" min="1" max="8" value={width} onChange={ev=>setWidth(Number(ev.target.value))}/>{width}</label></div>}</Menu><button aria-label="실행 취소" disabled={!e.history.length||note.deleted} onClick={()=>undo()}>↶</button><button aria-label="다시 실행" disabled={!e.redo.length||note.deleted} onClick={()=>undo(true)}>↷</button><span role="status" className="pdf-save-state">{state.saving?'저장 중…':state.dirty?'저장 대기':state.loading?'불러오는 중…':'저장됨'}</span></div>
 <div className={`pdf-body ${pagesOpen?'pages-open':''}`}><aside className="pdf-pages" inert={!pagesOpen||undefined}>{pdf?Array.from({length:pdf.numPages},(_,i)=><PdfThumbnail key={i} pdf={pdf} number={i+1} active={page===i+1} open={pagesOpen} onOpen={()=>{setPage(i+1);setSelected(null);}}/>):null}</aside><div className={`pdf-scroll ${tool!=='select'?'pdf-drawing':''}`} onTouchMove={event=>{if(tool!=='select'&&event.touches.length===1)event.stopPropagation();}}>{!pdf?<div className="empty">PDF를 불러오는 중…</div>:<div ref={area} className={`pdf-sheet tool-${tool}`} style={viewport?{width:viewport.width,height:viewport.height,"--total-scale-factor":zoom,"--scale-round-x":"1px","--scale-round-y":"1px"}:undefined}><canvas ref={canvas}/><div ref={textLayer} className="textLayer" style={{pointerEvents:tool==='select'?'auto':'none'}}/><svg className="pdf-ink" width={viewport?.width||0} height={viewport?.height||0} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{stroke.current=null;setDraft(null);}} style={{pointerEvents:tool==='select'?'none':'auto',touchAction:tool==='select'?'auto':'none'}}>{tool!=='select'?<rect width="100%" height="100%" fill="transparent" style={{pointerEvents:'all'}}/>:null}<defs><marker id="pdf-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8" fill={color}/></marker></defs>{viewport?state.objects.filter(o=>o.page===page&&o.id!==draft?.id&&o.id!==text?.id).map(object):null}{viewport&&draft?object(draft):null}</svg>{text&&viewport?<textarea autoFocus aria-label="PDF 텍스트 입력" value={text.value} style={{left:viewport.convertToViewportPoint(...text.point)[0],top:viewport.convertToViewportPoint(...text.point)[1]-20}} onChange={ev=>setText({...text,value:ev.target.value})} onBlur={finishText} onKeyDown={ev=>{if(ev.key==='Escape'){ev.stopPropagation();finishText();setTool('select');}}}/>:null}</div>}</div></div>
 <div className="pdf-footer"><button onClick={()=>setSearching(v=>!v)}>검색</button>{searching?<form onSubmit={ev=>{ev.preventDefault();search();}}><input autoFocus aria-label="PDF 검색" value={query} onChange={ev=>setQuery(ev.target.value)}/><button>찾기</button>{query?<span>{matches.length?`${matchIndex+1} / ${matches.length}`:"0개"}</span>:null}<button type="button" aria-label="이전 PDF 검색 결과" disabled={!matches.length} onClick={()=>{const n=(matchIndex-1+matches.length)%matches.length;setMatchIndex(n);setPage(matches[n]);}}>↑</button><button type="button" aria-label="다음 PDF 검색 결과" disabled={!matches.length} onClick={()=>{const n=(matchIndex+1)%matches.length;setMatchIndex(n);setPage(matches[n]);}}>↓</button></form>:null}<div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><input aria-label="PDF 페이지 번호" type="number" min="1" max={pdf?.numPages||1} value={page} onChange={ev=>setPage(Math.max(1,Math.min(pdf?.numPages||1,Number(ev.target.value)||1)))}/> / {pdf?.numPages||note.pages}<button disabled={!pdf||page>=pdf.numPages} onClick={()=>setPage(p=>p+1)}>›</button></div><div><button onClick={()=>setZoom(z=>Math.max(.25,z-.25))}>−</button>{Math.round(zoom*100)}%<button onClick={()=>setZoom(z=>Math.min(4,z+.25))}>+</button><Menu label="PDF 맞춤" trigger={<>맞춤<Icon name="chevronDown"/></>}>{close=><>{[["width","너비 맞춤"],["page","페이지 맞춤"]].map(([kind,label])=><button role="menuitem" key={kind} onClick={()=>{close();if(viewport&&area.current){const parent=area.current.parentElement;setZoom(Math.max(.1,Math.min(4,zoom*(kind==="width"?(parent.clientWidth-40)/viewport.width:Math.min((parent.clientWidth-40)/viewport.width,(parent.clientHeight-40)/viewport.height)))));}}}>{label}</button>)}</>}</Menu></div></div></div></section>;
}
