import {useEffect,useMemo,useLayoutEffect,useRef,useState,useSyncExternalStore} from 'react';
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import worker from 'pdfjs-dist/legacy/build/pdf.worker.mjs?url';
import Modal from './Modal.jsx';
import {changeDrawingPage} from './drawingPages.js';
import {pdfShortcuts} from './pdfShortcuts.js';
import Menu from './Menu.jsx';
import Icon from './Icon.jsx';
import PdfPageRail from './PdfPageRail.jsx';
import {remotePDF} from './pdfRemote.js';
import {useDocumentFullscreen} from './documentView.js';
import PdfProperties from './PdfProperties.jsx';
import PdfTextEditor from './PdfTextEditor.jsx';
import DocumentMetadata from './DocumentMetadata.jsx';
import PdfInkObject from './PdfInkObject.jsx';
import useDocumentTitle,{mergeSaveStatus} from './useDocumentTitle.js';
import {readPdfText,forgetPdfText} from './pdfText.js';
import {pdfEntry,publish,backup,loadAnnotations,modify,persist,undoPdf} from './pdfStore.js';
import {clampZoom,appendPoint,touchesObject,matchingItems} from './pdfGeometry.js';
import './pdf.css';
pdfjs.GlobalWorkerOptions.workerSrc=worker;
const defaults={pen:{color:'#387a97',width:2},highlight:{color:'#e9bd52',width:4},text:{color:'#222222',width:2,fontSize:16},shape:{color:'#387a97',width:2}};
const shapes=[['line','직선'],['arrow','화살표'],['rect','사각형'],['ellipse','원']];
const toolNames={select:'선택',hand:'이동',pen:'펜',highlight:'형광펜',erase:'지우개',text:'텍스트',...Object.fromEntries(shapes)};
const toolIcons={select:'cursor',hand:'hand',pen:'pen',highlight:'highlight',erase:'erase',text:'text',line:'line',arrow:'arrow',rect:'rectangle',ellipse:'ellipse'};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
export default function PdfPage({note,mode='work',onBack,onUpdate}){
 const e=pdfEntry(note.id,mode),state=useSyncExternalStore(fn=>{e.listeners.add(fn);return()=>e.listeners.delete(fn);},()=>e.state);
 const viewKey='loxt.pdf.view:'+e.key,prefsKey='loxt.pdf.tools:'+(window.desktop.hostId||'desktop'),initial=useRef(read(viewKey,{})).current;
 const {title,setTitle,saveTitle,error:titleError,status:titleStatus}=useDocumentTitle(note,onUpdate);
 const [sourcePdf,setPdf]=useState(null),[page,setPage]=useState(initial.page||1),[zoom,setZoom]=useState(clampZoom(initial.zoom||1)),[fit,setFit]=useState(initial.fit||'width'),[fitReady,setFitReady]=useState(!initial.fit&&Boolean(initial.zoom));
 const drawing=note.documentType==='drawing';
 const pdf=useMemo(()=>!sourcePdf?null:!drawing?sourcePdf:{numPages:state.pageIds?.length||1,getPage:()=>sourcePdf.getPage(1),getOutline:async()=>[],getDestination:async()=>null,getPageIndex:async()=>0},[sourcePdf,drawing,state.pageIds]);
 const [pageDialog,setPageDialog]=useState(null);
 useEffect(()=>{if(drawing&&state.pageIds)setPage(p=>Math.min(p,state.pageIds.length));},[drawing,state.pageIds]);
 function pageAction(action,number=page){finishStroke();try{const changed=changeDrawingPage(e.state,action,number);modify(e,changed.objects,{pageIds:changed.pageIds});setPage(changed.page);setSelected(null);setText(null);setPageDialog(null);}catch(error){publish(e,{error:error.message});}}
 const [tool,setTool]=useState(note.documentType==='drawing'?'pen':'select'),[properties,setProperties]=useState(()=>({...defaults,...read(prefsKey,{})})),[fingerInk,setFingerInk]=useState(()=>read(prefsKey+':finger',note.documentType==='drawing'));
 const [pagesOpen,setPagesOpen]=useState(initial.pagesOpen??(innerWidth>700&&!matchMedia('(pointer:coarse)').matches)),[outline,setOutline]=useState([]),[railTab,setRailTab]=useState('pages'),[viewport,setViewport]=useState(null),[draft,setDraft]=useState(null),[selected,setSelected]=useState(null),[text,setText]=useState(null);
 const [query,setQuery]=useState(''),[matches,setMatches]=useState([]),[matchIndex,setMatchIndex]=useState(0),[searching,setSearching]=useState(false),[searchBusy,setSearchBusy]=useState(false),[searchNote,setSearchNote]=useState(''),[pageItems,setPageItems]=useState([]),[links,setLinks]=useState([]);
 const [loadError,setLoadError]=useState(''),[loadStack,setLoadStack]=useState(''),[loadProgress,setLoadProgress]=useState(null),[rendering,setRendering]=useState(true),[retry,setRetry]=useState(0),[paper,setPaper]=useState(initial.paper||'original'),[size,setSize]=useState({width:0,height:0});
 const root=useRef(null),canvas=useRef(null),layer=useRef(null),area=useRef(null),scroll=useRef(null),stroke=useRef(null),touches=useRef(new Map()),gesture=useRef(null),frame=useRef(null),anchor=useRef(null),space=useRef(false),searchToken=useRef(0),pageTexts=useRef(null),restoreScroll=useRef(true),viewRef=useRef(null),shapeButton=useRef(null);
 const previewSession=useRef(crypto.randomUUID()),previewSent=useRef(0),[remoteInk,setRemoteInk]=useState([]);
 function sendPreview(object){if(!window.desktop.pdf.previewInk)return;const now=performance.now();if(object&&now-previewSent.current<50)return;previewSent.current=now;let value=object;if(object){const points=object.points.length>600?object.points.filter((_,i)=>i%Math.ceil(object.points.length/599)===0||i===object.points.length-1):object.points;value={id:object.id,type:object.type,page:object.page,color:object.color,width:object.width,points,text:object.text||'',fontSize:object.fontSize};}window.desktop.pdf.previewInk({workspace:mode,id:note.id,session:previewSession.current,object:value}).catch(()=>{});}
 useEffect(()=>{const values=new Map();const off=window.desktop.pdf.onPreview?.(value=>{if(value.session===previewSession.current)return;if(value.clear){for(const [key,item]of values)if(item.actor===value.actor)values.delete(key);}else if(value.id===note.id&&value.workspace===mode){const key=value.actor+':'+value.session;if(value.object)values.set(key,value);else values.delete(key);}setRemoteInk([...values.values()]);});const expiry=setInterval(()=>{let changed=false;for(const [key,item]of values)if(item.expires<Date.now()){values.delete(key);changed=true;}if(changed)setRemoteInk([...values.values()]);},500);return()=>{off?.();clearInterval(expiry);sendPreview(null);};},[note.id,mode]);
 const [fullscreen,toggleFullscreen]=useDocumentFullscreen(root);
 const zoomTimer=useRef(null),zoomFrame=useRef(null),previewZoom=useRef(null),renderedPage=useRef(null),renderedZoom=useRef(1);
 const editable=!note.deleted,bucket=['pen','highlight','text'].includes(tool)?tool:'shape',activeObject=state.objects.find(o=>o.id===selected),style=activeObject||properties[bucket];
 viewRef.current={page,zoom,fit,pagesOpen,paper,left:scroll.current?.scrollLeft||0,top:scroll.current?.scrollTop||0};
 function report(error,stage){setLoadError(error.message);setLoadStack(error.stack||String(error));window.desktop.reportClientError?.({scope:'pdf.'+stage,stack:error.stack||String(error),version:pdfjs.version}).catch(()=>{});}
 function commit(objects){if(editable)modify(e,objects);}
 function chooseTool(value){finishStroke();setTool(value);setSelected(null);}
 function property(change){if(activeObject){commit(state.objects.map(o=>o.id===selected?{...o,...change}:o));return;}setProperties(p=>{const next={...p,[bucket]:{...p[bucket],...change}};write(prefsKey,next);return next;});}
 function navigatePage(value){finishStroke();setText(null);setSelected(null);setPage(Math.max(1,Math.min(pdf?.numPages||note.pages,value)));scroll.current?.scrollTo(0,0);}
 useEffect(()=>{let active=true,task;setLoadError('');setLoadStack('');setLoadProgress(null);setRendering(true);setPdf(null);
  const load=async()=>{try{
   const annotations=loadAnnotations(e);annotations.catch(()=>{});const payload={workspace:mode,id:note.id};
   const info=await window.desktop.pdf.info?.(payload);if(!active)return;
   if(window.desktop.remote&&info?.bytes>=32*1024*1024){const loaded=await remotePDF(payload,info);task={destroy:()=>loaded.destroy()};await annotations;if(!active){await loaded.destroy();return;}setPdf(loaded);setPage(p=>Math.min(p,loaded.numPages));loaded.getOutline().then(value=>{if(active)setOutline(value);}).catch(()=>{});return;}
   const source=window.desktop.pdf.source?{url:window.desktop.pdf.source(payload),withCredentials:true,disableAutoFetch:true,disableStream:true,rangeChunkSize:131072}:{data:new Uint8Array(await window.desktop.pdf.bytes(payload))};
   if(!active)return;task=pdfjs.getDocument({...source,isEvalSupported:false,cMapUrl:new URL('./pdf-assets/cmaps/',location.href).href,cMapPacked:true,standardFontDataUrl:new URL('./pdf-assets/standard_fonts/',location.href).href,wasmUrl:new URL('./pdf-assets/wasm/',location.href).href});
   task.onProgress=({loaded,total})=>{if(active)setLoadProgress(total>0?Math.round(loaded/total*100):null);};
   const loaded=await task.promise;await annotations;if(!active)return;setPdf(loaded);setPage(p=>Math.min(p,loaded.numPages));
   loaded.getOutline().then(value=>{if(active)setOutline(value||[]);}).catch(()=>{});
   window.desktop.pdf.searchIndex?.(payload).then(cached=>{if(active&&cached?.pages)pageTexts.current=cached.pages;}).catch(()=>{});
  }catch(error){if(active)report(error,'load');}};
  load();return()=>{active=false;clearTimeout(zoomTimer.current);cancelAnimationFrame(zoomFrame.current);cancelAnimationFrame(frame.current);finishStroke();persist(e);forgetPdfText();task?.destroy();write(viewKey,viewRef.current);};
 },[note.id,mode,retry]);
 useEffect(()=>{const target=scroll.current;if(!target)return;const observer=new ResizeObserver(()=>setSize({width:target.clientWidth,height:target.clientHeight}));observer.observe(target);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!fit){setFitReady(true);return;}if(!pdf||!size.width||!size.height)return;let active=true,timer;setFitReady(false);const apply=()=>{if(gesture.current?.kind==='pinch'){timer=setTimeout(apply,80);return;}pdf.getPage(page).then(p=>{if(!active)return;const v=p.getViewport({scale:1}),margin=size.width<600?20:40;setZoom(clampZoom(fit==='width'?(size.width-margin)/v.width:Math.min((size.width-margin)/v.width,(size.height-margin)/v.height)));setFitReady(true);});};timer=setTimeout(apply,180);return()=>{active=false;clearTimeout(timer);};},[pdf,page,fit,size.width,size.height]);
 useEffect(()=>{if(!pdf||!canvas.current||!fitReady)return;let active=true,render,textRender,buffer;setRendering(true);
  const run=async()=>{try{const p=await pdf.getPage(page);if(!active)return;const v=p.getViewport({scale:zoom}),mobile=window.desktop.remote||matchMedia('(pointer:coarse)').matches,budget=mobile?5_242_880:12_000_000,ratio=Math.min(devicePixelRatio||1,2,Math.sqrt(budget/(v.width*v.height)));
   buffer=document.createElement('canvas');buffer.width=Math.max(1,Math.floor(v.width*ratio));buffer.height=Math.max(1,Math.floor(v.height*ratio));
   render=p.render({canvasContext:buffer.getContext('2d'),viewport:v,transform:[ratio,0,0,ratio,0,0]});await render.promise;while(active&&gesture.current?.kind==='pinch')await new Promise(resolve=>setTimeout(resolve,40));if(!active)return;
   const c=canvas.current;c.width=buffer.width;c.height=buffer.height;c.getContext('2d').drawImage(buffer,0,0);c.style.width=v.width+'px';c.style.height=v.height+'px';buffer.width=buffer.height=1;buffer=null;
   if(renderedPage.current!==page){layer.current.replaceChildren();setPageItems([]);setLinks([]);}renderedPage.current=page;renderedZoom.current=zoom;
   if(area.current){area.current.style.transform='';area.current.classList.remove('pdf-zoom-preview');}previewZoom.current=null;setViewport(v);c.dataset.rendered='true';setRendering(false);setLoadError('');
   const content=await readPdfText(p);if(!active)return;setPageItems(content.items);
   // Build the text layer separately; it never delays the visible page swap.
   const textBuffer=document.createElement('div');textBuffer.className='textLayer';textBuffer.style.width=(v.rawDims.pageWidth*zoom)+'px';textBuffer.style.height=(v.rawDims.pageHeight*zoom)+'px';textBuffer.style.setProperty('--total-scale-factor',zoom);
   textRender=new pdfjs.TextLayer({textContentSource:content,container:textBuffer,viewport:v});await textRender.render();if(!active)return;layer.current.replaceChildren(...textBuffer.childNodes);for(let i=0;i<textBuffer.style.length;i++){const name=textBuffer.style.item(i);layer.current.style.setProperty(name,textBuffer.style.getPropertyValue(name));}layer.current.dataset.mainRotation=textBuffer.dataset.mainRotation||'0';
   const annotations=await p.getAnnotations({intent:'display'});if(active)setLinks(annotations.filter(a=>a.subtype==='Link'&&(a.dest||/^https?:|^mailto:/i.test(a.url||''))));
  }catch(error){if(active&&error.name!=='RenderingCancelledException'){setRendering(false);report(error,'render');}}finally{if(buffer){buffer.width=buffer.height=1;buffer=null;}}};run();return()=>{active=false;render?.cancel();textRender?.cancel();};
 },[pdf,page,zoom,retry,fitReady]);
 useLayoutEffect(()=>{if(!viewport||!area.current||!scroll.current)return;const s=scroll.current;if(anchor.current){const a=anchor.current,p=viewport.convertToViewportPoint(...a.pdf);s.scrollLeft=area.current.offsetLeft+p[0]-a.x;s.scrollTop=area.current.offsetTop+p[1]-a.y;anchor.current=null;}else if(restoreScroll.current&&!fit){s.scrollLeft=initial.left||0;s.scrollTop=initial.top||0;restoreScroll.current=false;}},[viewport]);
 useEffect(()=>{const timer=setTimeout(()=>write(viewKey,viewRef.current),300);return()=>clearTimeout(timer);},[page,zoom,fit,pagesOpen,paper]);
 useEffect(()=>{const el=scroll.current;if(!el)return;const wheel=event=>{if(event.ctrlKey||event.metaKey){event.preventDefault();zoomAt((previewZoom.current||zoom)*Math.exp(-event.deltaY*.002),event.clientX,event.clientY);}};el.addEventListener('wheel',wheel,{passive:false});const gestureStart=event=>event.preventDefault();el.addEventListener('gesturestart',gestureStart,{passive:false});el.addEventListener('gesturechange',gestureStart,{passive:false});return()=>{el.removeEventListener('wheel',wheel);el.removeEventListener('gesturestart',gestureStart);el.removeEventListener('gesturechange',gestureStart);};},[viewport,zoom]);
 function point(event){const box=area.current.getBoundingClientRect(),ratio=previewZoom.current?previewZoom.current/renderedZoom.current:1;return viewport.convertToPdfPoint((event.clientX-box.left)/ratio,(event.clientY-box.top)/ratio);}
 function previewScale(value,pdfPoint,x,y){const next=clampZoom(value);previewZoom.current=next;anchor.current={pdf:pdfPoint,x,y};if(zoomFrame.current)return;zoomFrame.current=requestAnimationFrame(()=>{zoomFrame.current=null;if(!area.current||!scroll.current||!viewport)return;const z=previewZoom.current/renderedZoom.current,p=viewport.convertToViewportPoint(...anchor.current.pdf);area.current.style.transformOrigin='0 0';area.current.style.transform=`scale(${z})`;area.current.classList.add('pdf-zoom-preview');scroll.current.scrollLeft=area.current.offsetLeft+p[0]*z-anchor.current.x;scroll.current.scrollTop=area.current.offsetTop+p[1]*z-anchor.current.y;});}
 function commitZoom(){clearTimeout(zoomTimer.current);zoomTimer.current=setTimeout(()=>{zoomTimer.current=null;if(previewZoom.current!=null){setFit('');setZoom(previewZoom.current);}},160);}
 function zoomAt(value,x,y){if(!viewport||!scroll.current)return;const box=scroll.current.getBoundingClientRect();previewScale(value,point({clientX:x,clientY:y}),x-box.left,y-box.top);commitZoom();}
 function centeredZoom(value){const r=scroll.current?.getBoundingClientRect();if(r)zoomAt(value,r.left+r.width/2,r.top+r.height/2);}
 function drawFrame(){if(frame.current)return;frame.current=requestAnimationFrame(()=>{frame.current=null;const s=stroke.current;if(s&&!s.erase)sendPreview(s.move?s.preview:s);if(s)setDraft(s.erase?{erase:true}:{...(s.move?s.preview:s),points:(s.move?s.preview:s).points});});}
 function eraseAt(p){const s=stroke.current;for(const o of state.objects)if(o.page===page&&!s.removed.has(o.id)&&touchesObject(o,p,8/zoom))s.removed.add(o.id);drawFrame();}
 function startPan(event){scroll.current.setPointerCapture(event.pointerId);gesture.current={kind:'pan',id:event.pointerId,x:event.clientX,y:event.clientY,left:scroll.current.scrollLeft,top:scroll.current.scrollTop};}
 function down(event){
  if(!viewport||event.target.closest('textarea,a,button')||(event.pointerType==='mouse'&&event.button!==0))return;
  if(event.pointerType==='touch'){
   if(stroke.current?.pointerType==='pen')return;touches.current.set(event.pointerId,{x:event.clientX,y:event.clientY});scroll.current.setPointerCapture(event.pointerId);
   if(touches.current.size===2){event.preventDefault();sendPreview(null);stroke.current=null;setDraft(null);const [a,b]=[...touches.current.values()],x=(a.x+b.x)/2,y=(a.y+b.y)/2,r=scroll.current.getBoundingClientRect();gesture.current={kind:'pinch',distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:previewZoom.current||renderedZoom.current,pdf:point({clientX:x,clientY:y}),x:x-r.left,y:y-r.top};return;}
   if(!fingerInk||tool==='hand'||space.current){event.preventDefault();startPan(event);return;}
  }
  if(tool==='hand'||space.current){event.preventDefault();startPan(event);return;}
  if(!editable||rendering&&renderedPage.current!==page)return;const p=point(event),id=event.target.closest('[data-object]')?.dataset.object;
  if(tool==='select'){
   setSelected(id||null);if(!id)return;event.preventDefault();const original=state.objects.find(o=>o.id===id);stroke.current={id:original.id,move:true,start:p,original,preview:original,resize:event.target.dataset.resize==='true',pointerId:event.pointerId,pointerType:event.pointerType};
  }else if(tool==='text'){event.preventDefault();setText({point:p,value:'',...properties.text});return;}
  else if(tool==='erase'){event.preventDefault();stroke.current={erase:true,removed:new Set(),pointerId:event.pointerId,pointerType:event.pointerType};eraseAt(p);}
  else {event.preventDefault();stroke.current={id:crypto.randomUUID(),type:tool,page,...(drawing?{pageId:state.pageIds?.[page-1]}:{}),...properties[bucket],points:[p],pointerId:event.pointerId,pointerType:event.pointerType};drawFrame();}
  if(stroke.current)scroll.current.setPointerCapture(event.pointerId);
 }
 function move(event){
  if(touches.current.has(event.pointerId)){touches.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(gesture.current?.kind==='pinch'&&touches.current.size>=2){event.preventDefault();const [a,b]=[...touches.current.values()],g=gesture.current,r=scroll.current.getBoundingClientRect();previewScale(g.zoom*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,g.distance),g.pdf,(a.x+b.x)/2-r.left,(a.y+b.y)/2-r.top);return;}}
  const g=gesture.current;if(g?.kind==='pan'&&g.id===event.pointerId){event.preventDefault();scroll.current.scrollLeft=g.left+g.x-event.clientX;scroll.current.scrollTop=g.top+g.y-event.clientY;return;}
  const s=stroke.current;if(!s||s.pointerId!==event.pointerId)return;event.preventDefault();const p=point(event);
  if(s.erase){eraseAt(p);return;}
  if(s.move){const dx=p[0]-s.start[0],dy=p[1]-s.start[1],o=s.original,a=o.points[0],b=o.points.at(-1),sx=s.resize&&Math.abs(b[0]-a[0])>.01?(b[0]-a[0]+dx)/(b[0]-a[0]):1,sy=s.resize&&Math.abs(b[1]-a[1])>.01?(b[1]-a[1]+dy)/(b[1]-a[1]):1;s.preview={...o,...(s.resize&&o.type==='text'?{fontSize:Math.max(6,Math.min(144,(o.fontSize||Math.max(8,o.width*6))+dx/4))}:{}),points:o.points.map(v=>s.resize?[a[0]+(v[0]-a[0])*sx,a[1]+(v[1]-a[1])*sy]:[v[0]+dx,v[1]+dy])};}
  else if(['pen','highlight'].includes(s.type)){const coalesced=event.nativeEvent.getCoalescedEvents?.();for(const item of coalesced?.length?coalesced:[event])appendPoint(s,point(item));}
  else s.points=[s.points[0],p];drawFrame();
 }
 function finishStroke(){const s=stroke.current;if(!s)return;sendPreview(null);cancelAnimationFrame(frame.current);frame.current=null;stroke.current=null;setDraft(null);
  if(s.erase){if(s.removed.size)commit(state.objects.filter(o=>!s.removed.has(o.id)));}
  else if(s.move){if(s.preview!==s.original)commit(state.objects.map(o=>o.id===s.id?s.preview:o));}
  else {const {pointerId,pointerType,...object}=s;if(object.points.length&&(['pen','highlight'].includes(object.type)||object.points.length>1))commit([...state.objects,{...object,points:[...object.points]}]);}
 }
 function up(event){if(gesture.current?.kind==='pinch')commitZoom();if(stroke.current?.pointerId===event.pointerId)finishStroke();touches.current.delete(event.pointerId);if(gesture.current){if(touches.current.size===1){const [id,p]=[...touches.current][0];gesture.current={kind:'pan',id,x:p.x,y:p.y,left:scroll.current.scrollLeft,top:scroll.current.scrollTop};}else gesture.current=null;}}
 function cancel(event){if(gesture.current?.kind==='pinch'){commitZoom();stroke.current=null;setDraft(null);}else if(stroke.current?.pointerId===event.pointerId)finishStroke();touches.current.delete(event.pointerId);gesture.current=null;}
 function finishText(){if(!text)return;if(text.value.trim())commit([...state.objects.filter(o=>o.id!==text.id),{id:text.id||crypto.randomUUID(),type:'text',page,color:text.color,width:text.width||2,fontSize:text.fontSize||16,points:[text.point],text:text.value}]);setText(null);}
 function editText(object){if(editable){setSelected(object.id);setText({id:object.id,point:object.points[0],value:object.text,color:object.color,width:object.width,fontSize:object.fontSize||Math.max(8,object.width*6)});}}
 function keys(event){if(event.target.closest('input,textarea,[contenteditable=true],[role=menu],[role=dialog]'))return;const k=event.key.toLowerCase(),ctrl=event.ctrlKey||event.metaKey;
  if(ctrl&&k==='f'){event.preventDefault();event.stopPropagation();setSearching(true);return;}
  if(ctrl&&k==='d'){event.preventDefault();shapeButton.current?.querySelector('button')?.click();}
  else if(ctrl&&event.shiftKey&&['e','h'].includes(k)){event.preventDefault();if(!event.repeat)chooseTool(k==='h'?'highlight':tool==='pen'?'erase':'pen');}
  else if(ctrl&&k==='z'){event.preventDefault();event.stopPropagation();finishStroke();undoPdf(e,event.shiftKey);}
  else if(!ctrl&&!event.altKey&&k==='t'){chooseTool('text');event.preventDefault();}
  else if(event.code==='Space'){event.preventDefault();space.current=true;}
  else if(event.key==='Escape'){chooseTool('select');setText(null);setSelected(null);setSearching(false);}
  else if(event.key==='Delete'&&selected){event.preventDefault();commit(state.objects.filter(o=>o.id!==selected));setSelected(null);}
 }
 async function destination(dest){if(!pdf)return;const value=typeof dest==='string'?await pdf.getDestination(dest):dest;if(Array.isArray(value)&&value[0]!=null){const n=typeof value[0]==='number'?value[0]:await pdf.getPageIndex(value[0]);navigatePage(n+1);}}
 async function search(){if(!pdf)return;const token=++searchToken.current;setSearchBusy(true);setMatches([]);try{const found=[];let hasText=false;const q=query.trim().toLocaleLowerCase();if(!pageTexts.current){const index=await window.desktop.pdf.prepareIndex?.({workspace:mode,id:note.id});if(token!==searchToken.current)return;pageTexts.current=index?.pages;setSearchNote(index?.truncated?'문서의 첫 200만 글자에서 검색합니다.':'');}for(let n=1;q&&n<=pdf.numPages;n++){let content;if(pageTexts.current?.[n-1]!=null){const value=pageTexts.current[n-1];hasText ||= Boolean(value.trim());if(!value.toLocaleLowerCase().includes(q))continue;}content=await readPdfText(await pdf.getPage(n));hasText ||= content.items.some(i=>i.str?.trim());for(const m of matchingItems(content.items,q))found.push({...m,page:n});if(token!==searchToken.current)return;}setMatches(found);setMatchIndex(0);setSearchNote(hasText?'': '검색 가능한 텍스트가 없는 PDF입니다.');if(found.length)navigatePage(found[0].page);}catch(error){setSearchNote(error.message);}finally{if(token===searchToken.current)setSearchBusy(false);}}
 const match=matches[matchIndex],highlighted=new Set(match?.page===page?match.indexes:[]);
 useEffect(()=>{if(!match||match.page!==page||!viewport||!scroll.current)return;const item=pageItems[match.indexes[0]];if(!item)return;const p=viewport.convertToViewportPoint(item.transform[4],item.transform[5]);scroll.current.scrollTop=Math.max(0,p[1]-scroll.current.clientHeight/2);},[matchIndex,matches,viewport,pageItems]);
 const currentShape=shapes.find(([id])=>id===tool),visibleObjects=state.objects.filter(o=>o.page===page&&o.id!==draft?.id&&o.id!==text?.id&&!stroke.current?.removed?.has(o.id));
 const status=mergeSaveStatus(state.saving?'PC에 저장 중…':state.error&&state.dirty?'기기에 초안 보관':state.dirty?'저장 대기':state.loading?'불러오는 중…':'저장됨',titleStatus);
 return <section ref={root} className={`content workspace pdf-workspace ${fullscreen?'document-fullscreen':''}`} tabIndex="0" onKeyDown={keys} onKeyUp={event=>{if(event.code==='Space')space.current=false;}} onBlur={event=>{if(!event.currentTarget.contains(event.relatedTarget))space.current=false;}}>

  {titleError?<p role="alert" className="error-message">{titleError}</p>:null}
  {loadStack?<details className="pdf-error-detail"><summary>PDF 오류 상세</summary><pre>{loadStack}</pre></details>:null}
  {loadError?<p className="error-message" role="alert">{loadError}<button onClick={()=>setRetry(v=>v+1)}>다시 불러오기</button></p>:null}
  {state.error?<p className="error-message" role="alert">{state.error} {state.dirty?<><button onClick={()=>persist(e)}>저장 재시도</button><button onClick={async()=>{backup(e);const doc=await window.desktop.pdf.get({workspace:mode,id:note.id});e.savedObjects=doc.objects;publish(e,{...doc,dirty:false,error:''});}}>최신 내용 보기</button><button onClick={async()=>{try{const bytes=await window.desktop.pdf.bytes({workspace:mode,id:note.id}),copy=await window.desktop.pdf.import({workspace:mode,folder:note.folder,name:title+' 필기 사본.pdf',bytes});await window.desktop.pdf.save({workspace:mode,id:copy.note.id,revision:0,objects:state.objects});publish(e,{error:'내 필기를 보관함에 사본으로 저장했습니다.'});}catch(error){publish(e,{error:error.message});}}}>내 필기 사본 저장</button></>:null}</p>:null}
  {pageDialog?<Modal title="그리기 페이지 삭제" onClose={()=>setPageDialog(null)}><p className="hint">{pageDialog}쪽과 이 페이지의 필기·텍스트·도형을 삭제할까요? 실행 취소로 되돌릴 수 있습니다.</p><div className="conversion-actions"><button className="secondary" onClick={()=>setPageDialog(null)}>취소</button><button className="primary danger" onClick={()=>pageAction('delete',pageDialog)}>페이지 삭제</button></div></Modal>:null}
  <div className="pdf-frame"><div className="document-toolbar"><button className="document-back" aria-label="보관함으로 돌아가기" onClick={async()=>{await persist(e);if(await saveTitle()!==false)onBack();}}><Icon name="back"/></button><button aria-label="페이지 미리보기" aria-expanded={pagesOpen} onClick={()=>setPagesOpen(v=>!v)}><Icon name="sidebar"/></button><div className="document-identity"><input aria-label="PDF 제목" value={title} readOnly={!editable} maxLength={120} onChange={ev=>setTitle(ev.target.value)} onBlur={saveTitle} onKeyDown={ev=>{if(ev.key==='Enter')ev.currentTarget.blur();}}/><DocumentMetadata folder={note.folder} extra={`${page} / ${pdf?.numPages||note.pages}`}/></div><div className="document-actions"><span role="status" className="pdf-save-state">{status}</span><Menu className="pdf-export" label="PDF 내보내기" trigger={<><Icon name="download"/><span>내보내기</span><Icon name="chevronDown"/></>}>{close=><>{[['annotated','필기 포함 PDF'],['original','원본 PDF']].map(([format,label])=><button role="menuitem" key={format} onClick={async()=>{close();await persist(e);if(e.state.dirty){publish(e,{error:'저장하지 못한 필기가 있습니다. 저장 후 내보내 주세요.'});return;}try{await window.desktop.pdf.export({workspace:mode,id:note.id,annotated:format==='annotated'});}catch(error){publish(e,{error:error.message});}}}>{label}</button>)}</>}</Menu><button aria-label={fullscreen?'전체화면 종료':'전체화면'} aria-pressed={fullscreen} onClick={toggleFullscreen}><Icon name={fullscreen?'collapse':'expand'}/></button></div></div>
   <div className="pdf-toolbar" role="toolbar" aria-label="PDF 도구">

    {['select','hand','pen','highlight','erase','text'].map(id=><button key={id} disabled={!editable&&!['select','hand'].includes(id)} aria-label={toolNames[id]} aria-pressed={tool===id} title={toolNames[id]+' · '+(pdfShortcuts[id]||'')} onClick={()=>chooseTool(id)}><Icon name={toolIcons[id]}/></button>)}
    <span ref={shapeButton}><Menu label="도형" shortcut="Ctrl + D" trigger={<><Icon name={toolIcons[currentShape?.[0]||'rect']}/><span className="pdf-tool-label">{currentShape?.[1]||'도형'}</span><Icon name="chevronDown"/></>} disabled={!editable}>{close=><>{shapes.map(([id,label],index)=><button role="menuitemradio" aria-checked={tool===id} key={id} data-shortcut-key={index+1} title={`Ctrl + D → ${index+1}`} onClick={()=>{chooseTool(id);close();}}><Icon name={toolIcons[id]}/>{label}<kbd>{index+1}</kbd>{tool===id?'✓':null}</button>)}</>}</Menu></span>
    <div className="pdf-quick-properties"><button className="pdf-color-dot" aria-label="현재 필기 색상" title="현재 필기 색상" style={{'--ink-color':style.color}} disabled/><span>{tool==='text'||activeObject?.type==='text'?`${style.fontSize||16}pt`:`${style.width}pt`}</span></div>
    <PdfProperties><div className="pdf-tool-options"><strong>{activeObject?'선택한 객체':toolNames[tool]||'필기'} 속성</strong><div className="pdf-swatches">{['#222222','#387a97','#ca6b62','#e9bd52','#76a886'].map(color=><button key={color} aria-label={'색상 '+color} aria-pressed={style.color===color} style={{'--ink-color':color}} onClick={()=>property({color})}/>)}</div><label>색상<input aria-label="필기 색상" type="color" value={style.color} disabled={!editable} onChange={ev=>property({color:ev.target.value})}/></label>{tool==='text'||activeObject?.type==='text'?<label>글자 크기<input aria-label="텍스트 크기" type="number" min="6" max="144" value={style.fontSize||16} onChange={ev=>property({fontSize:Math.max(6,Math.min(144,Number(ev.target.value)||16))})}/></label>:<><div className="pdf-width-presets">{[1,2,4].map(width=><button key={width} aria-pressed={style.width===width} onClick={()=>property({width})}>{width}pt</button>)}</div><label>굵기<input aria-label="필기 굵기" type="range" min="1" max="8" step=".5" value={style.width} onChange={ev=>property({width:Number(ev.target.value)})}/>{style.width}</label></>}{activeObject?.type==='text'?<button onClick={()=>editText(activeObject)}>텍스트 수정</button>:null}<label><input type="checkbox" checked={fingerInk} onChange={ev=>{setFingerInk(ev.target.checked);write(prefsKey+':finger',ev.target.checked);}}/>손가락 필기</label><label>화면 용지색<select aria-label="화면 용지색" value={paper} onChange={ev=>setPaper(ev.target.value)}><option value="original">원본</option><option value="warm">따뜻한 톤</option><option value="dim">밝기 낮추기</option></select></label><small>보기 전용이며 내보내기에는 적용되지 않습니다.</small></div></PdfProperties>
    <span className="pdf-tool-divider"/><button aria-label="실행 취소" title={pdfShortcuts.undo} disabled={!e.history.length||!editable} onClick={()=>undoPdf(e)}>↶</button><button aria-label="다시 실행" title={pdfShortcuts.redo} disabled={!e.redo.length||!editable} onClick={()=>undoPdf(e,true)}>↷</button>
   </div>
   <div className={`pdf-body ${pagesOpen?'pages-open':''}`}>
    <aside className="pdf-pages" inert={!pagesOpen||undefined} aria-label="PDF 페이지 탐색"><div className="pdf-rail-tabs"><button aria-pressed={railTab==='pages'} onClick={()=>setRailTab('pages')}>페이지</button><button aria-pressed={railTab==='outline'} onClick={()=>setRailTab('outline')}>목차</button><button aria-label="페이지 패널 닫기" onClick={()=>setPagesOpen(false)}>×</button></div>{railTab==='pages'&&pdf?<PdfPageRail objects={state.objects} drawing={drawing} canEdit={editable} onAction={(action,n)=>action==='delete'?setPageDialog(n):pageAction(action,n)} pdf={pdf} page={page} open={pagesOpen} onOpen={navigatePage}/>:railTab==='outline'?<Outline items={outline} onOpen={destination}/>:null}</aside>
    <div ref={scroll} className={`pdf-scroll ${tool!=='select'?'pdf-drawing':''}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel} onLostPointerCapture={event=>{if(stroke.current?.pointerId===event.pointerId)finishStroke();}} onScroll={()=>{viewRef.current={...viewRef.current,left:scroll.current.scrollLeft,top:scroll.current.scrollTop};}}>
     {!pdf?<div className="pdf-loading" role="status"><div className="pdf-loading-sheet"/>PDF를 불러오는 중{loadProgress!=null?` · ${loadProgress}%`:'…'}</div>:<div ref={area} className={`pdf-sheet tool-${tool} paper-${paper}`} style={viewport?{width:viewport.width,height:viewport.height,'--total-scale-factor':viewport.scale,'--scale-round-x':'1px','--scale-round-y':'1px'}:undefined}>
      <canvas ref={canvas}/><div ref={layer} className="textLayer" style={{pointerEvents:tool==='select'?'auto':'none'}}/>
      <div className="pdf-search-marks" aria-hidden="true">{viewport?Array.from(highlighted).map(i=>{const item=pageItems[i];if(!item)return null;const p=viewport.convertToViewportPoint(item.transform[4],item.transform[5]);return <mark key={i} style={{left:p[0],top:p[1]-item.height*viewport.scale,width:Math.max(2,item.width*viewport.scale),height:Math.max(4,item.height*viewport.scale)}}/>;}):null}</div>
      {text&&viewport?<PdfTextEditor text={text} viewport={viewport} sheet={area} root={root} onChange={setText} onFinish={finishText} onCancel={()=>{setText(null);setTool('select');}}/>:null}
      <svg className="pdf-ink" width={viewport?.width||0} height={viewport?.height||0} onDoubleClick={event=>{const id=event.target.closest('[data-object]')?.dataset.object,o=state.objects.find(o=>o.id===id);if(o?.type==='text')editText(o);}} style={{pointerEvents:tool==='select'?'none':'auto'}}>{viewport?visibleObjects.map(o=><PdfInkObject key={o.id} object={o} viewport={viewport} selected={selected===o.id&&tool==='select'}/>):null}{viewport?remoteInk.filter(v=>v.object.page===page&&!state.objects.some(o=>o.id===v.object.id)).map(v=><g className="pdf-remote-preview" style={{pointerEvents:'none'}} key={v.actor+':'+v.session}><PdfInkObject object={v.object} viewport={viewport} preview/></g>):null}{viewport&&draft&&!draft.erase?<PdfInkObject object={draft} viewport={viewport} selected={false}/>:null}</svg>
      {viewport&&tool==='select'?links.map((a,i)=>{const r=viewport.convertToViewportRectangle(a.rect),style={left:Math.min(r[0],r[2]),top:Math.min(r[1],r[3]),width:Math.abs(r[2]-r[0]),height:Math.abs(r[3]-r[1])};return a.url?<a key={i} className="pdf-link" style={style} href={a.url} target="_blank" rel="noopener noreferrer" aria-label="PDF 링크 열기" onClick={event=>{event.preventDefault();window.desktop.memos.openLink(a.url);}}/>:<button key={i} className="pdf-link" style={style} aria-label="PDF 내부 링크 이동" onClick={()=>destination(a.dest)}/>;}):null}
     </div>}
     {pdf&&rendering?<div className="pdf-render-state" role="status">페이지를 그리는 중…</div>:null}
    </div>
   </div>
   {searching?<form className="pdf-search-bar" onSubmit={ev=>{ev.preventDefault();search();}}><Icon name="search"/><input autoFocus aria-label="PDF 검색" value={query} onChange={ev=>setQuery(ev.target.value)}/><button disabled={searchBusy}>찾기</button><span role="status">{searchBusy?'검색 중…':matches.length?`${matchIndex+1} / ${matches.length}`:'0개'}</span><button type="button" aria-label="이전 PDF 검색 결과" disabled={!matches.length} onClick={()=>{const n=(matchIndex-1+matches.length)%matches.length;setMatchIndex(n);navigatePage(matches[n].page);}}>↑</button><button type="button" aria-label="다음 PDF 검색 결과" disabled={!matches.length} onClick={()=>{const n=(matchIndex+1)%matches.length;setMatchIndex(n);navigatePage(matches[n].page);}}>↓</button><button type="button" aria-label="PDF 검색 닫기" onClick={()=>{searchToken.current++;setSearchBusy(false);setSearching(false);setMatches([]);}}>×</button>{searchNote?<small>{searchNote}</small>:null}{match?<small>{match.context}</small>:null}</form>:null}
   <div className="pdf-footer"><button aria-label="PDF 검색 열기" title="PDF 검색 · Ctrl + F" onClick={()=>setSearching(v=>!v)}><Icon name="search"/></button><div className="pdf-page-control"><button aria-label="이전 PDF 페이지" disabled={page<=1} onClick={()=>navigatePage(page-1)}>‹</button><input aria-label="PDF 페이지 번호" type="number" min="1" max={pdf?.numPages||1} value={page} onChange={ev=>navigatePage(Number(ev.target.value)||1)}/> / {pdf?.numPages||note.pages}<button aria-label="다음 PDF 페이지" disabled={!pdf||page>=pdf.numPages} onClick={()=>navigatePage(page+1)}>›</button></div><div className="pdf-zoom-control"><button aria-label="PDF 축소" onClick={()=>centeredZoom(zoom/1.2)}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="PDF 확대" onClick={()=>centeredZoom(zoom*1.2)}>+</button><Menu label="PDF 맞춤" trigger={<><span>{fit==='width'?'너비 맞춤':fit==='page'?'페이지 맞춤':'맞춤'}</span><Icon name="chevronDown"/></>}>{close=><><button role="menuitem" onClick={()=>{close();centeredZoom(zoom*1.2);}}>확대</button><button role="menuitem" onClick={()=>{close();centeredZoom(zoom/1.2);}}>축소</button>{[['width','너비 맞춤'],['page','페이지 맞춤']].map(([kind,label])=><button role="menuitemradio" aria-checked={fit===kind} key={kind} onClick={()=>{close();setFit(kind);}}>{label}{fit===kind?'✓':null}</button>)}</>}</Menu></div></div>
  </div>
 </section>;
}
function Outline({items,onOpen}){return items.length?<ul className="pdf-outline">{items.map((item,i)=><li key={i}><button onClick={()=>{if(item.dest)onOpen(item.dest);else if(/^https?:|^mailto:/i.test(item.url||''))window.desktop.memos.openLink(item.url);}}>{item.title}</button>{item.items?.length?<Outline items={item.items} onOpen={onOpen}/>:null}</li>)}</ul>:<p className="pdf-outline-empty">목차가 없습니다.</p>;}
